export class Constants {
  public static CRAFTTYPE = {
    0: "None",
    1: "X-wing",
    2: "Y-wing",
    3: "A-wing",
    4: "B-wing",
    5: "TIE Fighter",
    6: "TIE Interceptor",
    7: "TIE Bomber",
    8: "TIE Advanced",
    9: "TIE Defender",
    10: "Patch Slot 10",
    11: "Patch Slot 11",
    12: "Missile Boat",
    13: "T-wing",
    14: "Z-95 Headhunter",
    15: "R-41 Starchaser",
    16: "Assault Gunboat",
    17: "Shuttle",
    18: "Escort Shuttle",
    19: "System Patrol Craft",
    20: "Scout Craft",
    21: "Stormtrooper Transport",
    22: "Assault Transport",
    23: "Escort Transport",
    24: "Tug",
    25: "Combat Utility Vehicle",
    26: "Container A",
    27: "Container B",
    28: "Container C",
    29: "Container D",
    30: "Heavy Lifter",
    31: "Unused",
    32: "Bulk Freighter",
    33: "Cargo Ferry",
    34: "Modular Conveyor",
    35: "Container Transport",
    36: "Unused",
    37: "Murrian Transport",
    38: "Corellian Transport",
    39: "Unused",
    40: "Corellian Corvette",
    41: "Modified Corvette",
    42: "Nebulon-B Frigate",
    43: "Modified Frigate",
    44: "C-3 Passenger Liner",
    45: "Carrack Cruiser",
    46: "Strike Cruiser",
    47: "Escort Carrier",
    48: "Dreadnaught",
    49: "Mon Calamari Cruiser",
    50: "Light Mon Calamari Cruiser",
    51: "Interdictor Cruiser",
    52: "Victory-class Star Destroyer",
    53: "Imperator-class Star Destroyer",
    54: "Unused",
    55: "Container E",
    56: "Container F",
    57: "Container G",
    58: "Container H",
    59: "Container I",
    60: "Platform A",
    61: "Platform B",
    62: "Platform C",
    63: "Platform D",
    64: "Platform E",
    65: "Platform F",
    66: "Asteroid R&D Station",
    67: "Asteroid Laser Battery",
    68: "Asteroid Warhead Battery",
    69: "X/7 Factory",
    70: "Satellite 1",
    71: "Satellite 2",
    72: "Unused",
    73: "Unused",
    74: "Unused",
    75: "Mine A",
    76: "Mine B",
    77: "Mine C",
    78: "Unused",
    79: "Unused",
    80: "Probe A",
    81: "Probe B",
    82: "Unused",
    83: "Nav Buoy A",
    84: "Nav Buoy B",
    85: "Unused",
    86: "Asteroid Field",
    87: "Planet",
  };

  public static CRAFTABBR = {
    0: "None",
    1: "X-W",
    2: "Y-W",
    3: "A-W",
    4: "B-W",
    5: "T/F",
    6: "T/I",
    7: "T/B",
    8: "T/A",
    9: "T/D",
    10: "PATCH10",
    11: "PATCH11",
    12: "MIS",
    13: "T-W",
    14: "Z-95",
    15: "R-41",
    16: "GUN",
    17: "SHU",
    18: "E/S",
    19: "SPC",
    20: "SCT",
    21: "TRN",
    22: "ATR",
    23: "ETR",
    24: "TUG",
    25: "CUV",
    26: "CN/A",
    27: "CN/B",
    28: "CN/C",
    29: "CN/D",
    30: "HLF",
    31: "GPLT",
    32: "FRT",
    33: "CARG",
    34: "CNVYR",
    35: "CTRNS",
    36: "MDTRN",
    37: "MUTR",
    38: "CORT",
    39: "M/SC",
    40: "CRV",
    41: "M/CRV",
    42: "FRG",
    43: "M/FRG",
    44: "LINER",
    45: "CRCK",
    46: "STRCK",
    47: "ESC",
    48: "DREAD",
    49: "CRS",
    50: "CRL",
    51: "INT",
    52: "VSD",
    53: "ISD",
    54: "SSD",
    55: "CN/E",
    56: "CN/F",
    57: "CN/G",
    58: "CN/H",
    59: "CN/I",
    60: "PLT/1",
    61: "PLT/2",
    62: "PLT/3",
    63: "PLT/4",
    64: "PLT/5",
    65: "PLT/6",
    66: "R&D FC",
    67: "LAS BAT",
    68: "W LNCHR",
    69: "FAC/1",
    70: "SAT 1",
    71: "SAT/2",
    72: "UNK",
    73: "UNK",
    74: "UNK",
    75: "MINE 1",
    76: "MINE B",
    77: "MINE C",
    78: "UNK",
    79: "UNK",
    80: "PROBE A",
    81: "PROBE B",
    82: "UNK",
    83: "NAV 1",
    84: "NAV 2",
    85: "Asteroid",
    86: "Asteroid",
    87: "Planet",
  };

  public static STATUS = {
    0: "None",
    1: "2X Warheads",
    2: "1/2 Warheads",
    3: "Disabled",
    4: "1/2 Shields",
    5: "No Lasers",
    6: "No Hyperdrive",
    7: "Shields 0%, charging",
    8: "Shields added or 200%",
    9: "Hyperdrive added",
    20: "Invincible",
  };

  public static WARHEAD = {
    0: "None",
    1: "Heavy Rocket",
    2: "Space Bomb",
    3: "Concussion Missile",
    4: "Torpedo",
    5: "Advanced Concussion Missile",
    6: "Advanced Torpedo",
    7: "Mag Pulse Torpedo",
  };

  public static BEAM = {
    0: "None",
    1: "Tractor Beam",
    2: "Jamming Beam",
  };

  public static GROUPAI = {
    0: "Rookie (None)",
    1: "Novice",
    2: "Veteran",
    3: "Officer",
    4: "Ace",
    5: "Top Ace (Invincible)",
  };

  public static MARKINGS = {
    0: "Red (TIE - None)",
    1: "Gold (TIE - Red)",
    2: "Blue (TIE - Gold)",
    3: "Green (TIE - Blue)",
  };

  public static FORMATION = {
    0: "Vic",
    1: "Finger Four",
    2: "Line Astern",
    3: "Line Abreast",
    4: "Echelon Right",
    5: "Echelon Left",
    6: "Double Astern",
    7: "Diamond",
    8: "Stack",
    9: "High X",
    10: "Vic Abreast",
    11: "High Vic",
    12: "Reverse High Vic",
  };

  public static ARRIVALDIFFICULTY = {
    0: "All",
    1: "Easy",
    2: "Medium",
    3: "Hard",
    4: "Medium, Hard",
    5: "Easy, Medium",
  };

  public static CONDITION = {
    0: "Always (true)",
    1: "Created",
    2: "Destroyed",
    3: "Attacked",
    4: "Captured",
    5: "Inspected",
    6: "Boarded",
    7: "Docked",
    8: "Disabled",
    9: "Survived (exist)",
    10: "None (false)",
    11: "Unknown (---)",
    12: "Completed mission",
    13: "Completed Primary Goals",
    14: "Failed Primary Goals",
    15: "Completed Secondary Goals",
    16: "Failed Secondary Goals",
    17: "Completed Bonus Goals",
    18: "Failed Bonus Goals",
    19: "Dropped off",
    20: "Reinforced",
    21: "0% Shields",
    22: "50% Hull",
    23: "Out of Warheads",
    24: "Unknown (arrive?)",
  };

  public static VARIABLETYPE = {
    0: "None",
    1: "Flight Group",
    2: "CraftType (enum)",
    3: "CraftCategory (enum)",
    4: "ObjectCategory (enum)",
    5: "IFF",
    6: "Order (enum)",
    7: "CraftWhen (enum)",
    8: "Global Group",
    9: "Misc (enum)",
    10: "Unknown",
  };

  public static CRAFTCATEGORY = {
    0: "Starfighters",
    1: "Transports",
    2: "Freighters/Containers",
    3: "Starships",
    4: "Utility Craft",
    5: "Platforms/Facilities",
    6: "Mines",
  };

  public static OBJECTCATEGORY = {
    0: "Craft",
    1: "Weapons",
    2: "Space Objects",
  };

  public static TRIGGERAMOUNT = {
    0: "100%",
    1: "75%",
    2: "50%",
    3: "25%",
    4: "At least one",
    5: "All but one",
    6: "Special craft",
    7: "All non-special craft",
    8: "All non-player craft",
    9: "Player's craft",
    10: "100% of first wave",
    11: "75% of first wave",
    12: "50% of first wave",
    13: "25% of first wave",
    14: "At least one of first wave",
    15: "All but one of first wave",
  };

  public static GOALAMOUNT = {
    0: "100%",
    1: "50%",
    2: "At least one",
    3: "All but one",
    4: "Special craft",
  };

  public static ABORTTRIGGER = {
    0: "None",
    1: "0% Shields",
    2: "Systems 75% (fighters and transports only)",
    3: "Out of warheads",
    4: "50% Hull",
    5: "Attacked",
  };

  public static ORDER = {
    0: "Hold Station",
    1: "Go Home",
    2: "Circle",
    3: "Circle and Evade",
    4: "Rendezvous",
    5: "Disabled",
    6: "Await Boarding",
    7: "Attack",
    8: "Attack Escorts",
    9: "Protect",
    10: "Escort",
    11: "Disable",
    12: "Board and Give Cargo",
    13: "Board and Take Cargo",
    14: "Board and Exchange Cargo",
    15: "Board and Capture Cargo",
    16: "Board and Destroy Cargo",
    17: "Pick up",
    18: "Drop off",
    19: "Wait",
    20: "SS Wait",
    21: "SS Patrol Loop",
    22: "SS Await Return",
    23: "SS Launch",
    24: "SS Protect",
    25: "SS Wait and Protect",
    26: "SS Patrol and Attack",
    27: "SS Patrol and Disable",
    28: "SS Hold Steady",
    29: "SS Go Home",
    30: "SS Wait",
    31: "SS Board",
    32: "Board to Repair",
    33: "Hold Station",
    34: "Hold Steady",
    35: "SS Hold Station",
    36: "SS Kamikaze?",
    37: "SS Kamikaze?",
    38: "SS Disabled",
    39: "SS Disabled",
  };

  public static CRAFTWHEN = {
    1: "Boarding",
    2: "Boarded",
    3: "Defence",
    4: "Disabled",
    7: "Special craft",
    8: "Non-special craft",
    9: "Player's craft",
    10: "Non-player's craft",
  };

  public static MISC = {
    0: "Rookie craft",
    1: "Novice craft",
    2: "Officer craft",
    3: "Veteran craft",
    4: "Ace craft",
    5: "Top Ace craft",
    6: "Stationary craft",
    7: "Craft returning to base",
    8: "Non-evading craft",
    9: "Craft in formation",
    10: "Rendezvousing craft",
    11: "Disabled craft",
    12: "Craft awaiting boarding",
    13: "Attacking craft",
    14: "Craft atatcking escorts",
    15: "Protecting craft",
    16: "Escorting craft",
    17: "Disabling craft",
    18: "Delivering craft",
    19: "Siezing craft",
    20: "Exchanging craft",
    21: "Capturing craft",
    22: "Craft destroying cargo",
    23: "Picked up craft",
    24: "Dropped off craft",
    25: "Waiting fighters",
    26: "Waiting starships",
    27: "Patrolling starships",
    28: "SS awaiting returns",
    29: "SS waiting to launch",
    30: "SS waiting to be boarded",
    31: "SS witing for boarding craft to appear",
    32: "SS attacking",
    33: "SS disabling",
    34: "SS disabling?",
    35: "SS flying home",
    36: "Rebels",
    37: "Imperials",
    39: "Spacecraft",
    40: "Weapons",
    41: "Space objects",
    46: "Fighters",
    47: "Transports",
    48: "Freighters",
    49: "Utility craft",
    50: "Startships",
    51: "Platforms",
    54: "Mines",
  };

  public static EVENTTYPE = {
    3: "Page Break",
    4: "Title Text",
    5: "Caption Text",
    6: "Move Map",
    7: "Zoom Map",
    8: "Clear FG Tags",
    9: "FG Tag 1",
    10: "FG Tag 2",
    11: "FG Tag 3",
    12: "FG Tag 4",
    13: "FG Tag 5",
    14: "FG Tag 6",
    15: "FG Tag 7",
    16: "FG Tag 8",
    17: "Clear Text Tags",
    18: "Text Tag 1",
    19: "Text Tag 2",
    20: "Text Tag 3",
    21: "Text Tag 4",
    22: "Text Tag 5",
    23: "Text Tag 6",
    24: "Text Tag 7",
    25: "Text Tag 8",
    34: "End Briefing",
  };

  public static TEXTTAGCOLOR = {
    0: "Green",
    1: "Red",
    2: "Purple",
    3: "Blue",
    4: "Red",
    5: "Light Red",
    6: "Gray",
    7: "White",
  };

  public static BRIEFINGOFFICERS = {
    1: "Both officers",
    2: "Flight Officer",
    3: "Secret Order",
  };

  public static QUESTIONTYPE = {
    0: "None",
    1: "Primary Goals",
    2: "Secondary Goals",
  };

  public static QUESTIONCONDITION = {
    0: "None",
    4: "Successful",
    5: "Failed",
  };

  public static MESSAGECOLOR = {
    0: "Red",
    1: "Green",
    2: "Blue",
    3: "Purple",
  };

  public static IFFCOLOR = {
    0: "Green",
    1: "Red",
    2: "Purple",
    3: "Blue",
  };

  public static PILOTSTATUS = {
    0: "Alive",
    1: "Captured",
    2: "Killed",
  };

  public static PILOTRANK = {
    0: "Cadet",
    1: "Officer",
    2: "Lieutenant",
    3: "Captain",
    4: "Commander",
    5: "General",
  };

  public static PILOTDIFFICULTY = {
    0: "Easy",
    1: "Medium",
    2: "Hard",
  };

  public static TRAININGCRAFT = {
    0: "TIE Fighter",
    1: "TIE Interceptor",
    2: "TIE Bomber",
    3: "TIE Advanced",
    4: "Assault Gunboat",
    5: "TIE Defender",
    6: "Missile Boat",
  };

  public static TRAININGCRAFTABBR = {
    0: "T/F",
    1: "T/I",
    2: "T/B",
    3: "T/A",
    4: "GUN",
    5: "T/D",
    6: "MIS",
  };

  public static BATTLESTATUS = {
    0: "None",
    1: "In Progress",
    2: "Incomplete",
    3: "Completed",
  };

  public static SECRETORDER = {
    0: "None",
    1: "First Circle",
    2: "Second Circle",
    3: "Third Circle",
    4: "Fourth Circle",
    5: "Inner Circle",
    6: "Emperor's Hand",
    7: "Emperor's Eyes",
    8: "Emperor's Voice",
    9: "Emperor's Reach",
  };

}

export enum CraftType {
  none = 0,
  xwing = 1,
  ywing = 2,
  awing = 3,
  bwing = 4,
  tieFighter = 5,
  tieInterceptor = 6,
  tieBomber = 7,
  tieAdvanced = 8,
  tieDefender = 9,
  patchSlot10 = 10,
  patchSlot11 = 11,
  missileBoat = 12,
  twing = 13,
  z95Headhunter = 14,
  r41Starchaser = 15,
  assaultGunboat = 16,
  shuttle = 17,
  escortShuttle = 18,
  systemPatrolCraft = 19,
  scoutCraft = 20,
  stormtrooperTransport = 21,
  assaultTransport = 22,
  escortTransport = 23,
  tug = 24,
  combatUtilityVehicle = 25,
  containerA = 26,
  containerB = 27,
  containerC = 28,
  containerD = 29,
  heavyLifter = 30,
  unused = 31,
  bulkFreighter = 32,
  cargoFerry = 33,
  modularConveyor = 34,
  containerTransport = 35,
  // duplicate unused = 36,
  murrianTransport = 37,
  corellianTransport = 38,
  // duplicate unused = 39,
  corellianCorvette = 40,
  modifiedCorvette = 41,
  nebulonBFrigate = 42,
  modifiedFrigate = 43,
  c3PassengerLiner = 44,
  carrackCruiser = 45,
  strikeCruiser = 46,
  escortCarrier = 47,
  dreadnaught = 48,
  monCalamariCruiser = 49,
  lightMonCalamariCruiser = 50,
  interdictorCruiser = 51,
  victoryclassStarDestroyer = 52,
  imperatorclassStarDestroyer = 53,
  // duplicate unused = 54,
  containerE = 55,
  containerF = 56,
  containerG = 57,
  containerH = 58,
  containerI = 59,
  platformA = 60,
  platformB = 61,
  platformC = 62,
  platformD = 63,
  platformE = 64,
  platformF = 65,
  asteroidRnDStation = 66,
  asteroidLaserBattery = 67,
  asteroidWarheadBattery = 68,
  x7Factory = 69,
  satellite1 = 70,
  satellite2 = 71,
  // duplicate unused = 72,
  // duplicate unused = 73,
  // duplicate unused = 74,
  mineA = 75,
  mineB = 76,
  mineC = 77,
  // duplicate unused = 78,
  // duplicate unused = 79,
  probeA = 80,
  probeB = 81,
  // duplicate unused = 82,
  navBuoyA = 83,
  navBuoyB = 84,
  // duplicate unused = 85,
  asteroidField = 86,
  planet = 87,
}

export enum CraftAbbr {
  none = 0,
  xw = 1,
  yw = 2,
  aw = 3,
  bw = 4,
  tf = 5,
  ti = 6,
  tb = 7,
  ta = 8,
  td = 9,
  patch10 = 10,
  patch11 = 11,
  mis = 12,
  tw = 13,
  z95 = 14,
  r41 = 15,
  gun = 16,
  shu = 17,
  es = 18,
  spc = 19,
  sct = 20,
  trn = 21,
  atr = 22,
  etr = 23,
  tug = 24,
  cuv = 25,
  cna = 26,
  cnb = 27,
  cnc = 28,
  cnd = 29,
  hlf = 30,
  gplt = 31,
  frt = 32,
  carg = 33,
  cnvyr = 34,
  ctrns = 35,
  mdtrn = 36,
  mutr = 37,
  cort = 38,
  msc = 39,
  crv = 40,
  mcrv = 41,
  frg = 42,
  mfrg = 43,
  liner = 44,
  crck = 45,
  strck = 46,
  esc = 47,
  dread = 48,
  crs = 49,
  crl = 50,
  int = 51,
  vsd = 52,
  isd = 53,
  ssd = 54,
  cne = 55,
  cnf = 56,
  cng = 57,
  cnh = 58,
  cni = 59,
  plt1 = 60,
  plt2 = 61,
  plt3 = 62,
  plt4 = 63,
  plt5 = 64,
  plt6 = 65,
  rnDFc = 66,
  lasBat = 67,
  wLnchr = 68,
  fac1 = 69,
  sat1 = 70,
  sat2 = 71,
  unk = 72,
  // duplicate unk = 73,
  // duplicate unk = 74,
  mine1 = 75,
  mineB = 76,
  mineC = 77,
  // duplicate unk = 78,
  // duplicate unk = 79,
  probeA = 80,
  probeB = 81,
  // duplicate unk = 82,
  nav1 = 83,
  nav2 = 84,
  asteroid = 85,
  // duplicate asteroid = 86,
  planet = 87,
}

export enum Status {
  none = 0,
  n2XWarheads = 1,
  n12Warheads = 2,
  disabled = 3,
  n12Shields = 4,
  noLasers = 5,
  noHyperdrive = 6,
  shields0PercentCharging = 7,
  shieldsAddedOr200Percent = 8,
  hyperdriveAdded = 9,
  invincible = 20,
}

export enum Warhead {
  none = 0,
  heavyRocket = 1,
  spaceBomb = 2,
  concussionMissile = 3,
  torpedo = 4,
  advancedConcussionMissile = 5,
  advancedTorpedo = 6,
  magPulseTorpedo = 7,
}

export enum Beam {
  none = 0,
  tractorBeam = 1,
  jammingBeam = 2,
}

export enum GroupAI {
  rookieNone = 0,
  novice = 1,
  veteran = 2,
  officer = 3,
  ace = 4,
  topAceInvincible = 5,
}

export enum Markings {
  redTieNone = 0,
  goldTieRed = 1,
  blueTieGold = 2,
  greenTieBlue = 3,
}

export enum Formation {
  vic = 0,
  fingerFour = 1,
  lineAstern = 2,
  lineAbreast = 3,
  echelonRight = 4,
  echelonLeft = 5,
  doubleAstern = 6,
  diamond = 7,
  stack = 8,
  highX = 9,
  vicAbreast = 10,
  highVic = 11,
  reverseHighVic = 12,
}

export enum ArrivalDifficulty {
  all = 0,
  easy = 1,
  medium = 2,
  hard = 3,
  mediumHard = 4,
  easyMedium = 5,
}

export enum Condition {
  alwaysTrue = 0,
  created = 1,
  destroyed = 2,
  attacked = 3,
  captured = 4,
  inspected = 5,
  boarded = 6,
  docked = 7,
  disabled = 8,
  survivedExist = 9,
  noneFalse = 10,
  unknown = 11,
  completedMission = 12,
  completedPrimaryGoals = 13,
  failedPrimaryGoals = 14,
  completedSecondaryGoals = 15,
  failedSecondaryGoals = 16,
  completedBonusGoals = 17,
  failedBonusGoals = 18,
  droppedOff = 19,
  reinforced = 20,
  n0PercentShields = 21,
  n50PercentHull = 22,
  outOfWarheads = 23,
  unknownArrive = 24,
}

export enum VariableType {
  none = 0,
  flightGroup = 1,
  craftTypeEnum = 2,
  craftCategoryEnum = 3,
  objectCategoryEnum = 4,
  iff = 5,
  orderEnum = 6,
  craftWhenEnum = 7,
  globalGroup = 8,
  miscEnum = 9,
  unknown = 10,
}

export enum CraftCategory {
  starfighters = 0,
  transports = 1,
  freightersContainers = 2,
  starships = 3,
  utilityCraft = 4,
  platformsFacilities = 5,
  mines = 6,
}

export enum ObjectCategory {
  craft = 0,
  weapons = 1,
  spaceObjects = 2,
}

export enum TriggerAmount {
  n100Percent = 0,
  n75Percent = 1,
  n50Percent = 2,
  n25Percent = 3,
  atLeastOne = 4,
  allButOne = 5,
  specialCraft = 6,
  allNonspecialCraft = 7,
  allNonplayerCraft = 8,
  playersCraft = 9,
  n100PercentOfFirstWave = 10,
  n75PercentOfFirstWave = 11,
  n50PercentOfFirstWave = 12,
  n25PercentOfFirstWave = 13,
  atLeastOneOfFirstWave = 14,
  allButOneOfFirstWave = 15,
}

export enum GoalAmount {
  n100Percent = 0,
  n50Percent = 1,
  atLeastOne = 2,
  allButOne = 3,
  specialCraft = 4,
}

export enum AbortTrigger {
  none = 0,
  n0PercentShields = 1,
  systems75PercentFightersAndTransportsOnly = 2,
  outOfWarheads = 3,
  n50PercentHull = 4,
  attacked = 5,
}

export enum Order {
  holdStation = 0,
  goHome = 1,
  circle = 2,
  circleAndEvade = 3,
  rendezvous = 4,
  disabled = 5,
  awaitBoarding = 6,
  attack = 7,
  attackEscorts = 8,
  protect = 9,
  escort = 10,
  disable = 11,
  boardAndGiveCargo = 12,
  boardAndTakeCargo = 13,
  boardAndExchangeCargo = 14,
  boardAndCaptureCargo = 15,
  boardAndDestroyCargo = 16,
  pickUp = 17,
  dropOff = 18,
  wait = 19,
  ssWait = 20,
  ssPatrolLoop = 21,
  ssAwaitReturn = 22,
  ssLaunch = 23,
  ssProtect = 24,
  ssWaitAndProtect = 25,
  ssPatrolAndAttack = 26,
  ssPatrolAndDisable = 27,
  ssHoldSteady = 28,
  ssGoHome = 29,
  // duplicate ssWait = 30,
  ssBoard = 31,
  boardToRepair = 32,
  // duplicate holdStation = 33,
  holdSteady = 34,
  ssHoldStation = 35,
  ssKamikaze = 36,
  // duplicate ssKamikaze = 37,
  ssDisabled = 38,
  // duplicate ssDisabled = 39,
}

export enum CraftWhen {
  boarding = 1,
  boarded = 2,
  defence = 3,
  disabled = 4,
  specialCraft = 7,
  nonspecialCraft = 8,
  playersCraft = 9,
  nonplayersCraft = 10,
}

export enum Misc {
  rookieCraft = 0,
  noviceCraft = 1,
  officerCraft = 2,
  veteranCraft = 3,
  aceCraft = 4,
  topAceCraft = 5,
  stationaryCraft = 6,
  craftReturningToBase = 7,
  nonevadingCraft = 8,
  craftInFormation = 9,
  rendezvousingCraft = 10,
  disabledCraft = 11,
  craftAwaitingBoarding = 12,
  attackingCraft = 13,
  craftAtatckingEscorts = 14,
  protectingCraft = 15,
  escortingCraft = 16,
  disablingCraft = 17,
  deliveringCraft = 18,
  siezingCraft = 19,
  exchangingCraft = 20,
  capturingCraft = 21,
  craftDestroyingCargo = 22,
  pickedUpCraft = 23,
  droppedOffCraft = 24,
  waitingFighters = 25,
  waitingStarships = 26,
  patrollingStarships = 27,
  ssAwaitingReturns = 28,
  ssWaitingToLaunch = 29,
  ssWaitingToBeBoarded = 30,
  ssWitingForBoardingCraftToAppear = 31,
  ssAttacking = 32,
  ssDisabling = 33,
  // duplicate ssDisabling = 34,
  ssFlyingHome = 35,
  rebels = 36,
  imperials = 37,
  spacecraft = 39,
  weapons = 40,
  spaceObjects = 41,
  fighters = 46,
  transports = 47,
  freighters = 48,
  utilityCraft = 49,
  startships = 50,
  platforms = 51,
  mines = 54,
}

export enum EventType {
  pageBreak = 3,
  titleText = 4,
  captionText = 5,
  moveMap = 6,
  zoomMap = 7,
  clearFgTags = 8,
  fgTag1 = 9,
  fgTag2 = 10,
  fgTag3 = 11,
  fgTag4 = 12,
  fgTag5 = 13,
  fgTag6 = 14,
  fgTag7 = 15,
  fgTag8 = 16,
  clearTextTags = 17,
  textTag1 = 18,
  textTag2 = 19,
  textTag3 = 20,
  textTag4 = 21,
  textTag5 = 22,
  textTag6 = 23,
  textTag7 = 24,
  textTag8 = 25,
  endBriefing = 34,
}

export enum TextTagColor {
  green = 0,
  red = 1,
  purple = 2,
  blue = 3,
  // duplicate red = 4,
  lightRed = 5,
  gray = 6,
  white = 7,
}

export enum BriefingOfficers {
  bothOfficers = 1,
  flightOfficer = 2,
  secretOrder = 3,
}

export enum QuestionType {
  none = 0,
  primaryGoals = 1,
  secondaryGoals = 2,
}

export enum QuestionCondition {
  none = 0,
  successful = 4,
  failed = 5,
}

export enum MessageColor {
  red = 0,
  green = 1,
  blue = 2,
  purple = 3,
}

export enum IFFColor {
  green = 0,
  red = 1,
  purple = 2,
  blue = 3,
}

export enum PilotStatus {
  alive = 0,
  captured = 1,
  killed = 2,
}

export enum PilotRank {
  cadet = 0,
  officer = 1,
  lieutenant = 2,
  captain = 3,
  commander = 4,
  general = 5,
}

export enum PilotDifficulty {
  easy = 0,
  medium = 1,
  hard = 2,
}

export enum TrainingCraft {
  tieFighter = 0,
  tieInterceptor = 1,
  tieBomber = 2,
  tieAdvanced = 3,
  assaultGunboat = 4,
  tieDefender = 5,
  missileBoat = 6,
}

export enum TrainingCraftAbbr {
  tf = 0,
  ti = 1,
  tb = 2,
  ta = 3,
  gun = 4,
  td = 5,
  mis = 6,
}

export enum BattleStatus {
  none = 0,
  inProgress = 1,
  incomplete = 2,
  completed = 3,
}

export enum SecretOrder {
  none = 0,
  firstCircle = 1,
  secondCircle = 2,
  thirdCircle = 3,
  fourthCircle = 4,
  innerCircle = 5,
  emperorsHand = 6,
  emperorsEyes = 7,
  emperorsVoice = 8,
  emperorsReach = 9,
}
