/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Battle } from "./model/ehtc/battle";
import { BattleSummary, CharacterSummary, PilotSummary } from "./model/ehtc";
import { Mission } from "./model/TIE/mission";
import { BattleText, Delt, Header, LString, LText, OpCode, Rmap, Row, TIEBattle, Voic } from "./model/LFD";
import { Event, FileHeader, FlightGroup, GlobalGoal, GoalFG, Message, Mission as Mission1, Order, PilotFile, PostMissionQuestions, PreMissionQuestions, Tag, TIEString, Trigger, Waypt } from "./model/TIE";
import { MissionData, PilotFile as PilotFile1, TeamStats } from "./model/XvT";
import { FileHeader as FileHeader1, FlightGroup as FlightGroup1, Mission as Mission2, ObjectGroup, PilotFile as PilotFile2 } from "./model/XW";
import { MissionData as MissionData1, PilotFile as PilotFile3 } from "./model/XWA";
export namespace Components {
    interface EhtcBattle {
        "battle": Battle;
        "code": string;
    }
    interface EhtcBattleCenter {
    }
    interface EhtcBattleSelect {
        "battle": BattleSummary;
        "domain": string;
        "name": string;
        "search": (query: string) => Promise<void>;
        "value": string;
    }
    interface EhtcMemberSelect {
        "domain": string;
        "filter": string;
        "mode": "character" | "pilot";
        "name": string;
        "search": (query: string) => Promise<void>;
        "value": string;
    }
    interface EhtcPilot {
        "pin": number;
        "secondary": boolean;
    }
    interface PyriteFrown {
        "mission": Mission;
    }
    interface PyriteLfd {
        "file": string;
        "loadArrayBuffer": (value: ArrayBuffer) => Promise<void>;
    }
    interface PyriteLfdBattleText {
        "battletext": BattleText;
    }
    interface PyriteLfdDelt {
        "delt": Delt;
    }
    interface PyriteLfdHeader {
        "header": Header;
    }
    interface PyriteLfdLString {
        "lstring": LString;
    }
    interface PyriteLfdLText {
        "ltext": LText;
    }
    interface PyriteLfdOpCode {
        "opcode": OpCode;
    }
    interface PyriteLfdRmap {
        "rmap": Rmap;
    }
    interface PyriteLfdRow {
        "row": Row;
    }
    interface PyriteLfdTieBattle {
        "tiebattle": TIEBattle;
    }
    interface PyriteLfdVoic {
        "voic": Voic;
    }
    interface PyriteMission {
        "file": string;
        "name": string;
        "nr": string;
        "plt": string;
        "sub": string;
    }
    interface PyriteMissionTabs {
    }
    interface PyriteMissionWrapper {
        "file": string;
    }
    interface PyritePilotFile {
        "allowUpload": boolean;
        "bsf": string;
        "file": string;
        "useFileInput": (file: File) => Promise<void>;
    }
    interface PyriteResource {
        "name": string;
    }
    interface PyriteResources {
    }
    interface PyriteTieBriefing {
        "mission"?: Mission;
    }
    interface PyriteTieEvent {
        "event": Event;
    }
    interface PyriteTieFileHeader {
        "fileheader": FileHeader;
    }
    interface PyriteTieFlightGroup {
        "flightgroup": FlightGroup;
    }
    interface PyriteTieFlightgroup {
        "flightGroup": FlightGroup;
    }
    interface PyriteTieFlightgroups {
        "mission": Mission;
    }
    interface PyriteTieGlobalGoal {
        "globalgoal": GlobalGoal;
    }
    interface PyriteTieGoalFg {
        "goalfg": GoalFG;
    }
    interface PyriteTieMessage {
        "message": Message;
    }
    interface PyriteTieMessages {
        "mission": Mission;
    }
    interface PyriteTieMission {
        "file": string;
    }
    interface PyriteTieOrder {
        "order": Order;
    }
    interface PyriteTiePilotFile {
        "pilotfile": PilotFile;
    }
    interface PyriteTiePostMissionQuestions {
        "postmissionquestions": PostMissionQuestions;
    }
    interface PyriteTiePreMissionQuestions {
        "premissionquestions": PreMissionQuestions;
    }
    interface PyriteTieScore {
        "mission": Mission;
    }
    interface PyriteTieTag {
        "tag": Tag;
    }
    interface PyriteTieTieString {
        "tiestring": TIEString;
    }
    interface PyriteTieTrigger {
        "trigger": Trigger;
    }
    interface PyriteTieWaypt {
        "waypt": Waypt;
    }
    interface PyriteXvtMissionData {
        "missiondata": MissionData;
    }
    interface PyriteXvtPilotFile {
        "pilotfile": PilotFile;
    }
    interface PyriteXvtTeamStats {
        "teamstats": TeamStats;
    }
    interface PyriteXwFileHeader {
        "fileheader": FileHeader;
    }
    interface PyriteXwFlightGroup {
        "flightgroup": FlightGroup;
    }
    interface PyriteXwMission {
        "mission": Mission;
    }
    interface PyriteXwObjectGroup {
        "objectgroup": ObjectGroup;
    }
    interface PyriteXwPilotFile {
        "pilotfile": PilotFile;
    }
    interface PyriteXwaMissionData {
        "missiondata": MissionData;
    }
    interface PyriteXwaPilotFile {
        "pilotfile": PilotFile;
    }
}
declare global {
    interface HTMLEhtcBattleElement extends Components.EhtcBattle, HTMLStencilElement {
    }
    var HTMLEhtcBattleElement: {
        prototype: HTMLEhtcBattleElement;
        new (): HTMLEhtcBattleElement;
    };
    interface HTMLEhtcBattleCenterElement extends Components.EhtcBattleCenter, HTMLStencilElement {
    }
    var HTMLEhtcBattleCenterElement: {
        prototype: HTMLEhtcBattleCenterElement;
        new (): HTMLEhtcBattleCenterElement;
    };
    interface HTMLEhtcBattleSelectElement extends Components.EhtcBattleSelect, HTMLStencilElement {
    }
    var HTMLEhtcBattleSelectElement: {
        prototype: HTMLEhtcBattleSelectElement;
        new (): HTMLEhtcBattleSelectElement;
    };
    interface HTMLEhtcMemberSelectElement extends Components.EhtcMemberSelect, HTMLStencilElement {
    }
    var HTMLEhtcMemberSelectElement: {
        prototype: HTMLEhtcMemberSelectElement;
        new (): HTMLEhtcMemberSelectElement;
    };
    interface HTMLEhtcPilotElement extends Components.EhtcPilot, HTMLStencilElement {
    }
    var HTMLEhtcPilotElement: {
        prototype: HTMLEhtcPilotElement;
        new (): HTMLEhtcPilotElement;
    };
    interface HTMLPyriteFrownElement extends Components.PyriteFrown, HTMLStencilElement {
    }
    var HTMLPyriteFrownElement: {
        prototype: HTMLPyriteFrownElement;
        new (): HTMLPyriteFrownElement;
    };
    interface HTMLPyriteLfdElement extends Components.PyriteLfd, HTMLStencilElement {
    }
    var HTMLPyriteLfdElement: {
        prototype: HTMLPyriteLfdElement;
        new (): HTMLPyriteLfdElement;
    };
    interface HTMLPyriteLfdBattleTextElement extends Components.PyriteLfdBattleText, HTMLStencilElement {
    }
    var HTMLPyriteLfdBattleTextElement: {
        prototype: HTMLPyriteLfdBattleTextElement;
        new (): HTMLPyriteLfdBattleTextElement;
    };
    interface HTMLPyriteLfdDeltElement extends Components.PyriteLfdDelt, HTMLStencilElement {
    }
    var HTMLPyriteLfdDeltElement: {
        prototype: HTMLPyriteLfdDeltElement;
        new (): HTMLPyriteLfdDeltElement;
    };
    interface HTMLPyriteLfdHeaderElement extends Components.PyriteLfdHeader, HTMLStencilElement {
    }
    var HTMLPyriteLfdHeaderElement: {
        prototype: HTMLPyriteLfdHeaderElement;
        new (): HTMLPyriteLfdHeaderElement;
    };
    interface HTMLPyriteLfdLStringElement extends Components.PyriteLfdLString, HTMLStencilElement {
    }
    var HTMLPyriteLfdLStringElement: {
        prototype: HTMLPyriteLfdLStringElement;
        new (): HTMLPyriteLfdLStringElement;
    };
    interface HTMLPyriteLfdLTextElement extends Components.PyriteLfdLText, HTMLStencilElement {
    }
    var HTMLPyriteLfdLTextElement: {
        prototype: HTMLPyriteLfdLTextElement;
        new (): HTMLPyriteLfdLTextElement;
    };
    interface HTMLPyriteLfdOpCodeElement extends Components.PyriteLfdOpCode, HTMLStencilElement {
    }
    var HTMLPyriteLfdOpCodeElement: {
        prototype: HTMLPyriteLfdOpCodeElement;
        new (): HTMLPyriteLfdOpCodeElement;
    };
    interface HTMLPyriteLfdRmapElement extends Components.PyriteLfdRmap, HTMLStencilElement {
    }
    var HTMLPyriteLfdRmapElement: {
        prototype: HTMLPyriteLfdRmapElement;
        new (): HTMLPyriteLfdRmapElement;
    };
    interface HTMLPyriteLfdRowElement extends Components.PyriteLfdRow, HTMLStencilElement {
    }
    var HTMLPyriteLfdRowElement: {
        prototype: HTMLPyriteLfdRowElement;
        new (): HTMLPyriteLfdRowElement;
    };
    interface HTMLPyriteLfdTieBattleElement extends Components.PyriteLfdTieBattle, HTMLStencilElement {
    }
    var HTMLPyriteLfdTieBattleElement: {
        prototype: HTMLPyriteLfdTieBattleElement;
        new (): HTMLPyriteLfdTieBattleElement;
    };
    interface HTMLPyriteLfdVoicElement extends Components.PyriteLfdVoic, HTMLStencilElement {
    }
    var HTMLPyriteLfdVoicElement: {
        prototype: HTMLPyriteLfdVoicElement;
        new (): HTMLPyriteLfdVoicElement;
    };
    interface HTMLPyriteMissionElement extends Components.PyriteMission, HTMLStencilElement {
    }
    var HTMLPyriteMissionElement: {
        prototype: HTMLPyriteMissionElement;
        new (): HTMLPyriteMissionElement;
    };
    interface HTMLPyriteMissionTabsElement extends Components.PyriteMissionTabs, HTMLStencilElement {
    }
    var HTMLPyriteMissionTabsElement: {
        prototype: HTMLPyriteMissionTabsElement;
        new (): HTMLPyriteMissionTabsElement;
    };
    interface HTMLPyriteMissionWrapperElement extends Components.PyriteMissionWrapper, HTMLStencilElement {
    }
    var HTMLPyriteMissionWrapperElement: {
        prototype: HTMLPyriteMissionWrapperElement;
        new (): HTMLPyriteMissionWrapperElement;
    };
    interface HTMLPyritePilotFileElement extends Components.PyritePilotFile, HTMLStencilElement {
    }
    var HTMLPyritePilotFileElement: {
        prototype: HTMLPyritePilotFileElement;
        new (): HTMLPyritePilotFileElement;
    };
    interface HTMLPyriteResourceElement extends Components.PyriteResource, HTMLStencilElement {
    }
    var HTMLPyriteResourceElement: {
        prototype: HTMLPyriteResourceElement;
        new (): HTMLPyriteResourceElement;
    };
    interface HTMLPyriteResourcesElement extends Components.PyriteResources, HTMLStencilElement {
    }
    var HTMLPyriteResourcesElement: {
        prototype: HTMLPyriteResourcesElement;
        new (): HTMLPyriteResourcesElement;
    };
    interface HTMLPyriteTieBriefingElement extends Components.PyriteTieBriefing, HTMLStencilElement {
    }
    var HTMLPyriteTieBriefingElement: {
        prototype: HTMLPyriteTieBriefingElement;
        new (): HTMLPyriteTieBriefingElement;
    };
    interface HTMLPyriteTieEventElement extends Components.PyriteTieEvent, HTMLStencilElement {
    }
    var HTMLPyriteTieEventElement: {
        prototype: HTMLPyriteTieEventElement;
        new (): HTMLPyriteTieEventElement;
    };
    interface HTMLPyriteTieFileHeaderElement extends Components.PyriteTieFileHeader, HTMLStencilElement {
    }
    var HTMLPyriteTieFileHeaderElement: {
        prototype: HTMLPyriteTieFileHeaderElement;
        new (): HTMLPyriteTieFileHeaderElement;
    };
    interface HTMLPyriteTieFlightGroupElement extends Components.PyriteTieFlightGroup, HTMLStencilElement {
    }
    var HTMLPyriteTieFlightGroupElement: {
        prototype: HTMLPyriteTieFlightGroupElement;
        new (): HTMLPyriteTieFlightGroupElement;
    };
    interface HTMLPyriteTieFlightgroupElement extends Components.PyriteTieFlightgroup, HTMLStencilElement {
    }
    var HTMLPyriteTieFlightgroupElement: {
        prototype: HTMLPyriteTieFlightgroupElement;
        new (): HTMLPyriteTieFlightgroupElement;
    };
    interface HTMLPyriteTieFlightgroupsElement extends Components.PyriteTieFlightgroups, HTMLStencilElement {
    }
    var HTMLPyriteTieFlightgroupsElement: {
        prototype: HTMLPyriteTieFlightgroupsElement;
        new (): HTMLPyriteTieFlightgroupsElement;
    };
    interface HTMLPyriteTieGlobalGoalElement extends Components.PyriteTieGlobalGoal, HTMLStencilElement {
    }
    var HTMLPyriteTieGlobalGoalElement: {
        prototype: HTMLPyriteTieGlobalGoalElement;
        new (): HTMLPyriteTieGlobalGoalElement;
    };
    interface HTMLPyriteTieGoalFgElement extends Components.PyriteTieGoalFg, HTMLStencilElement {
    }
    var HTMLPyriteTieGoalFgElement: {
        prototype: HTMLPyriteTieGoalFgElement;
        new (): HTMLPyriteTieGoalFgElement;
    };
    interface HTMLPyriteTieMessageElement extends Components.PyriteTieMessage, HTMLStencilElement {
    }
    var HTMLPyriteTieMessageElement: {
        prototype: HTMLPyriteTieMessageElement;
        new (): HTMLPyriteTieMessageElement;
    };
    interface HTMLPyriteTieMessagesElement extends Components.PyriteTieMessages, HTMLStencilElement {
    }
    var HTMLPyriteTieMessagesElement: {
        prototype: HTMLPyriteTieMessagesElement;
        new (): HTMLPyriteTieMessagesElement;
    };
    interface HTMLPyriteTieMissionElement extends Components.PyriteTieMission, HTMLStencilElement {
    }
    var HTMLPyriteTieMissionElement: {
        prototype: HTMLPyriteTieMissionElement;
        new (): HTMLPyriteTieMissionElement;
    };
    interface HTMLPyriteTieOrderElement extends Components.PyriteTieOrder, HTMLStencilElement {
    }
    var HTMLPyriteTieOrderElement: {
        prototype: HTMLPyriteTieOrderElement;
        new (): HTMLPyriteTieOrderElement;
    };
    interface HTMLPyriteTiePilotFileElement extends Components.PyriteTiePilotFile, HTMLStencilElement {
    }
    var HTMLPyriteTiePilotFileElement: {
        prototype: HTMLPyriteTiePilotFileElement;
        new (): HTMLPyriteTiePilotFileElement;
    };
    interface HTMLPyriteTiePostMissionQuestionsElement extends Components.PyriteTiePostMissionQuestions, HTMLStencilElement {
    }
    var HTMLPyriteTiePostMissionQuestionsElement: {
        prototype: HTMLPyriteTiePostMissionQuestionsElement;
        new (): HTMLPyriteTiePostMissionQuestionsElement;
    };
    interface HTMLPyriteTiePreMissionQuestionsElement extends Components.PyriteTiePreMissionQuestions, HTMLStencilElement {
    }
    var HTMLPyriteTiePreMissionQuestionsElement: {
        prototype: HTMLPyriteTiePreMissionQuestionsElement;
        new (): HTMLPyriteTiePreMissionQuestionsElement;
    };
    interface HTMLPyriteTieScoreElement extends Components.PyriteTieScore, HTMLStencilElement {
    }
    var HTMLPyriteTieScoreElement: {
        prototype: HTMLPyriteTieScoreElement;
        new (): HTMLPyriteTieScoreElement;
    };
    interface HTMLPyriteTieTagElement extends Components.PyriteTieTag, HTMLStencilElement {
    }
    var HTMLPyriteTieTagElement: {
        prototype: HTMLPyriteTieTagElement;
        new (): HTMLPyriteTieTagElement;
    };
    interface HTMLPyriteTieTieStringElement extends Components.PyriteTieTieString, HTMLStencilElement {
    }
    var HTMLPyriteTieTieStringElement: {
        prototype: HTMLPyriteTieTieStringElement;
        new (): HTMLPyriteTieTieStringElement;
    };
    interface HTMLPyriteTieTriggerElement extends Components.PyriteTieTrigger, HTMLStencilElement {
    }
    var HTMLPyriteTieTriggerElement: {
        prototype: HTMLPyriteTieTriggerElement;
        new (): HTMLPyriteTieTriggerElement;
    };
    interface HTMLPyriteTieWayptElement extends Components.PyriteTieWaypt, HTMLStencilElement {
    }
    var HTMLPyriteTieWayptElement: {
        prototype: HTMLPyriteTieWayptElement;
        new (): HTMLPyriteTieWayptElement;
    };
    interface HTMLPyriteXvtMissionDataElement extends Components.PyriteXvtMissionData, HTMLStencilElement {
    }
    var HTMLPyriteXvtMissionDataElement: {
        prototype: HTMLPyriteXvtMissionDataElement;
        new (): HTMLPyriteXvtMissionDataElement;
    };
    interface HTMLPyriteXvtPilotFileElement extends Components.PyriteXvtPilotFile, HTMLStencilElement {
    }
    var HTMLPyriteXvtPilotFileElement: {
        prototype: HTMLPyriteXvtPilotFileElement;
        new (): HTMLPyriteXvtPilotFileElement;
    };
    interface HTMLPyriteXvtTeamStatsElement extends Components.PyriteXvtTeamStats, HTMLStencilElement {
    }
    var HTMLPyriteXvtTeamStatsElement: {
        prototype: HTMLPyriteXvtTeamStatsElement;
        new (): HTMLPyriteXvtTeamStatsElement;
    };
    interface HTMLPyriteXwFileHeaderElement extends Components.PyriteXwFileHeader, HTMLStencilElement {
    }
    var HTMLPyriteXwFileHeaderElement: {
        prototype: HTMLPyriteXwFileHeaderElement;
        new (): HTMLPyriteXwFileHeaderElement;
    };
    interface HTMLPyriteXwFlightGroupElement extends Components.PyriteXwFlightGroup, HTMLStencilElement {
    }
    var HTMLPyriteXwFlightGroupElement: {
        prototype: HTMLPyriteXwFlightGroupElement;
        new (): HTMLPyriteXwFlightGroupElement;
    };
    interface HTMLPyriteXwMissionElement extends Components.PyriteXwMission, HTMLStencilElement {
    }
    var HTMLPyriteXwMissionElement: {
        prototype: HTMLPyriteXwMissionElement;
        new (): HTMLPyriteXwMissionElement;
    };
    interface HTMLPyriteXwObjectGroupElement extends Components.PyriteXwObjectGroup, HTMLStencilElement {
    }
    var HTMLPyriteXwObjectGroupElement: {
        prototype: HTMLPyriteXwObjectGroupElement;
        new (): HTMLPyriteXwObjectGroupElement;
    };
    interface HTMLPyriteXwPilotFileElement extends Components.PyriteXwPilotFile, HTMLStencilElement {
    }
    var HTMLPyriteXwPilotFileElement: {
        prototype: HTMLPyriteXwPilotFileElement;
        new (): HTMLPyriteXwPilotFileElement;
    };
    interface HTMLPyriteXwaMissionDataElement extends Components.PyriteXwaMissionData, HTMLStencilElement {
    }
    var HTMLPyriteXwaMissionDataElement: {
        prototype: HTMLPyriteXwaMissionDataElement;
        new (): HTMLPyriteXwaMissionDataElement;
    };
    interface HTMLPyriteXwaPilotFileElement extends Components.PyriteXwaPilotFile, HTMLStencilElement {
    }
    var HTMLPyriteXwaPilotFileElement: {
        prototype: HTMLPyriteXwaPilotFileElement;
        new (): HTMLPyriteXwaPilotFileElement;
    };
    interface HTMLElementTagNameMap {
        "ehtc-battle": HTMLEhtcBattleElement;
        "ehtc-battle-center": HTMLEhtcBattleCenterElement;
        "ehtc-battle-select": HTMLEhtcBattleSelectElement;
        "ehtc-member-select": HTMLEhtcMemberSelectElement;
        "ehtc-pilot": HTMLEhtcPilotElement;
        "pyrite-frown": HTMLPyriteFrownElement;
        "pyrite-lfd": HTMLPyriteLfdElement;
        "pyrite-lfd-battle-text": HTMLPyriteLfdBattleTextElement;
        "pyrite-lfd-delt": HTMLPyriteLfdDeltElement;
        "pyrite-lfd-header": HTMLPyriteLfdHeaderElement;
        "pyrite-lfd-l-string": HTMLPyriteLfdLStringElement;
        "pyrite-lfd-l-text": HTMLPyriteLfdLTextElement;
        "pyrite-lfd-op-code": HTMLPyriteLfdOpCodeElement;
        "pyrite-lfd-rmap": HTMLPyriteLfdRmapElement;
        "pyrite-lfd-row": HTMLPyriteLfdRowElement;
        "pyrite-lfd-tie-battle": HTMLPyriteLfdTieBattleElement;
        "pyrite-lfd-voic": HTMLPyriteLfdVoicElement;
        "pyrite-mission": HTMLPyriteMissionElement;
        "pyrite-mission-tabs": HTMLPyriteMissionTabsElement;
        "pyrite-mission-wrapper": HTMLPyriteMissionWrapperElement;
        "pyrite-pilot-file": HTMLPyritePilotFileElement;
        "pyrite-resource": HTMLPyriteResourceElement;
        "pyrite-resources": HTMLPyriteResourcesElement;
        "pyrite-tie-briefing": HTMLPyriteTieBriefingElement;
        "pyrite-tie-event": HTMLPyriteTieEventElement;
        "pyrite-tie-file-header": HTMLPyriteTieFileHeaderElement;
        "pyrite-tie-flight-group": HTMLPyriteTieFlightGroupElement;
        "pyrite-tie-flightgroup": HTMLPyriteTieFlightgroupElement;
        "pyrite-tie-flightgroups": HTMLPyriteTieFlightgroupsElement;
        "pyrite-tie-global-goal": HTMLPyriteTieGlobalGoalElement;
        "pyrite-tie-goal-fg": HTMLPyriteTieGoalFgElement;
        "pyrite-tie-message": HTMLPyriteTieMessageElement;
        "pyrite-tie-messages": HTMLPyriteTieMessagesElement;
        "pyrite-tie-mission": HTMLPyriteTieMissionElement;
        "pyrite-tie-order": HTMLPyriteTieOrderElement;
        "pyrite-tie-pilot-file": HTMLPyriteTiePilotFileElement;
        "pyrite-tie-post-mission-questions": HTMLPyriteTiePostMissionQuestionsElement;
        "pyrite-tie-pre-mission-questions": HTMLPyriteTiePreMissionQuestionsElement;
        "pyrite-tie-score": HTMLPyriteTieScoreElement;
        "pyrite-tie-tag": HTMLPyriteTieTagElement;
        "pyrite-tie-tie-string": HTMLPyriteTieTieStringElement;
        "pyrite-tie-trigger": HTMLPyriteTieTriggerElement;
        "pyrite-tie-waypt": HTMLPyriteTieWayptElement;
        "pyrite-xvt-mission-data": HTMLPyriteXvtMissionDataElement;
        "pyrite-xvt-pilot-file": HTMLPyriteXvtPilotFileElement;
        "pyrite-xvt-team-stats": HTMLPyriteXvtTeamStatsElement;
        "pyrite-xw-file-header": HTMLPyriteXwFileHeaderElement;
        "pyrite-xw-flight-group": HTMLPyriteXwFlightGroupElement;
        "pyrite-xw-mission": HTMLPyriteXwMissionElement;
        "pyrite-xw-object-group": HTMLPyriteXwObjectGroupElement;
        "pyrite-xw-pilot-file": HTMLPyriteXwPilotFileElement;
        "pyrite-xwa-mission-data": HTMLPyriteXwaMissionDataElement;
        "pyrite-xwa-pilot-file": HTMLPyriteXwaPilotFileElement;
    }
}
declare namespace LocalJSX {
    interface EhtcBattle {
        "battle"?: Battle;
        "code"?: string;
        "onDownloadBattle"?: (event: CustomEvent<Battle>) => void;
    }
    interface EhtcBattleCenter {
    }
    interface EhtcBattleSelect {
        "battle"?: BattleSummary;
        "domain"?: string;
        "name"?: string;
        "onBattleSelect"?: (event: CustomEvent<BattleSummary>) => void;
        "value"?: string;
    }
    interface EhtcMemberSelect {
        "domain"?: string;
        "filter"?: string;
        "mode"?: "character" | "pilot";
        "name"?: string;
        "onMemberSelect"?: (event: CustomEvent<PilotSummary | CharacterSummary>) => void;
        "value"?: string;
    }
    interface EhtcPilot {
        "pin"?: number;
        "secondary"?: boolean;
    }
    interface PyriteFrown {
        "mission"?: Mission;
    }
    interface PyriteLfd {
        "file"?: string;
    }
    interface PyriteLfdBattleText {
        "battletext"?: BattleText;
    }
    interface PyriteLfdDelt {
        "delt"?: Delt;
    }
    interface PyriteLfdHeader {
        "header"?: Header;
    }
    interface PyriteLfdLString {
        "lstring"?: LString;
    }
    interface PyriteLfdLText {
        "ltext"?: LText;
    }
    interface PyriteLfdOpCode {
        "opcode"?: OpCode;
    }
    interface PyriteLfdRmap {
        "rmap"?: Rmap;
    }
    interface PyriteLfdRow {
        "row"?: Row;
    }
    interface PyriteLfdTieBattle {
        "tiebattle"?: TIEBattle;
    }
    interface PyriteLfdVoic {
        "voic"?: Voic;
    }
    interface PyriteMission {
        "file"?: string;
        "name"?: string;
        "nr"?: string;
        "plt"?: string;
        "sub"?: string;
    }
    interface PyriteMissionTabs {
    }
    interface PyriteMissionWrapper {
        "file"?: string;
    }
    interface PyritePilotFile {
        "allowUpload"?: boolean;
        "bsf"?: string;
        "file"?: string;
    }
    interface PyriteResource {
        "name"?: string;
    }
    interface PyriteResources {
    }
    interface PyriteTieBriefing {
        "mission"?: Mission;
    }
    interface PyriteTieEvent {
        "event"?: Event;
    }
    interface PyriteTieFileHeader {
        "fileheader"?: FileHeader;
    }
    interface PyriteTieFlightGroup {
        "flightgroup"?: FlightGroup;
    }
    interface PyriteTieFlightgroup {
        "flightGroup"?: FlightGroup;
    }
    interface PyriteTieFlightgroups {
        "mission"?: Mission;
    }
    interface PyriteTieGlobalGoal {
        "globalgoal"?: GlobalGoal;
    }
    interface PyriteTieGoalFg {
        "goalfg"?: GoalFG;
    }
    interface PyriteTieMessage {
        "message"?: Message;
    }
    interface PyriteTieMessages {
        "mission"?: Mission;
    }
    interface PyriteTieMission {
        "file"?: string;
    }
    interface PyriteTieOrder {
        "order"?: Order;
    }
    interface PyriteTiePilotFile {
        "pilotfile"?: PilotFile;
    }
    interface PyriteTiePostMissionQuestions {
        "postmissionquestions"?: PostMissionQuestions;
    }
    interface PyriteTiePreMissionQuestions {
        "premissionquestions"?: PreMissionQuestions;
    }
    interface PyriteTieScore {
        "mission"?: Mission;
    }
    interface PyriteTieTag {
        "tag"?: Tag;
    }
    interface PyriteTieTieString {
        "tiestring"?: TIEString;
    }
    interface PyriteTieTrigger {
        "trigger"?: Trigger;
    }
    interface PyriteTieWaypt {
        "waypt"?: Waypt;
    }
    interface PyriteXvtMissionData {
        "missiondata"?: MissionData;
    }
    interface PyriteXvtPilotFile {
        "pilotfile"?: PilotFile;
    }
    interface PyriteXvtTeamStats {
        "teamstats"?: TeamStats;
    }
    interface PyriteXwFileHeader {
        "fileheader"?: FileHeader;
    }
    interface PyriteXwFlightGroup {
        "flightgroup"?: FlightGroup;
    }
    interface PyriteXwMission {
        "mission"?: Mission;
    }
    interface PyriteXwObjectGroup {
        "objectgroup"?: ObjectGroup;
    }
    interface PyriteXwPilotFile {
        "pilotfile"?: PilotFile;
    }
    interface PyriteXwaMissionData {
        "missiondata"?: MissionData;
    }
    interface PyriteXwaPilotFile {
        "pilotfile"?: PilotFile;
    }
    interface IntrinsicElements {
        "ehtc-battle": EhtcBattle;
        "ehtc-battle-center": EhtcBattleCenter;
        "ehtc-battle-select": EhtcBattleSelect;
        "ehtc-member-select": EhtcMemberSelect;
        "ehtc-pilot": EhtcPilot;
        "pyrite-frown": PyriteFrown;
        "pyrite-lfd": PyriteLfd;
        "pyrite-lfd-battle-text": PyriteLfdBattleText;
        "pyrite-lfd-delt": PyriteLfdDelt;
        "pyrite-lfd-header": PyriteLfdHeader;
        "pyrite-lfd-l-string": PyriteLfdLString;
        "pyrite-lfd-l-text": PyriteLfdLText;
        "pyrite-lfd-op-code": PyriteLfdOpCode;
        "pyrite-lfd-rmap": PyriteLfdRmap;
        "pyrite-lfd-row": PyriteLfdRow;
        "pyrite-lfd-tie-battle": PyriteLfdTieBattle;
        "pyrite-lfd-voic": PyriteLfdVoic;
        "pyrite-mission": PyriteMission;
        "pyrite-mission-tabs": PyriteMissionTabs;
        "pyrite-mission-wrapper": PyriteMissionWrapper;
        "pyrite-pilot-file": PyritePilotFile;
        "pyrite-resource": PyriteResource;
        "pyrite-resources": PyriteResources;
        "pyrite-tie-briefing": PyriteTieBriefing;
        "pyrite-tie-event": PyriteTieEvent;
        "pyrite-tie-file-header": PyriteTieFileHeader;
        "pyrite-tie-flight-group": PyriteTieFlightGroup;
        "pyrite-tie-flightgroup": PyriteTieFlightgroup;
        "pyrite-tie-flightgroups": PyriteTieFlightgroups;
        "pyrite-tie-global-goal": PyriteTieGlobalGoal;
        "pyrite-tie-goal-fg": PyriteTieGoalFg;
        "pyrite-tie-message": PyriteTieMessage;
        "pyrite-tie-messages": PyriteTieMessages;
        "pyrite-tie-mission": PyriteTieMission;
        "pyrite-tie-order": PyriteTieOrder;
        "pyrite-tie-pilot-file": PyriteTiePilotFile;
        "pyrite-tie-post-mission-questions": PyriteTiePostMissionQuestions;
        "pyrite-tie-pre-mission-questions": PyriteTiePreMissionQuestions;
        "pyrite-tie-score": PyriteTieScore;
        "pyrite-tie-tag": PyriteTieTag;
        "pyrite-tie-tie-string": PyriteTieTieString;
        "pyrite-tie-trigger": PyriteTieTrigger;
        "pyrite-tie-waypt": PyriteTieWaypt;
        "pyrite-xvt-mission-data": PyriteXvtMissionData;
        "pyrite-xvt-pilot-file": PyriteXvtPilotFile;
        "pyrite-xvt-team-stats": PyriteXvtTeamStats;
        "pyrite-xw-file-header": PyriteXwFileHeader;
        "pyrite-xw-flight-group": PyriteXwFlightGroup;
        "pyrite-xw-mission": PyriteXwMission;
        "pyrite-xw-object-group": PyriteXwObjectGroup;
        "pyrite-xw-pilot-file": PyriteXwPilotFile;
        "pyrite-xwa-mission-data": PyriteXwaMissionData;
        "pyrite-xwa-pilot-file": PyriteXwaPilotFile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ehtc-battle": LocalJSX.EhtcBattle & JSXBase.HTMLAttributes<HTMLEhtcBattleElement>;
            "ehtc-battle-center": LocalJSX.EhtcBattleCenter & JSXBase.HTMLAttributes<HTMLEhtcBattleCenterElement>;
            "ehtc-battle-select": LocalJSX.EhtcBattleSelect & JSXBase.HTMLAttributes<HTMLEhtcBattleSelectElement>;
            "ehtc-member-select": LocalJSX.EhtcMemberSelect & JSXBase.HTMLAttributes<HTMLEhtcMemberSelectElement>;
            "ehtc-pilot": LocalJSX.EhtcPilot & JSXBase.HTMLAttributes<HTMLEhtcPilotElement>;
            "pyrite-frown": LocalJSX.PyriteFrown & JSXBase.HTMLAttributes<HTMLPyriteFrownElement>;
            "pyrite-lfd": LocalJSX.PyriteLfd & JSXBase.HTMLAttributes<HTMLPyriteLfdElement>;
            "pyrite-lfd-battle-text": LocalJSX.PyriteLfdBattleText & JSXBase.HTMLAttributes<HTMLPyriteLfdBattleTextElement>;
            "pyrite-lfd-delt": LocalJSX.PyriteLfdDelt & JSXBase.HTMLAttributes<HTMLPyriteLfdDeltElement>;
            "pyrite-lfd-header": LocalJSX.PyriteLfdHeader & JSXBase.HTMLAttributes<HTMLPyriteLfdHeaderElement>;
            "pyrite-lfd-l-string": LocalJSX.PyriteLfdLString & JSXBase.HTMLAttributes<HTMLPyriteLfdLStringElement>;
            "pyrite-lfd-l-text": LocalJSX.PyriteLfdLText & JSXBase.HTMLAttributes<HTMLPyriteLfdLTextElement>;
            "pyrite-lfd-op-code": LocalJSX.PyriteLfdOpCode & JSXBase.HTMLAttributes<HTMLPyriteLfdOpCodeElement>;
            "pyrite-lfd-rmap": LocalJSX.PyriteLfdRmap & JSXBase.HTMLAttributes<HTMLPyriteLfdRmapElement>;
            "pyrite-lfd-row": LocalJSX.PyriteLfdRow & JSXBase.HTMLAttributes<HTMLPyriteLfdRowElement>;
            "pyrite-lfd-tie-battle": LocalJSX.PyriteLfdTieBattle & JSXBase.HTMLAttributes<HTMLPyriteLfdTieBattleElement>;
            "pyrite-lfd-voic": LocalJSX.PyriteLfdVoic & JSXBase.HTMLAttributes<HTMLPyriteLfdVoicElement>;
            "pyrite-mission": LocalJSX.PyriteMission & JSXBase.HTMLAttributes<HTMLPyriteMissionElement>;
            "pyrite-mission-tabs": LocalJSX.PyriteMissionTabs & JSXBase.HTMLAttributes<HTMLPyriteMissionTabsElement>;
            "pyrite-mission-wrapper": LocalJSX.PyriteMissionWrapper & JSXBase.HTMLAttributes<HTMLPyriteMissionWrapperElement>;
            "pyrite-pilot-file": LocalJSX.PyritePilotFile & JSXBase.HTMLAttributes<HTMLPyritePilotFileElement>;
            "pyrite-resource": LocalJSX.PyriteResource & JSXBase.HTMLAttributes<HTMLPyriteResourceElement>;
            "pyrite-resources": LocalJSX.PyriteResources & JSXBase.HTMLAttributes<HTMLPyriteResourcesElement>;
            "pyrite-tie-briefing": LocalJSX.PyriteTieBriefing & JSXBase.HTMLAttributes<HTMLPyriteTieBriefingElement>;
            "pyrite-tie-event": LocalJSX.PyriteTieEvent & JSXBase.HTMLAttributes<HTMLPyriteTieEventElement>;
            "pyrite-tie-file-header": LocalJSX.PyriteTieFileHeader & JSXBase.HTMLAttributes<HTMLPyriteTieFileHeaderElement>;
            "pyrite-tie-flight-group": LocalJSX.PyriteTieFlightGroup & JSXBase.HTMLAttributes<HTMLPyriteTieFlightGroupElement>;
            "pyrite-tie-flightgroup": LocalJSX.PyriteTieFlightgroup & JSXBase.HTMLAttributes<HTMLPyriteTieFlightgroupElement>;
            "pyrite-tie-flightgroups": LocalJSX.PyriteTieFlightgroups & JSXBase.HTMLAttributes<HTMLPyriteTieFlightgroupsElement>;
            "pyrite-tie-global-goal": LocalJSX.PyriteTieGlobalGoal & JSXBase.HTMLAttributes<HTMLPyriteTieGlobalGoalElement>;
            "pyrite-tie-goal-fg": LocalJSX.PyriteTieGoalFg & JSXBase.HTMLAttributes<HTMLPyriteTieGoalFgElement>;
            "pyrite-tie-message": LocalJSX.PyriteTieMessage & JSXBase.HTMLAttributes<HTMLPyriteTieMessageElement>;
            "pyrite-tie-messages": LocalJSX.PyriteTieMessages & JSXBase.HTMLAttributes<HTMLPyriteTieMessagesElement>;
            "pyrite-tie-mission": LocalJSX.PyriteTieMission & JSXBase.HTMLAttributes<HTMLPyriteTieMissionElement>;
            "pyrite-tie-order": LocalJSX.PyriteTieOrder & JSXBase.HTMLAttributes<HTMLPyriteTieOrderElement>;
            "pyrite-tie-pilot-file": LocalJSX.PyriteTiePilotFile & JSXBase.HTMLAttributes<HTMLPyriteTiePilotFileElement>;
            "pyrite-tie-post-mission-questions": LocalJSX.PyriteTiePostMissionQuestions & JSXBase.HTMLAttributes<HTMLPyriteTiePostMissionQuestionsElement>;
            "pyrite-tie-pre-mission-questions": LocalJSX.PyriteTiePreMissionQuestions & JSXBase.HTMLAttributes<HTMLPyriteTiePreMissionQuestionsElement>;
            "pyrite-tie-score": LocalJSX.PyriteTieScore & JSXBase.HTMLAttributes<HTMLPyriteTieScoreElement>;
            "pyrite-tie-tag": LocalJSX.PyriteTieTag & JSXBase.HTMLAttributes<HTMLPyriteTieTagElement>;
            "pyrite-tie-tie-string": LocalJSX.PyriteTieTieString & JSXBase.HTMLAttributes<HTMLPyriteTieTieStringElement>;
            "pyrite-tie-trigger": LocalJSX.PyriteTieTrigger & JSXBase.HTMLAttributes<HTMLPyriteTieTriggerElement>;
            "pyrite-tie-waypt": LocalJSX.PyriteTieWaypt & JSXBase.HTMLAttributes<HTMLPyriteTieWayptElement>;
            "pyrite-xvt-mission-data": LocalJSX.PyriteXvtMissionData & JSXBase.HTMLAttributes<HTMLPyriteXvtMissionDataElement>;
            "pyrite-xvt-pilot-file": LocalJSX.PyriteXvtPilotFile & JSXBase.HTMLAttributes<HTMLPyriteXvtPilotFileElement>;
            "pyrite-xvt-team-stats": LocalJSX.PyriteXvtTeamStats & JSXBase.HTMLAttributes<HTMLPyriteXvtTeamStatsElement>;
            "pyrite-xw-file-header": LocalJSX.PyriteXwFileHeader & JSXBase.HTMLAttributes<HTMLPyriteXwFileHeaderElement>;
            "pyrite-xw-flight-group": LocalJSX.PyriteXwFlightGroup & JSXBase.HTMLAttributes<HTMLPyriteXwFlightGroupElement>;
            "pyrite-xw-mission": LocalJSX.PyriteXwMission & JSXBase.HTMLAttributes<HTMLPyriteXwMissionElement>;
            "pyrite-xw-object-group": LocalJSX.PyriteXwObjectGroup & JSXBase.HTMLAttributes<HTMLPyriteXwObjectGroupElement>;
            "pyrite-xw-pilot-file": LocalJSX.PyriteXwPilotFile & JSXBase.HTMLAttributes<HTMLPyriteXwPilotFileElement>;
            "pyrite-xwa-mission-data": LocalJSX.PyriteXwaMissionData & JSXBase.HTMLAttributes<HTMLPyriteXwaMissionDataElement>;
            "pyrite-xwa-pilot-file": LocalJSX.PyriteXwaPilotFile & JSXBase.HTMLAttributes<HTMLPyriteXwaPilotFileElement>;
        }
    }
}
