export class Constants {
  public static CRAFTTYPE = {
    1: "X-wing",
    2: "Y-wing",
    3: "A-wing",
    4: "B-wing",
    5: "TIE Fighter",
    6: "TIE Interceptor",
    7: "TIE Bomber",
    8: "TIE Advanced",
    9: "TIE Defender",
    10: "IRD Fighter",
    11: "Toscan Fighter",
    12: "Missile Boat",
    13: "T-wing",
    14: "Z-95 Headhunter",
    15: "R-41 Starchaser",
    16: "Assault Gunboat",
    17: "Shuttle",
    18: "Escort Shuttle",
    19: "System Patrol Craft",
    20: "*Scout Craft",
    21: "Stormtrooper Transport",
    22: "Assault Transport",
    23: "Escort Transport",
    24: "Tug",
    25: "Combat Utility Vehicle",
    26: "Container A",
    27: "Container B",
    28: "Container C",
    29: "Container D",
    30: "Heavy Lifter",
    31: "Mole Miner",
    32: "Bulk Freighter",
    33: "Cargo Ferry",
    34: "Modular Conveyor",
    35: "*Container Transport",
    36: "Medium Transport",
    37: "Murrian Transport",
    38: "Corellian Transport",
    39: "Millenium Falcon",
    40: "Corellian Corvette",
    41: "Modified Corvette",
    42: "Nebulon-B Frigate",
    43: "Modified Frigate",
    44: "*C-3 Passenger Liner",
    45: "*Carrack Cruiser",
    46: "Strike Cruiser",
    47: "Escort Carrier",
    48: "Dreadnaught",
    49: "MC80a Cruiser",
    50: "MC40a Light Cruiser",
    51: "Interdictor Cruiser",
    52: "Victory-class Star Destroyer",
    53: "Imperator-class Star Destroyer",
    54: "Executor-class Star Destroyer",
    55: "Container E",
    56: "Container F",
    57: "Container G",
    58: "Container H",
    59: "Container I",
    60: "Platform A",
    61: "Platform B",
    62: "Platform C",
    63: "Platform D",
    64: "Platform E",
    65: "Platform F",
    66: "Asteroid R&D Station",
    67: "Asteroid Laser Battery",
    68: "Asteroid Warhead Battery",
    69: "X/7 Factory",
    70: "Satellite 1",
    71: "Satellite 2",
    72: "Satellite 3",
    73: "*Satellite 4",
    74: "*Satellite 5",
    75: "Mine A",
    76: "Mine B",
    77: "Mine C",
    78: "Gun Emplacement",
    79: "*Mine 5",
    80: "Probe A",
    81: "Probe B",
    82: "*Probe 3",
    83: "Nav Buoy A",
    84: "Nav Buoy B",
    85: "Hyper Buoy",
    86: "Asteroid Field",
    87: "Planet",
    88: "Rendezvous Buoy",
    89: "Cargo Canister",
    90: "Shipyard",
    91: "Repair Yard",
    92: "*Modified Strike Cruiser",
    93: "Lancer Frigate",
    94: "Bulk Cruiser",
    95: "Assault Frigate",
    96: "Corellian Gunship",
    97: "Imperial Landing Craft",
    98: "Assault Shuttle",
    99: "Marauder Corvette",
    100: "Star Galleon",
    101: "Imperial Research Ship",
    102: "Luxury Yacht 3000",
    103: "Ferryboat Liner",
    104: "Modified Action Transport",
    105: "Mobquet Transport",
    106: "Xiytiar Transport",
    107: "Freight Transport/C",
    108: "Freight Transport/H",
    109: "Freight Transport/K",
    110: "YT-2000",
    111: "YT-2400",
    112: "Suprosa",
    113: "Skipray Blastboat",
    114: "T/e m1",
    115: "T/e m2",
    116: "T/e m3",
    117: "T/e m4",
    118: "T/e m5",
    119: "Cloakshape Fighter",
    120: "Razor Fighter",
    121: "Planetary Fighter",
    122: "Supa Fighter",
    123: "Pinook Fighter",
    124: "*Booster Pack",
    125: "Preybird Fighter",
    126: "*StarViper",
    127: "Firespray",
    128: "Pursuer",
    129: "Golan 1",
    130: "Golan 2",
    131: "Golan 3",
    132: "Derilyn Platform",
    133: "Sensor Array",
    134: "Comm Relay",
    135: "Space Colony 1",
    136: "Space Colony 2",
    137: "Space Colony 3",
    138: "Casino",
    139: "Cargo Facility 1",
    140: "Cargo Facility 2",
    141: "Asteroid Mining Plant",
    142: "Processing Plant",
    143: "Rebel Platform",
    144: "Imperial Research Center",
    145: "Family Base",
    146: "Family Repair Yard",
    147: "Pirate Shipyard",
    148: "Industrical Complex",
    149: "*Pirate Junkyard Base",
    150: "Escape Pod 1",
    151: "Pressure Tank",
    152: "Container J",
    153: "Container K",
    154: "Container L",
    155: "Container Hangar",
    156: "Large Gun Emplacement",
    157: "Large Gun/Warhead Emplacement",
    158: "Proximity Mine A",
    159: "Proximity Mine B",
    160: "*Homing Mine A",
    161: "Homing Mine B",
    162: "New Laser Battery",
    163: "New Ion Battery",
    164: "Cargo Freighter",
    165: "*Cargo Freighter 2",
    166: "*Cargo Freighter 3",
    167: "*Cargo Freighter 4",
    168: "*Cargo Freighter 5",
    169: "Cargo Tanker",
    170: "*Cargo Tanker 2",
    171: "*Cargo Tanker 3",
    172: "*Cargo Tanker 4",
    173: "*Cargo Tanker 5",
    174: "Escape Pod 2",
    175: "*Rebel Pilot",
    176: "*Imperial Pilot",
    177: "*Civilian Pilot",
    178: "Spacetrooper",
    179: "Zero-G Utility Suit",
    180: "Emkay",
    181: "Astromech",
    182: "Worker droid",
    183: "Backdrop",
    184: "*Forest Moon of Endor",
    185: "*Endor",
    186: "*Sullust",
    187: "*Bothuwai",
    188: "*Kothlis",
    189: "*Hoth",
    190: "*DeathStar II backdrop",
    191: "*Nar Shadda",
    192: "*Planet",
    197: "*Planet",
    198: "*Moon",
    202: "*Moon",
    203: "*Sun",
    212: "*Sun",
    213: "*Backdrop",
    226: "*Backdrop",
    227: "Death Star II",
    228: "MC80 Liberty-class Cruiser",
    229: "Victory-class Star Destroyer II",
    230: "Imperator-class Star Destroyer II",
    231: "*Planet",
  };

  public static CRAFTABBR = {
    1: "X-W",
    2: "Y-W",
    3: "A-W",
    4: "B-W",
    5: "T/F",
    6: "T/I",
    7: "T/B",
    8: "T/A",
    9: "T/D",
    10: "IRD",
    11: "TOS",
    12: "MIS",
    13: "T-W",
    14: "Z-95",
    15: "R-41",
    16: "GUN",
    17: "SHU",
    18: "E/S",
    19: "SPC",
    20: "SCT",
    21: "TRN",
    22: "ATR",
    23: "ETR",
    24: "TUG",
    25: "CUV",
    26: "CN/A",
    27: "CN/B",
    28: "CN/C",
    29: "CN/D",
    30: "HLF",
    31: "Mole Miner",
    32: "FRT",
    33: "CARG",
    34: "CNVYR",
    35: "CTRNS",
    36: "MED",
    37: "MUR",
    38: "CORT",
    39: "FALC",
    40: "CRV",
    41: "M/CRV",
    42: "FRG",
    43: "M/FRG",
    44: "LINER",
    45: "CRCK",
    46: "STRKC",
    47: "ESC",
    48: "DRD",
    49: "CRS",
    50: "CRL",
    51: "INT",
    52: "VSD",
    53: "ISD",
    54: "SSD",
    55: "CN/E",
    56: "CN/F",
    57: "CN/G",
    58: "CN/H",
    59: "CN/I",
    60: "PLT/A",
    61: "PLT/B",
    62: "PLT/C",
    63: "PLT/D",
    64: "PLT/E",
    65: "PLT/F",
    66: "Asteroid R&D Station",
    67: "Asteroid Laser Battery",
    68: "Asteroid Warhead Battery",
    69: "X/7 Factory",
    70: "Satellite 1",
    71: "Satellite 2",
    72: "Satellite 3",
    73: "*Satellite 4",
    74: "*Satellite 5",
    75: "Mine A",
    76: "Mine B",
    77: "Mine C",
    78: "Gun Emplacement",
    79: "*Mine 5",
    80: "Probe A",
    81: "Probe B",
    82: "*Probe 3",
    83: "Nav Buoy A",
    84: "Nav Buoy B",
    85: "Hyper Buoy",
    86: "Asteroid Field",
    87: "Planet",
    88: "Rendezvous Buoy",
    89: "Cargo Canister",
    90: "Shipyard",
    91: "Repair Yard",
    92: "*Modified Strike Cruiser",
    93: "Lancer Frigate",
    94: "Bulk Cruiser",
    95: "Assault Frigate",
    96: "Corellian Gunship",
    97: "Imperial Landing Craft",
    98: "Assault Shuttle",
    99: "Marauder Corvette",
    100: "Star Galleon",
    101: "Imperial Research Ship",
    102: "Luxury Yacht 3000",
    103: "Ferryboat Liner",
    104: "Modified Action Transport",
    105: "Mobquet Transport",
    106: "Xiytiar Transport",
    107: "Freight Transport/C",
    108: "Freight Transport/H",
    109: "Freight Transport/K",
    110: "YT-2000",
    111: "YT-2400",
    112: "Suprosa",
    113: "Skipray Blastboat",
    114: "T/e m1",
    115: "T/e m2",
    116: "T/e m3",
    117: "T/e m4",
    118: "T/e m5",
    119: "Cloakshape Fighter",
    120: "Razor Fighter",
    121: "Planetary Fighter",
    122: "Supa Fighter",
    123: "Pinook Fighter",
    124: "*Booster Pack",
    125: "Preybird Fighter",
    126: "*StarViper",
    127: "Firespray",
    128: "Pursuer",
    129: "Golan 1",
    130: "Golan 2",
    131: "Golan 3",
    132: "Derilyn Platform",
    133: "Sensor Array",
    134: "Comm Relay",
    135: "Space Colony 1",
    136: "Space Colony 2",
    137: "Space Colony 3",
    138: "Casino",
    139: "Cargo Facility 1",
    140: "Cargo Facility 2",
    141: "Asteroid Mining Plant",
    142: "Processing Plant",
    143: "Rebel Platform",
    144: "Imperial Research Center",
    145: "Family Base",
    146: "Family Repair Yard",
    147: "Pirate Shipyard",
    148: "Industrical Complex",
    149: "*Pirate Junkyard Base",
    150: "Escape Pod 1",
    151: "Pressure Tank",
    152: "Container J",
    153: "Container K",
    154: "Container L",
    155: "Container Hangar",
    156: "Large Gun Emplacement",
    157: "Large Gun/Warhead Emplacement",
    158: "Proximity Mine A",
    159: "Proximity Mine B",
    160: "*Homing Mine A",
    161: "Homing Mine B",
    162: "New Laser Battery",
    163: "New Ion Battery",
    164: "Cargo Freighter",
    165: "*Cargo Freighter 2",
    166: "*Cargo Freighter 3",
    167: "*Cargo Freighter 4",
    168: "*Cargo Freighter 5",
    169: "Cargo Tanker",
    170: "*Cargo Tanker 2",
    171: "*Cargo Tanker 3",
    172: "*Cargo Tanker 4",
    173: "*Cargo Tanker 5",
    174: "Escape Pod 2",
    175: "*Rebel Pilot",
    176: "*Imperial Pilot",
    177: "*Civilian Pilot",
    178: "Spacetrooper",
    179: "Zero-G Utility Suit",
    180: "Emkay",
    181: "Astromech",
    182: "Worker droid",
    183: "Backdrop",
    228: "W/CRS",
    229: "VSD-II",
    230: "ISD-II",
  };

  public static HANGAR = {
    0: "Junkyard",
    1: "Quick Start 1",
    2: "Quick Start 2",
    3: "Quick Start 3",
    4: "Skirmish",
    5: "Death Star run",
    6: "Calamari Cruiser",
    7: "Family Mission",
  };

  public static BRIEFINGOFFICER = {
    0: "Devers",
    1: "Kupalo",
    2: "Zaletta",
    8: "Emkay",
  };

  public static BRIEFINGLOGO = {
    4: "Defiance",
    5: "Liberty",
    6: "Independence",
    7: "Family",
    8: "Phantom Squadron",
  };

  public static DESIGNATION = {
    0: "Command Ship",
    1: "Base",
    2: "Station",
    3: "Mission Critical Craft",
    4: "Convoy Craft",
    5: "Strike Craft",
    6: "Reload Craft",
    7: "Primary Target",
    8: "Secondary Target",
    9: "Tertiary Target",
    10: "Resource Center",
    11: "Facility",
    12: "HYP from Region 1",
    13: "HYP from Region 2",
    14: "HYP from Region 3",
    15: "HYP from Region 4",
    16: "HYP to Region 1",
    17: "HYP to Region 2",
    18: "HYP to Region 3",
    19: "HYP to Region 4",
    20: "Unknown",
    21: "Unknown",
  };

  public static STATUS = {
    0: "None",
    1: "2X Warheads",
    2: "1/2 Warheads",
    3: "No Shields",
    4: "1/2 Shields",
    5: "No Lasers",
    6: "No Hyperdrive",
    7: "Shields 0%, charging",
    8: "Shields added or 200%",
    9: "Hyperdrive added",
    10: "2x Countermeasure",
    11: "1/2 Countermeasures",
    12: "(200% Shields)",
    13: "Shields 50%, Charging",
    14: "(No Lasers)",
    15: "Engines Damaged",
    16: "Shields + Hyperdrive added",
    17: "All Systems Damaged",
    18: "200% Shields",
    19: "(50% Shields)",
    20: "Invincible",
    21: "Infinite Warheads",
    22: "No Escape Pods / Ejected Pilot",
    23: "No Cargo Pods",
    24: "Not Inspected",
    25: "Not ID'ed",
    26: "Inspected",
    27: "ID'ed",
    28: "Limited Targetability",
  };

  public static WARHEAD = {
    0: "None",
    1: "Space Bomb",
    2: "Heavy Rocket",
    3: "Concussion Missile",
    4: "Torpedo",
    5: "Advanced Concussion Missile",
    6: "Advanced Torpedo",
    7: "Mag Pulse Torpedo",
    8: "Ion Pulse Torpedo",
  };

  public static BEAM = {
    0: "None",
    1: "Tractor Beam",
    2: "Jamming Beam",
    3: "Decoy Beam",
  };

  public static GROUPAI = {
    0: "Novice (None)",
    1: "Officer",
    2: "Veteran",
    3: "Ace",
    4: "Top Ace",
    5: "Super Ace (Invincible)",
  };

  public static MARKINGS = {
    0: "Red (TIE - None)",
    1: "Gold (TIE - Red)",
    2: "Blue (TIE - Gold)",
    3: "Green (TIE - Blue)",
  };

  public static RADIO = {
    0: "None",
    1: "Team 1",
    2: "Team 2",
    3: "Team 3",
    4: "Team 4",
    5: "Team 5",
    6: "Team 6",
    7: "Team 7",
    8: "Team 8",
    9: "Player 1",
    10: "Player 2",
    11: "Player 3",
    12: "Player 4",
    13: "Player 5",
    14: "Player 6",
    15: "Player 7",
    16: "Player 8",
  };

  public static FORMATION = {
    0: "Vic",
    1: "Finger Four",
    2: "Line Astern",
    3: "Line Abreast",
    4: "Echelon Right",
    5: "Echelon Left",
    6: "Double Astern",
    7: "Diamond",
    8: "Stack",
    9: "High X",
    10: "Vic Abreast",
    11: "High Vic",
    12: "Reverse High Vic",
    13: "Reverse Line Astern",
    14: "Stacked Low",
    15: "Abreast Right",
    16: "Abreast Left",
    17: "Wing Forward",
    18: "Wing Back",
    19: "Line Astern Up",
    20: "Line Astern Down",
    21: "Abreast V",
    22: "Abreast Inverted V",
    23: "Double Astern Mirror",
    24: "Double Stacked Astern",
    25: "Double Stacked High",
    26: "Diamond 1",
    27: "Diamond 2",
    28: "Flat Pentagon",
    29: "Side Pentagon",
    30: "Front Pentagon",
    31: "Flat Hexagon",
    32: "Side Hexagon",
    33: "Front Hexagon",
    34: "Single Point",
  };

  public static ARRIVALDIFFICULTY = {
    0: "All",
    1: "Easy",
    2: "Medium",
    3: "Hard",
    4: "Greater than Easy",
    5: "Less than Hard",
    6: "Never",
  };

  public static CONDITION = {
    0: "Always (true)",
    1: "Created",
    2: "Destroyed",
    3: "Attacked",
    4: "Captured",
    5: "Inspected",
    6: "Boarded",
    7: "Docked",
    8: "Disabled",
    9: "Exist",
    10: "None (false)",
    11: "Unknown (---)",
    12: "Completed mission",
    13: "Completed Primary Goals",
    14: "Failed Primary Goals",
    15: "Completed Secondary Goals",
    16: "Failed Secondary Goals",
    17: "Completed Bonus Goals",
    18: "Failed Bonus Goals",
    19: "Dropped off",
    20: "Reinforced",
    21: "0% Shields",
    22: "50% Hull",
    23: "Out of Warheads",
    24: "Unknown (arrive?)",
    25: "Be dropped off",
    26: "Unharmed?",
    27: "NOT be disabled",
    28: "NOT be picked up",
    29: "Destroyed w/o Inspection",
    30: "Be docked with",
    31: "NOT be docked with",
    32: "Begin boarding",
    33: "NOT begin boarding",
    34: "50% Shields",
    35: "25% Shields",
    36: "75% Hull",
    37: "25% Hull",
    38: "Unknown",
    39: "Unknown",
    40: "Unknown",
    41: "Be all Player Craft",
    42: "Reinforced by AI?",
    43: "Come and go",
    44: "Be picked up",
    45: "Withdraw",
    46: "Be carried away",
    47: "Arrived in Region",
    48: "Departed Region",
    49: "Be in proximity of",
    50: "NOT be in proxmity of",
    51: "Unknown",
    52: "Defect",
    53: "Be in convoy",
    54: "Be delivered?",
    55: "Unknown",
    56: "Be shown (message)",
    57: "Be ID'ed",
    58: "Unknown",
    59: "Exist?",
  };

  public static VARIABLETYPE = {
    0: "None",
    1: "Flight Group",
    2: "CraftType (enum)",
    3: "CraftCategory (enum)",
    4: "ObjectCategory (enum)",
    5: "IFF",
    6: "Order (enum)",
    7: "CraftWhen (enum)",
    8: "Global Group",
    9: "Rating",
    10: "Craft with Status1",
    11: "All",
    12: "Team",
    13: "Player",
    14: "Delay",
    15: "All Flight Groups except",
    16: "All Craft Types except",
    17: "All Craft Categories except",
    18: "All Object Categories except",
    19: "All IFFs except",
    20: "All Global Groups except",
    21: "All Teams except",
    22: "All players except",
    23: "Global Unit",
    24: "All Global Units except?",
    25: "Craft with Global Cargo",
    26: "Craft without Global Cargo",
    27: "Message #",
  };

  public static CRAFTCATEGORY = {
    0: "Starfighters",
    1: "Transports",
    2: "Freighters/Containers",
    3: "Starships",
    4: "Utility Craft",
    5: "Platforms/Facilities",
    6: "Mines",
  };

  public static OBJECTCATEGORY = {
    0: "Craft",
    1: "Weapons",
    2: "Space Objects",
  };

  public static AMOUNT = {
    0: "100%",
    1: "75%",
    2: "50%",
    3: "25%",
    4: "At least one",
    5: "All but one",
    6: "Special craft",
    7: "All non-special craft",
    8: "All non-player craft",
    9: "Player's craft",
    10: "Unknown",
    16: "66%",
    17: "33%",
    18: "Each craft",
    19: "Each special craft",
  };

  public static ABORTTRIGGER = {
    0: "None",
    1: "0% Shields",
    2: "Unknown",
    3: "Out of warheads",
    4: "50% Hull",
    5: "Attacked",
    6: "50% Shields",
    7: "25% Shields",
    8: "75% Hull",
    9: "25% Hull",
  };

  public static ORDER = {
    0: "Hold Station",
    1: "Go Home",
    2: "Circle",
    3: "Circle and Evade",
    4: "Rendezvous",
    5: "Disabled",
    6: "Await Boarding",
    7: "Attack",
    8: "Attack Escorts",
    9: "Protect",
    10: "Escort",
    11: "Disable",
    12: "Board and Give Cargo",
    13: "Board and Take Cargo",
    14: "Board and Exchange Cargo",
    15: "Board and Capture Cargo",
    16: "Board and Destroy Cargo",
    17: "Pick up",
    18: "Drop off",
    19: "Wait",
    20: "SS Wait",
    21: "SS Patrol Loop",
    22: "SS Await Return",
    23: "SS Launch",
    24: "SS Protect",
    25: "SS Wait and Protect",
    26: "SS Patrol and Attack",
    27: "SS Patrol and Disable",
    28: "SS Hold Steady",
    29: "SS Go Home",
    30: "SS Wait",
    31: "SS Board",
    32: "Board to Repair",
    33: "Hold Station",
    34: "Hold Steady",
    35: "SS Hold Station",
    36: "Self-destruct",
    37: "Kamikaze",
    38: "(Orbit)/Permanently disabled",
    39: "(Release Carried Cargo)",
    40: "Deliver/Drop Off",
    41: "Unknown",
    42: "(Attack)",
    43: "Load Objects",
    44: "Sit and Fire",
    45: "Repair Self",
    46: "Defect",
    47: "Self Capture / Surrender",
    48: "*Make",
    49: "Beacon",
    50: "Hyper to Region",
    51: "*Relaunch",
    52: "Transfer Cargo",
    53: "Inspect Targets",
    54: "*Await Assembly",
    55: "*Await Disassembly",
    56: "*Construct Train",
    57: "Park at",
    58: "*Board to Defuse",
    59: "Start Over",
    60: "*Take Apart Train",
    61: "Work on",
    62: "(Dock to Load)",
    63: "Follow Targets",
    64: "Home In",
  };

  public static CRAFTWHEN = {
    1: "Inspected",
    2: "Finished docking?",
    4: "Disabled",
    5: "Attacked",
    6: "Any hull damage",
    7: "Special craft",
    8: "Non-special craft",
    9: "Player's craft",
    10: "Non-player's craft",
    12: "not disabled",
  };

  public static EVENTTYPE = {
    3: "Page Break",
    4: "Title Text",
    5: "Caption Text",
    6: "Move Map",
    7: "Zoom Map",
    8: "Clear FG Tags",
    9: "FG Tag 1",
    10: "FG Tag 2",
    11: "FG Tag 3",
    12: "FG Tag 4",
    13: "FG Tag 5",
    14: "FG Tag 6",
    15: "FG Tag 7",
    16: "FG Tag 8",
    17: "Clear Text Tags",
    18: "Text Tag 1",
    19: "Text Tag 2",
    20: "Text Tag 3",
    21: "Text Tag 4",
    22: "Text Tag 5",
    23: "Text Tag 6",
    24: "Text Tag 7",
    25: "Text Tag 8",
    26: "New Icon",
    27: "Ship Craft Data",
    28: "Move Icon",
    29: "Rotate Icon",
    30: "Change Region",
    34: "End Briefing",
  };

}

export enum CraftType {
  xwing = 1,
  ywing = 2,
  awing = 3,
  bwing = 4,
  tieFighter = 5,
  tieInterceptor = 6,
  tieBomber = 7,
  tieAdvanced = 8,
  tieDefender = 9,
  irdFighter = 10,
  toscanFighter = 11,
  missileBoat = 12,
  twing = 13,
  z95Headhunter = 14,
  r41Starchaser = 15,
  assaultGunboat = 16,
  shuttle = 17,
  escortShuttle = 18,
  systemPatrolCraft = 19,
  scoutCraft = 20,
  stormtrooperTransport = 21,
  assaultTransport = 22,
  escortTransport = 23,
  tug = 24,
  combatUtilityVehicle = 25,
  containerA = 26,
  containerB = 27,
  containerC = 28,
  containerD = 29,
  heavyLifter = 30,
  moleMiner = 31,
  bulkFreighter = 32,
  cargoFerry = 33,
  modularConveyor = 34,
  containerTransport = 35,
  mediumTransport = 36,
  murrianTransport = 37,
  corellianTransport = 38,
  milleniumFalcon = 39,
  corellianCorvette = 40,
  modifiedCorvette = 41,
  nebulonBFrigate = 42,
  modifiedFrigate = 43,
  c3PassengerLiner = 44,
  carrackCruiser = 45,
  strikeCruiser = 46,
  escortCarrier = 47,
  dreadnaught = 48,
  mc80ACruiser = 49,
  mc40ALightCruiser = 50,
  interdictorCruiser = 51,
  victoryclassStarDestroyer = 52,
  imperatorclassStarDestroyer = 53,
  executorclassStarDestroyer = 54,
  containerE = 55,
  containerF = 56,
  containerG = 57,
  containerH = 58,
  containerI = 59,
  platformA = 60,
  platformB = 61,
  platformC = 62,
  platformD = 63,
  platformE = 64,
  platformF = 65,
  asteroidRnDStation = 66,
  asteroidLaserBattery = 67,
  asteroidWarheadBattery = 68,
  x7Factory = 69,
  satellite1 = 70,
  satellite2 = 71,
  satellite3 = 72,
  satellite4 = 73,
  satellite5 = 74,
  mineA = 75,
  mineB = 76,
  mineC = 77,
  gunEmplacement = 78,
  mine5 = 79,
  probeA = 80,
  probeB = 81,
  probe3 = 82,
  navBuoyA = 83,
  navBuoyB = 84,
  hyperBuoy = 85,
  asteroidField = 86,
  planet = 87,
  rendezvousBuoy = 88,
  cargoCanister = 89,
  shipyard = 90,
  repairYard = 91,
  modifiedStrikeCruiser = 92,
  lancerFrigate = 93,
  bulkCruiser = 94,
  assaultFrigate = 95,
  corellianGunship = 96,
  imperialLandingCraft = 97,
  assaultShuttle = 98,
  marauderCorvette = 99,
  starGalleon = 100,
  imperialResearchShip = 101,
  luxuryYacht3000 = 102,
  ferryboatLiner = 103,
  modifiedActionTransport = 104,
  mobquetTransport = 105,
  xiytiarTransport = 106,
  freightTransportC = 107,
  freightTransportH = 108,
  freightTransportK = 109,
  yt2000 = 110,
  yt2400 = 111,
  suprosa = 112,
  skiprayBlastboat = 113,
  teM1 = 114,
  teM2 = 115,
  teM3 = 116,
  teM4 = 117,
  teM5 = 118,
  cloakshapeFighter = 119,
  razorFighter = 120,
  planetaryFighter = 121,
  supaFighter = 122,
  pinookFighter = 123,
  boosterPack = 124,
  preybirdFighter = 125,
  starViper = 126,
  firespray = 127,
  pursuer = 128,
  golan1 = 129,
  golan2 = 130,
  golan3 = 131,
  derilynPlatform = 132,
  sensorArray = 133,
  commRelay = 134,
  spaceColony1 = 135,
  spaceColony2 = 136,
  spaceColony3 = 137,
  casino = 138,
  cargoFacility1 = 139,
  cargoFacility2 = 140,
  asteroidMiningPlant = 141,
  processingPlant = 142,
  rebelPlatform = 143,
  imperialResearchCenter = 144,
  familyBase = 145,
  familyRepairYard = 146,
  pirateShipyard = 147,
  industricalComplex = 148,
  pirateJunkyardBase = 149,
  escapePod1 = 150,
  pressureTank = 151,
  containerJ = 152,
  containerK = 153,
  containerL = 154,
  containerHangar = 155,
  largeGunEmplacement = 156,
  largeGunWarheadEmplacement = 157,
  proximityMineA = 158,
  proximityMineB = 159,
  homingMineA = 160,
  homingMineB = 161,
  newLaserBattery = 162,
  newIonBattery = 163,
  cargoFreighter = 164,
  cargoFreighter2 = 165,
  cargoFreighter3 = 166,
  cargoFreighter4 = 167,
  cargoFreighter5 = 168,
  cargoTanker = 169,
  cargoTanker2 = 170,
  cargoTanker3 = 171,
  cargoTanker4 = 172,
  cargoTanker5 = 173,
  escapePod2 = 174,
  rebelPilot = 175,
  imperialPilot = 176,
  civilianPilot = 177,
  spacetrooper = 178,
  zeroGUtilitySuit = 179,
  emkay = 180,
  astromech = 181,
  workerDroid = 182,
  backdrop = 183,
  forestMoonOfEndor = 184,
  endor = 185,
  sullust = 186,
  bothuwai = 187,
  kothlis = 188,
  hoth = 189,
  deathStarIiBackdrop = 190,
  narShadda = 191,
  // duplicate planet = 192,
  // duplicate planet = 197,
  moon = 198,
  // duplicate moon = 202,
  sun = 203,
  // duplicate sun = 212,
  // duplicate backdrop = 213,
  // duplicate backdrop = 226,
  deathStarIi = 227,
  mc80LibertyclassCruiser = 228,
  victoryclassStarDestroyerIi = 229,
  imperatorclassStarDestroyerIi = 230,
  // duplicate planet = 231,
}

export enum CraftAbbr {
  xw = 1,
  yw = 2,
  aw = 3,
  bw = 4,
  tf = 5,
  ti = 6,
  tb = 7,
  ta = 8,
  td = 9,
  ird = 10,
  tos = 11,
  mis = 12,
  tw = 13,
  z95 = 14,
  r41 = 15,
  gun = 16,
  shu = 17,
  es = 18,
  spc = 19,
  sct = 20,
  trn = 21,
  atr = 22,
  etr = 23,
  tug = 24,
  cuv = 25,
  cna = 26,
  cnb = 27,
  cnc = 28,
  cnd = 29,
  hlf = 30,
  moleMiner = 31,
  frt = 32,
  carg = 33,
  cnvyr = 34,
  ctrns = 35,
  med = 36,
  mur = 37,
  cort = 38,
  falc = 39,
  crv = 40,
  mcrv = 41,
  frg = 42,
  mfrg = 43,
  liner = 44,
  crck = 45,
  strkc = 46,
  esc = 47,
  drd = 48,
  crs = 49,
  crl = 50,
  int = 51,
  vsd = 52,
  isd = 53,
  ssd = 54,
  cne = 55,
  cnf = 56,
  cng = 57,
  cnh = 58,
  cni = 59,
  plta = 60,
  pltb = 61,
  pltc = 62,
  pltd = 63,
  plte = 64,
  pltf = 65,
  asteroidRnDStation = 66,
  asteroidLaserBattery = 67,
  asteroidWarheadBattery = 68,
  x7Factory = 69,
  satellite1 = 70,
  satellite2 = 71,
  satellite3 = 72,
  satellite4 = 73,
  satellite5 = 74,
  mineA = 75,
  mineB = 76,
  mineC = 77,
  gunEmplacement = 78,
  mine5 = 79,
  probeA = 80,
  probeB = 81,
  probe3 = 82,
  navBuoyA = 83,
  navBuoyB = 84,
  hyperBuoy = 85,
  asteroidField = 86,
  planet = 87,
  rendezvousBuoy = 88,
  cargoCanister = 89,
  shipyard = 90,
  repairYard = 91,
  modifiedStrikeCruiser = 92,
  lancerFrigate = 93,
  bulkCruiser = 94,
  assaultFrigate = 95,
  corellianGunship = 96,
  imperialLandingCraft = 97,
  assaultShuttle = 98,
  marauderCorvette = 99,
  starGalleon = 100,
  imperialResearchShip = 101,
  luxuryYacht3000 = 102,
  ferryboatLiner = 103,
  modifiedActionTransport = 104,
  mobquetTransport = 105,
  xiytiarTransport = 106,
  freightTransportC = 107,
  freightTransportH = 108,
  freightTransportK = 109,
  yt2000 = 110,
  yt2400 = 111,
  suprosa = 112,
  skiprayBlastboat = 113,
  teM1 = 114,
  teM2 = 115,
  teM3 = 116,
  teM4 = 117,
  teM5 = 118,
  cloakshapeFighter = 119,
  razorFighter = 120,
  planetaryFighter = 121,
  supaFighter = 122,
  pinookFighter = 123,
  boosterPack = 124,
  preybirdFighter = 125,
  starViper = 126,
  firespray = 127,
  pursuer = 128,
  golan1 = 129,
  golan2 = 130,
  golan3 = 131,
  derilynPlatform = 132,
  sensorArray = 133,
  commRelay = 134,
  spaceColony1 = 135,
  spaceColony2 = 136,
  spaceColony3 = 137,
  casino = 138,
  cargoFacility1 = 139,
  cargoFacility2 = 140,
  asteroidMiningPlant = 141,
  processingPlant = 142,
  rebelPlatform = 143,
  imperialResearchCenter = 144,
  familyBase = 145,
  familyRepairYard = 146,
  pirateShipyard = 147,
  industricalComplex = 148,
  pirateJunkyardBase = 149,
  escapePod1 = 150,
  pressureTank = 151,
  containerJ = 152,
  containerK = 153,
  containerL = 154,
  containerHangar = 155,
  largeGunEmplacement = 156,
  largeGunWarheadEmplacement = 157,
  proximityMineA = 158,
  proximityMineB = 159,
  homingMineA = 160,
  homingMineB = 161,
  newLaserBattery = 162,
  newIonBattery = 163,
  cargoFreighter = 164,
  cargoFreighter2 = 165,
  cargoFreighter3 = 166,
  cargoFreighter4 = 167,
  cargoFreighter5 = 168,
  cargoTanker = 169,
  cargoTanker2 = 170,
  cargoTanker3 = 171,
  cargoTanker4 = 172,
  cargoTanker5 = 173,
  escapePod2 = 174,
  rebelPilot = 175,
  imperialPilot = 176,
  civilianPilot = 177,
  spacetrooper = 178,
  zeroGUtilitySuit = 179,
  emkay = 180,
  astromech = 181,
  workerDroid = 182,
  backdrop = 183,
  wcrs = 228,
  vsdii = 229,
  isdii = 230,
}

export enum Hangar {
  junkyard = 0,
  quickStart1 = 1,
  quickStart2 = 2,
  quickStart3 = 3,
  skirmish = 4,
  deathStarRun = 5,
  calamariCruiser = 6,
  familyMission = 7,
}

export enum BriefingOfficer {
  devers = 0,
  kupalo = 1,
  zaletta = 2,
  emkay = 8,
}

export enum BriefingLogo {
  defiance = 4,
  liberty = 5,
  independence = 6,
  family = 7,
  phantomSquadron = 8,
}

export enum Designation {
  commandShip = 0,
  base = 1,
  station = 2,
  missionCriticalCraft = 3,
  convoyCraft = 4,
  strikeCraft = 5,
  reloadCraft = 6,
  primaryTarget = 7,
  secondaryTarget = 8,
  tertiaryTarget = 9,
  resourceCenter = 10,
  facility = 11,
  hypFromRegion1 = 12,
  hypFromRegion2 = 13,
  hypFromRegion3 = 14,
  hypFromRegion4 = 15,
  hypToRegion1 = 16,
  hypToRegion2 = 17,
  hypToRegion3 = 18,
  hypToRegion4 = 19,
  unknown = 20,
  // duplicate unknown = 21,
}

export enum Status {
  none = 0,
  n2XWarheads = 1,
  n12Warheads = 2,
  noShields = 3,
  n12Shields = 4,
  noLasers = 5,
  noHyperdrive = 6,
  shields0PercentCharging = 7,
  shieldsAddedOr200Percent = 8,
  hyperdriveAdded = 9,
  n2XCountermeasure = 10,
  n12Countermeasures = 11,
  n200PercentShields = 12,
  shields50PercentCharging = 13,
  // duplicate noLasers = 14,
  enginesDamaged = 15,
  shieldsHyperdriveAdded = 16,
  allSystemsDamaged = 17,
  // duplicate n200PercentShields = 18,
  n50PercentShields = 19,
  invincible = 20,
  infiniteWarheads = 21,
  noEscapePodsEjectedPilot = 22,
  noCargoPods = 23,
  notInspected = 24,
  notIDed = 25,
  inspected = 26,
  iDed = 27,
  limitedTargetability = 28,
}

export enum Warhead {
  none = 0,
  spaceBomb = 1,
  heavyRocket = 2,
  concussionMissile = 3,
  torpedo = 4,
  advancedConcussionMissile = 5,
  advancedTorpedo = 6,
  magPulseTorpedo = 7,
  ionPulseTorpedo = 8,
}

export enum Beam {
  none = 0,
  tractorBeam = 1,
  jammingBeam = 2,
  decoyBeam = 3,
}

export enum GroupAI {
  noviceNone = 0,
  officer = 1,
  veteran = 2,
  ace = 3,
  topAce = 4,
  superAceInvincible = 5,
}

export enum Markings {
  redTieNone = 0,
  goldTieRed = 1,
  blueTieGold = 2,
  greenTieBlue = 3,
}

export enum Radio {
  none = 0,
  team1 = 1,
  team2 = 2,
  team3 = 3,
  team4 = 4,
  team5 = 5,
  team6 = 6,
  team7 = 7,
  team8 = 8,
  player1 = 9,
  player2 = 10,
  player3 = 11,
  player4 = 12,
  player5 = 13,
  player6 = 14,
  player7 = 15,
  player8 = 16,
}

export enum Formation {
  vic = 0,
  fingerFour = 1,
  lineAstern = 2,
  lineAbreast = 3,
  echelonRight = 4,
  echelonLeft = 5,
  doubleAstern = 6,
  diamond = 7,
  stack = 8,
  highX = 9,
  vicAbreast = 10,
  highVic = 11,
  reverseHighVic = 12,
  reverseLineAstern = 13,
  stackedLow = 14,
  abreastRight = 15,
  abreastLeft = 16,
  wingForward = 17,
  wingBack = 18,
  lineAsternUp = 19,
  lineAsternDown = 20,
  abreastV = 21,
  abreastInvertedV = 22,
  doubleAsternMirror = 23,
  doubleStackedAstern = 24,
  doubleStackedHigh = 25,
  diamond1 = 26,
  diamond2 = 27,
  flatPentagon = 28,
  sidePentagon = 29,
  frontPentagon = 30,
  flatHexagon = 31,
  sideHexagon = 32,
  frontHexagon = 33,
  singlePoint = 34,
}

export enum ArrivalDifficulty {
  all = 0,
  easy = 1,
  medium = 2,
  hard = 3,
  greaterThanEasy = 4,
  lessThanHard = 5,
  never = 6,
}

export enum Condition {
  alwaysTrue = 0,
  created = 1,
  destroyed = 2,
  attacked = 3,
  captured = 4,
  inspected = 5,
  boarded = 6,
  docked = 7,
  disabled = 8,
  exist = 9,
  noneFalse = 10,
  unknown = 11,
  completedMission = 12,
  completedPrimaryGoals = 13,
  failedPrimaryGoals = 14,
  completedSecondaryGoals = 15,
  failedSecondaryGoals = 16,
  completedBonusGoals = 17,
  failedBonusGoals = 18,
  droppedOff = 19,
  reinforced = 20,
  n0PercentShields = 21,
  n50PercentHull = 22,
  outOfWarheads = 23,
  unknownArrive = 24,
  beDroppedOff = 25,
  unharmed = 26,
  notBeDisabled = 27,
  notBePickedUp = 28,
  destroyedWoInspection = 29,
  beDockedWith = 30,
  notBeDockedWith = 31,
  beginBoarding = 32,
  notBeginBoarding = 33,
  n50PercentShields = 34,
  n25PercentShields = 35,
  n75PercentHull = 36,
  n25PercentHull = 37,
  // duplicate unknown = 38,
  // duplicate unknown = 39,
  // duplicate unknown = 40,
  beAllPlayerCraft = 41,
  reinforcedByAi = 42,
  comeAndGo = 43,
  bePickedUp = 44,
  withdraw = 45,
  beCarriedAway = 46,
  arrivedInRegion = 47,
  departedRegion = 48,
  beInProximityOf = 49,
  notBeInProxmityOf = 50,
  // duplicate unknown = 51,
  defect = 52,
  beInConvoy = 53,
  beDelivered = 54,
  // duplicate unknown = 55,
  beShownMessage = 56,
  beIDed = 57,
  // duplicate unknown = 58,
  // duplicate exist = 59,
}

export enum VariableType {
  none = 0,
  flightGroup = 1,
  craftTypeEnum = 2,
  craftCategoryEnum = 3,
  objectCategoryEnum = 4,
  iff = 5,
  orderEnum = 6,
  craftWhenEnum = 7,
  globalGroup = 8,
  rating = 9,
  craftWithStatus1 = 10,
  all = 11,
  team = 12,
  player = 13,
  delay = 14,
  allFlightGroupsExcept = 15,
  allCraftTypesExcept = 16,
  allCraftCategoriesExcept = 17,
  allObjectCategoriesExcept = 18,
  allIfFsExcept = 19,
  allGlobalGroupsExcept = 20,
  allTeamsExcept = 21,
  allPlayersExcept = 22,
  globalUnit = 23,
  allGlobalUnitsExcept = 24,
  craftWithGlobalCargo = 25,
  craftWithoutGlobalCargo = 26,
  message = 27,
}

export enum CraftCategory {
  starfighters = 0,
  transports = 1,
  freightersContainers = 2,
  starships = 3,
  utilityCraft = 4,
  platformsFacilities = 5,
  mines = 6,
}

export enum ObjectCategory {
  craft = 0,
  weapons = 1,
  spaceObjects = 2,
}

export enum Amount {
  n100Percent = 0,
  n75Percent = 1,
  n50Percent = 2,
  n25Percent = 3,
  atLeastOne = 4,
  allButOne = 5,
  specialCraft = 6,
  allNonspecialCraft = 7,
  allNonplayerCraft = 8,
  playersCraft = 9,
  unknown = 10,
  n66Percent = 16,
  n33Percent = 17,
  eachCraft = 18,
  eachSpecialCraft = 19,
}

export enum AbortTrigger {
  none = 0,
  n0PercentShields = 1,
  unknown = 2,
  outOfWarheads = 3,
  n50PercentHull = 4,
  attacked = 5,
  n50PercentShields = 6,
  n25PercentShields = 7,
  n75PercentHull = 8,
  n25PercentHull = 9,
}

export enum Order {
  holdStation = 0,
  goHome = 1,
  circle = 2,
  circleAndEvade = 3,
  rendezvous = 4,
  disabled = 5,
  awaitBoarding = 6,
  attack = 7,
  attackEscorts = 8,
  protect = 9,
  escort = 10,
  disable = 11,
  boardAndGiveCargo = 12,
  boardAndTakeCargo = 13,
  boardAndExchangeCargo = 14,
  boardAndCaptureCargo = 15,
  boardAndDestroyCargo = 16,
  pickUp = 17,
  dropOff = 18,
  wait = 19,
  ssWait = 20,
  ssPatrolLoop = 21,
  ssAwaitReturn = 22,
  ssLaunch = 23,
  ssProtect = 24,
  ssWaitAndProtect = 25,
  ssPatrolAndAttack = 26,
  ssPatrolAndDisable = 27,
  ssHoldSteady = 28,
  ssGoHome = 29,
  // duplicate ssWait = 30,
  ssBoard = 31,
  boardToRepair = 32,
  // duplicate holdStation = 33,
  holdSteady = 34,
  ssHoldStation = 35,
  selfdestruct = 36,
  kamikaze = 37,
  orbitPermanentlyDisabled = 38,
  releaseCarriedCargo = 39,
  deliverDropOff = 40,
  unknown = 41,
  // duplicate attack = 42,
  loadObjects = 43,
  sitAndFire = 44,
  repairSelf = 45,
  defect = 46,
  selfCaptureSurrender = 47,
  make = 48,
  beacon = 49,
  hyperToRegion = 50,
  relaunch = 51,
  transferCargo = 52,
  inspectTargets = 53,
  awaitAssembly = 54,
  awaitDisassembly = 55,
  constructTrain = 56,
  parkAt = 57,
  boardToDefuse = 58,
  startOver = 59,
  takeApartTrain = 60,
  workOn = 61,
  dockToLoad = 62,
  followTargets = 63,
  homeIn = 64,
}

export enum CraftWhen {
  inspected = 1,
  finishedDocking = 2,
  disabled = 4,
  attacked = 5,
  anyHullDamage = 6,
  specialCraft = 7,
  nonspecialCraft = 8,
  playersCraft = 9,
  nonplayersCraft = 10,
  notDisabled = 12,
}

export enum EventType {
  pageBreak = 3,
  titleText = 4,
  captionText = 5,
  moveMap = 6,
  zoomMap = 7,
  clearFgTags = 8,
  fgTag1 = 9,
  fgTag2 = 10,
  fgTag3 = 11,
  fgTag4 = 12,
  fgTag5 = 13,
  fgTag6 = 14,
  fgTag7 = 15,
  fgTag8 = 16,
  clearTextTags = 17,
  textTag1 = 18,
  textTag2 = 19,
  textTag3 = 20,
  textTag4 = 21,
  textTag5 = 22,
  textTag6 = 23,
  textTag7 = 24,
  textTag8 = 25,
  newIcon = 26,
  shipCraftData = 27,
  moveIcon = 28,
  rotateIcon = 29,
  changeRegion = 30,
  endBriefing = 34,
}
