export declare function getBool(hex: ArrayBuffer, start?: number): boolean;
export declare function getByte(hex: ArrayBuffer, start?: number): number;
export declare function getByteString(byte: number): string;
export declare function getSByte(hex: ArrayBuffer, start?: number): number;
export declare function getSChar(hex: ArrayBuffer, start?: number, length?: number): string;
export declare function getChar(hex: ArrayBuffer, start?: number, length?: number): string;
export declare function getShort(hex: ArrayBuffer, start?: number): number;
export declare function getUShort(hex: ArrayBuffer, start?: number): number;
export declare function getInt(hex: ArrayBuffer, start?: number): number;
export declare function getIntArray(hex: ArrayBuffer, start?: number, count?: number): number[];
export declare function getUInt(hex: ArrayBuffer, start?: number): number;
export declare function getString(hex: ArrayBuffer, start?: number, length?: number): string;
export declare function writeBool(hex: string, value: boolean, start?: number): void;
export declare function writeByte(hex: string, value: number, start?: number): void;
export declare function writeSByte(hex: string, value: number, start?: number): void;
export declare function writeChar(hex: string, value: string, length?: number, start?: number): void;
export declare function writeShort(hex: string, value: number, start?: number): void;
export declare function writeUShort(hex: string, value: number, start?: number): void;
export declare function writeInt(hex: string, value: number, start?: number): void;
export declare function writeString(hex: string, value: string, start?: number, length?: number): void;
export declare function writeObject(hex: string, value: any, position: number): void;
