<?php
namespace Pyrite\XvT;

class Constants
{
    public static $SHIPS = [
        0 => "Unknown",
        1 => "X-Wing",
        2 => "Y-Wing",
        3 => "A-Wing",
        4 => "*B-Wing",
        5 => "TIE Fighter",
        6 => "TIE Interceptor",
        7 => "TIE Bomber",
        8 => "TIE Advanced",
        9 => "*TIE Defender",
        10 => "Patch Slot 10",
        11 => "Patch Slot 11",
        12 => "Missile Boat",
        13 => "T-Wing",
        14 => "Z-95 Headhunter",
        15 => "R-41 Starchaser",
        16 => "Assault Gunboat",
        17 => "Shuttle",
        18 => "Escort Shuttle",
        19 => "System Patrol Craft",
        20 => "*Scout Craft",
        21 => "Stormtrooper Transport",
        22 => "Assault Transport",
        23 => "Escort Transport",
        24 => "Utility Tug",
        25 => "Combat Utility Vehicle",
        26 => "Container Class A",
        27 => "Container Class B",
        28 => "Container Class C",
        29 => "Container Class D",
        30 => "Heavy Lifter",
        31 => "*bulk_barge2",
        32 => "Bulk Freighter",
        33 => "Cargo Ferry",
        34 => "Modular Conveyor",
        35 => "Container Transport",
        36 => "*new_freighter3",
        37 => "Muurian Transport",
        38 => "Corellian Transport",
        39 => "*Millenium",
        40 => "Corellian Corvette",
        41 => "*Modified Corvette",
        42 => "Nebulon B Frigate",
        43 => "*Modified Frigate",
        44 => "*Passenger Liner",
        45 => "*Carrack Cruiser",
        46 => "Strike Cruiser",
        47 => "Escort Carrier",
        48 => "Dreadnaught",
        49 => "Calamari Cruiser",
        50 => "Lt. Calamari Cruiser",
        51 => "Interdictor",
        52 => "Victory Star Destroyer",
        53 => "Imperial Star Destroyer",
        54 => "*super_sd",
        55 => "Container Class E",
        56 => "Container Class F",
        57 => "Container Class G",
        58 => "Container Class H",
        59 => "Container Class I",
        60 => "XQ1 Platform",
        61 => "XQ2 Platform",
        62 => "XQ3 Platform",
        63 => "XQ4 Platform",
        64 => "XQ5 Platform",
        65 => "XQ6 Platform",
        66 => "Asteroid Hangar",
        67 => "Asteroid Laser Battery",
        68 => "Asteroid War Launcher",
        69 => "X7 Factory",
        70 => "Comm Sat",
        71 => "Comm Sat",
        72 => "*Sat3",
        73 => "*Sat4",
        74 => "*Sat5",
        75 => "Mine Type A",
        76 => "Mine Type B",
        77 => "Mine Type C",
        78 => "*Mine4",
        79 => "*Mine5",
        80 => "Probe",
        81 => "*Probe2",
        82 => "*Probe3",
        83 => "Nav Buoy",
        84 => "Nav Buoy",
        85 => "*Pilot",
        86 => "Asteroid",
        87 => "Planet",
        88 => "Obstacle",
        89 => "Unused",
        90 => "Shipyard",
        91 => "Repair Yard",
        92 => "Modified Strike Cruiser",
    ];

    public static $PILOTRATING = [
        0 => "Target Drone",
        1 => "Ground Crew",
        2 => "Trainee",
        3 => "Flight Cadet",
        4 => "Officer 4th Class",
        5 => "Officer 3rd Class",
        6 => "Officer 2nd Class",
        7 => "Officer 1st Class",
        8 => "Veteran 4th Grade",
        9 => "Veteran 3rd Grade",
        10 => "Veteran 2nd Grade",
        11 => "Veteran 1st Grade",
        12 => "Ace 4th Level",
        13 => "Ace 3rd Level",
        14 => "Ace 2nd Level",
        15 => "Ace 1st Level",
        16 => "Top Ace 4th Order",
        17 => "Top Ace 3rd Order",
        18 => "Top Ace 2nd Order",
        19 => "Top Ace 1st Order",
        20 => "Jedi 4th Degree",
        21 => "Jedi 3rd Degree",
        22 => "Jedi 2nd Degree",
        23 => "Jedi 1st Degree",
        24 => "Jedi Master",
    ];

    public static $WARHEADS = [
        0 => "None",
        1 => "Space Bombs",
        2 => "Cluster Bombs",
        3 => "Heavy Rockets",
        4 => "Missiles",
        5 => "Proton Torpedoes",
        6 => "Advanced Missiles",
        7 => "Advanced Torpedoes",
        8 => "Mag Pulse",
        9 => "Ion Pulse",
    ];

    public static $BEAMWEAPONS = [
        0 => "None",
        1 => "Tractor",
        2 => "Jamming",
        3 => "Decoy",
        4 => "Energy",
    ];

    public static $COUNTERMEASURES = [
        0 => "None",
        1 => "Chaff",
        2 => "Flare",
        3 => "Cluster Mine",
    ];

    public static $BESTRATING = [
        0 => "Gold",
        1 => "Silver",
        2 => "Bronze",
        3 => "Nickel",
        4 => "Copper",
        5 => "Lead",
    ];

}