export class Constants {
  public static SHIPS = {
    0: "Unknown",
    1: "X-Wing",
    2: "Y-Wing",
    3: "A-Wing",
    4: "*B-Wing",
    5: "TIE Fighter",
    6: "TIE Interceptor",
    7: "TIE Bomber",
    8: "TIE Advanced",
    9: "*TIE Defender",
    10: "Patch Slot 10",
    11: "Patch Slot 11",
    12: "Missile Boat",
    13: "T-Wing",
    14: "Z-95 Headhunter",
    15: "R-41 Starchaser",
    16: "Assault Gunboat",
    17: "Shuttle",
    18: "Escort Shuttle",
    19: "System Patrol Craft",
    20: "*Scout Craft",
    21: "Stormtrooper Transport",
    22: "Assault Transport",
    23: "Escort Transport",
    24: "Utility Tug",
    25: "Combat Utility Vehicle",
    26: "Container Class A",
    27: "Container Class B",
    28: "Container Class C",
    29: "Container Class D",
    30: "Heavy Lifter",
    31: "*bulk_barge2",
    32: "Bulk Freighter",
    33: "Cargo Ferry",
    34: "Modular Conveyor",
    35: "Container Transport",
    36: "*new_freighter3",
    37: "Muurian Transport",
    38: "Corellian Transport",
    39: "*Millenium",
    40: "Corellian Corvette",
    41: "*Modified Corvette",
    42: "Nebulon B Frigate",
    43: "*Modified Frigate",
    44: "*Passenger Liner",
    45: "*Carrack Cruiser",
    46: "Strike Cruiser",
    47: "Escort Carrier",
    48: "Dreadnaught",
    49: "Calamari Cruiser",
    50: "Lt. Calamari Cruiser",
    51: "Interdictor",
    52: "Victory Star Destroyer",
    53: "Imperial Star Destroyer",
    54: "*super_sd",
    55: "Container Class E",
    56: "Container Class F",
    57: "Container Class G",
    58: "Container Class H",
    59: "Container Class I",
    60: "XQ1 Platform",
    61: "XQ2 Platform",
    62: "XQ3 Platform",
    63: "XQ4 Platform",
    64: "XQ5 Platform",
    65: "XQ6 Platform",
    66: "Asteroid Hangar",
    67: "Asteroid Laser Battery",
    68: "Asteroid War Launcher",
    69: "X7 Factory",
    70: "Comm Sat",
    71: "Comm Sat",
    72: "*Sat3",
    73: "*Sat4",
    74: "*Sat5",
    75: "Mine Type A",
    76: "Mine Type B",
    77: "Mine Type C",
    78: "*Mine4",
    79: "*Mine5",
    80: "Probe",
    81: "*Probe2",
    82: "*Probe3",
    83: "Nav Buoy",
    84: "Nav Buoy",
    85: "*Pilot",
    86: "Asteroid",
    87: "Planet",
    88: "Obstacle",
    89: "Unused",
    90: "Shipyard",
    91: "Repair Yard",
    92: "Modified Strike Cruiser",
  };

  public static PILOTRATING = {
    0: "Target Drone",
    1: "Ground Crew",
    2: "Trainee",
    3: "Flight Cadet",
    4: "Officer 4th Class",
    5: "Officer 3rd Class",
    6: "Officer 2nd Class",
    7: "Officer 1st Class",
    8: "Veteran 4th Grade",
    9: "Veteran 3rd Grade",
    10: "Veteran 2nd Grade",
    11: "Veteran 1st Grade",
    12: "Ace 4th Level",
    13: "Ace 3rd Level",
    14: "Ace 2nd Level",
    15: "Ace 1st Level",
    16: "Top Ace 4th Order",
    17: "Top Ace 3rd Order",
    18: "Top Ace 2nd Order",
    19: "Top Ace 1st Order",
    20: "Jedi 4th Degree",
    21: "Jedi 3rd Degree",
    22: "Jedi 2nd Degree",
    23: "Jedi 1st Degree",
    24: "Jedi Master",
  };

  public static WARHEADS = {
    0: "None",
    1: "Space Bombs",
    2: "Cluster Bombs",
    3: "Heavy Rockets",
    4: "Missiles",
    5: "Proton Torpedoes",
    6: "Advanced Missiles",
    7: "Advanced Torpedoes",
    8: "Mag Pulse",
    9: "Ion Pulse",
  };

  public static BEAMWEAPONS = {
    0: "None",
    1: "Tractor",
    2: "Jamming",
    3: "Decoy",
    4: "Energy",
  };

  public static COUNTERMEASURES = {
    0: "None",
    1: "Chaff",
    2: "Flare",
    3: "Cluster Mine",
  };

  public static BESTRATING = {
    0: "Gold",
    1: "Silver",
    2: "Bronze",
    3: "Nickel",
    4: "Copper",
    5: "Lead",
  };

}

export enum Ships {
  unknown = 0,
  xWing = 1,
  yWing = 2,
  aWing = 3,
  bWing = 4,
  tieFighter = 5,
  tieInterceptor = 6,
  tieBomber = 7,
  tieAdvanced = 8,
  tieDefender = 9,
  patchSlot10 = 10,
  patchSlot11 = 11,
  missileBoat = 12,
  tWing = 13,
  z95Headhunter = 14,
  r41Starchaser = 15,
  assaultGunboat = 16,
  shuttle = 17,
  escortShuttle = 18,
  systemPatrolCraft = 19,
  scoutCraft = 20,
  stormtrooperTransport = 21,
  assaultTransport = 22,
  escortTransport = 23,
  utilityTug = 24,
  combatUtilityVehicle = 25,
  containerClassA = 26,
  containerClassB = 27,
  containerClassC = 28,
  containerClassD = 29,
  heavyLifter = 30,
  bulkBarge2 = 31,
  bulkFreighter = 32,
  cargoFerry = 33,
  modularConveyor = 34,
  containerTransport = 35,
  newFreighter3 = 36,
  muurianTransport = 37,
  corellianTransport = 38,
  millenium = 39,
  corellianCorvette = 40,
  modifiedCorvette = 41,
  nebulonBFrigate = 42,
  modifiedFrigate = 43,
  passengerLiner = 44,
  carrackCruiser = 45,
  strikeCruiser = 46,
  escortCarrier = 47,
  dreadnaught = 48,
  calamariCruiser = 49,
  ltCalamariCruiser = 50,
  interdictor = 51,
  victoryStarDestroyer = 52,
  imperialStarDestroyer = 53,
  superSd = 54,
  containerClassE = 55,
  containerClassF = 56,
  containerClassG = 57,
  containerClassH = 58,
  containerClassI = 59,
  xq1Platform = 60,
  xq2Platform = 61,
  xq3Platform = 62,
  xq4Platform = 63,
  xq5Platform = 64,
  xq6Platform = 65,
  asteroidHangar = 66,
  asteroidLaserBattery = 67,
  asteroidWarLauncher = 68,
  x7Factory = 69,
  commSat = 70,
  // duplicate commSat = 71,
  sat3 = 72,
  sat4 = 73,
  sat5 = 74,
  mineTypeA = 75,
  mineTypeB = 76,
  mineTypeC = 77,
  mine4 = 78,
  mine5 = 79,
  probe = 80,
  probe2 = 81,
  probe3 = 82,
  navBuoy = 83,
  // duplicate navBuoy = 84,
  pilot = 85,
  asteroid = 86,
  planet = 87,
  obstacle = 88,
  unused = 89,
  shipyard = 90,
  repairYard = 91,
  modifiedStrikeCruiser = 92,
}

export enum PilotRating {
  targetDrone = 0,
  groundCrew = 1,
  trainee = 2,
  flightCadet = 3,
  officer4thClass = 4,
  officer3rdClass = 5,
  officer2ndClass = 6,
  officer1stClass = 7,
  veteran4thGrade = 8,
  veteran3rdGrade = 9,
  veteran2ndGrade = 10,
  veteran1stGrade = 11,
  ace4thLevel = 12,
  ace3rdLevel = 13,
  ace2ndLevel = 14,
  ace1stLevel = 15,
  topAce4thOrder = 16,
  topAce3rdOrder = 17,
  topAce2ndOrder = 18,
  topAce1stOrder = 19,
  jedi4thDegree = 20,
  jedi3rdDegree = 21,
  jedi2ndDegree = 22,
  jedi1stDegree = 23,
  jediMaster = 24,
}

export enum Warheads {
  none = 0,
  spaceBombs = 1,
  clusterBombs = 2,
  heavyRockets = 3,
  missiles = 4,
  protonTorpedoes = 5,
  advancedMissiles = 6,
  advancedTorpedoes = 7,
  magPulse = 8,
  ionPulse = 9,
}

export enum BeamWeapons {
  none = 0,
  tractor = 1,
  jamming = 2,
  decoy = 3,
  energy = 4,
}

export enum Countermeasures {
  none = 0,
  chaff = 1,
  flare = 2,
  clusterMine = 3,
}

export enum BestRating {
  gold = 0,
  silver = 1,
  bronze = 2,
  nickel = 3,
  copper = 4,
  lead = 5,
}
