import { ControllerBase } from "../../controller-base";
import { FlightGroup } from "../../model/XW";

export class XWFlightGroupController extends ControllerBase {
  public readonly fields: object = {"Name":{"name":"Name","type":"STR"},"Cargo":{"name":"Cargo","type":"STR"},"SpecialCargo":{"name":"SpecialCargo","type":"STR"},"SpecialCargoCraft":{"name":"SpecialCargoCraft","type":"SHORT"},"CraftType":{"name":"CraftType","type":"SHORT","options":"Constants.CRAFTTYPE"},"IFF":{"name":"IFF","type":"SHORT","options":"Constants.IFF"},"FlightGroupStatus":{"name":"FlightGroupStatus","type":"SHORT","options":"Constants.FLIGHTGROUPSTATUS"},"NumberOfCraft":{"name":"NumberOfCraft","type":"SHORT"},"NumberOfWaves":{"name":"NumberOfWaves","type":"SHORT"},"ArrivalEvent":{"name":"ArrivalEvent","type":"SHORT","options":"Constants.ARRIVALEVENT"},"ArrivalDelay":{"name":"ArrivalDelay","type":"SHORT"},"ArrivalFlightGroup":{"name":"ArrivalFlightGroup","type":"SHORT"},"MothershipFlightGroup":{"name":"MothershipFlightGroup","type":"SHORT"},"ArriveByHyperspace":{"name":"ArriveByHyperspace","type":"SHORT"},"DepartByHyperspace":{"name":"DepartByHyperspace","type":"SHORT"},"XCoordinates":{"name":"XCoordinates","type":"SHORT"},"YCoordinates":{"name":"YCoordinates","type":"SHORT"},"ZCoordinates":{"name":"ZCoordinates","type":"SHORT"},"CoordinatesEnabled":{"name":"CoordinatesEnabled","type":"SHORT"},"Formation":{"name":"Formation","type":"SHORT","options":"Constants.FORMATION"},"PlayerCraft":{"name":"PlayerCraft","type":"SHORT"},"CraftAI":{"name":"CraftAI","type":"SHORT","options":"Constants.CRAFTAI"},"Order":{"name":"Order","type":"SHORT","options":"Constants.ORDER"},"OrderVariable":{"name":"OrderVariable","type":"SHORT"},"CraftColour":{"name":"CraftColour","type":"SHORT","options":"Constants.CRAFTCOLOUR"},"Reserved":{"name":"Reserved","type":"SHORT"},"CraftObjective":{"name":"CraftObjective","type":"SHORT","options":"Constants.CRAFTOBJECTIVE"},"PrimaryTarget":{"name":"PrimaryTarget","type":"SHORT"},"SecondaryTarget":{"name":"SecondaryTarget","type":"SHORT"}};

  constructor(public model: FlightGroup){
    super(model);
  }
}