import { ControllerBase } from "../../controller-base";
import { PilotFile } from "../../model/XW";

export class XWPilotFileController extends ControllerBase {
  public readonly fields: object = {"PlatformID":{"name":"PlatformID","type":"SHORT"},"PilotStatus":{"name":"PilotStatus","type":"BYTE","options":"Constants.PILOTSTATUS"},"PilotRank":{"name":"PilotRank","type":"BYTE","options":"Constants.PILOTRANK"},"TotalTODScore":{"name":"TotalTODScore","type":"INT"},"RookieNumber":{"name":"RookieNumber","type":"SHORT"},"TODMedals":{"name":"TODMedals","type":"BOOL"},"KalidorCrescent":{"name":"KalidorCrescent","type":"BYTE","options":"Constants.KALIDORCRESCENT"},"MazeScore":{"name":"MazeScore","type":"INT"},"MazeLevel":{"name":"MazeLevel","type":"BYTE"},"XWingHistoricalScore":{"name":"XWingHistoricalScore","type":"INT"},"YWingHistoricalScore":{"name":"YWingHistoricalScore","type":"INT"},"AWingHistoricalScore":{"name":"AWingHistoricalScore","type":"INT"},"BWingHistoricalScore":{"name":"BWingHistoricalScore","type":"INT"},"BonusHistoricalScore":{"name":"BonusHistoricalScore","type":"INT"},"XWingHistoricalComplete":{"name":"XWingHistoricalComplete","type":"BOOL"},"YWingHistoricalComplete":{"name":"YWingHistoricalComplete","type":"BOOL"},"AWingHistoricalComplete":{"name":"AWingHistoricalComplete","type":"BOOL"},"BWingHistoricalComplete":{"name":"BWingHistoricalComplete","type":"BOOL"},"BonusHistoricalComplete":{"name":"BonusHistoricalComplete","type":"BOOL"},"TourStatus":{"name":"TourStatus","type":"BYTE"},"TourOperationsComplete":{"name":"TourOperationsComplete","type":"BYTE"},"Tour1Scores":{"name":"Tour1Scores","type":"INT"},"Tour2Scores":{"name":"Tour2Scores","type":"INT"},"Tour3Scores":{"name":"Tour3Scores","type":"INT"},"Tour4Scores":{"name":"Tour4Scores","type":"INT"},"Tour5Scores":{"name":"Tour5Scores","type":"INT"},"SurfaceVictories":{"name":"SurfaceVictories","type":"SHORT"},"TODKills":{"name":"TODKills","type":"SHORT"},"TODCaptures":{"name":"TODCaptures","type":"SHORT"},"LasersFired":{"name":"LasersFired","type":"INT"},"LaserCraftHits":{"name":"LaserCraftHits","type":"INT"},"LaserGroundHits":{"name":"LaserGroundHits","type":"INT"},"MissilesFired":{"name":"MissilesFired","type":"SHORT"},"MissileCraftHits":{"name":"MissileCraftHits","type":"SHORT"},"MissileGroundHits":{"name":"MissileGroundHits","type":"SHORT"},"CraftLost":{"name":"CraftLost","type":"SHORT"}};

  constructor(public model: PilotFile){
    super(model);
  }
}