<?php
namespace Pyrite\XWA;

class Constants
{
    public static $CRAFTTYPE = [
        1 => "X-wing",
        2 => "Y-wing",
        3 => "A-wing",
        4 => "B-wing",
        5 => "TIE Fighter",
        6 => "TIE Interceptor",
        7 => "TIE Bomber",
        8 => "TIE Advanced",
        9 => "TIE Defender",
        10 => "IRD Fighter",
        11 => "Toscan Fighter",
        12 => "Missile Boat",
        13 => "T-wing",
        14 => "Z-95 Headhunter",
        15 => "R-41 Starchaser",
        16 => "Assault Gunboat",
        17 => "Shuttle",
        18 => "Escort Shuttle",
        19 => "System Patrol Craft",
        20 => "*Scout Craft",
        21 => "Stormtrooper Transport",
        22 => "Assault Transport",
        23 => "Escort Transport",
        24 => "Tug",
        25 => "Combat Utility Vehicle",
        26 => "Container A",
        27 => "Container B",
        28 => "Container C",
        29 => "Container D",
        30 => "Heavy Lifter",
        31 => "Mole Miner",
        32 => "Bulk Freighter",
        33 => "Cargo Ferry",
        34 => "Modular Conveyor",
        35 => "*Container Transport",
        36 => "Medium Transport",
        37 => "Murrian Transport",
        38 => "Corellian Transport",
        39 => "Millenium Falcon",
        40 => "Corellian Corvette",
        41 => "Modified Corvette",
        42 => "Nebulon-B Frigate",
        43 => "Modified Frigate",
        44 => "*C-3 Passenger Liner",
        45 => "*Carrack Cruiser",
        46 => "Strike Cruiser",
        47 => "Escort Carrier",
        48 => "Dreadnaught",
        49 => "MC80a Cruiser",
        50 => "MC40a Light Cruiser",
        51 => "Interdictor Cruiser",
        52 => "Victory-class Star Destroyer",
        53 => "Imperator-class Star Destroyer",
        54 => "Executor-class Star Destroyer",
        55 => "Container E",
        56 => "Container F",
        57 => "Container G",
        58 => "Container H",
        59 => "Container I",
        60 => "Platform A",
        61 => "Platform B",
        62 => "Platform C",
        63 => "Platform D",
        64 => "Platform E",
        65 => "Platform F",
        66 => "Asteroid R&D Station",
        67 => "Asteroid Laser Battery",
        68 => "Asteroid Warhead Battery",
        69 => "X/7 Factory",
        70 => "Satellite 1",
        71 => "Satellite 2",
        72 => "Satellite 3",
        73 => "*Satellite 4",
        74 => "*Satellite 5",
        75 => "Mine A",
        76 => "Mine B",
        77 => "Mine C",
        78 => "Gun Emplacement",
        79 => "*Mine 5",
        80 => "Probe A",
        81 => "Probe B",
        82 => "*Probe 3",
        83 => "Nav Buoy A",
        84 => "Nav Buoy B",
        85 => "Hyper Buoy",
        86 => "Asteroid Field",
        87 => "Planet",
        88 => "Rendezvous Buoy",
        89 => "Cargo Canister",
        90 => "Shipyard",
        91 => "Repair Yard",
        92 => "*Modified Strike Cruiser",
        93 => "Lancer Frigate",
        94 => "Bulk Cruiser",
        95 => "Assault Frigate",
        96 => "Corellian Gunship",
        97 => "Imperial Landing Craft",
        98 => "Assault Shuttle",
        99 => "Marauder Corvette",
        100 => "Star Galleon",
        101 => "Imperial Research Ship",
        102 => "Luxury Yacht 3000",
        103 => "Ferryboat Liner",
        104 => "Modified Action Transport",
        105 => "Mobquet Transport",
        106 => "Xiytiar Transport",
        107 => "Freight Transport/C",
        108 => "Freight Transport/H",
        109 => "Freight Transport/K",
        110 => "YT-2000",
        111 => "YT-2400",
        112 => "Suprosa",
        113 => "Skipray Blastboat",
        114 => "T/e m1",
        115 => "T/e m2",
        116 => "T/e m3",
        117 => "T/e m4",
        118 => "T/e m5",
        119 => "Cloakshape Fighter",
        120 => "Razor Fighter",
        121 => "Planetary Fighter",
        122 => "Supa Fighter",
        123 => "Pinook Fighter",
        124 => "*Booster Pack",
        125 => "Preybird Fighter",
        126 => "*StarViper",
        127 => "Firespray",
        128 => "Pursuer",
        129 => "Golan 1",
        130 => "Golan 2",
        131 => "Golan 3",
        132 => "Derilyn Platform",
        133 => "Sensor Array",
        134 => "Comm Relay",
        135 => "Space Colony 1",
        136 => "Space Colony 2",
        137 => "Space Colony 3",
        138 => "Casino",
        139 => "Cargo Facility 1",
        140 => "Cargo Facility 2",
        141 => "Asteroid Mining Plant",
        142 => "Processing Plant",
        143 => "Rebel Platform",
        144 => "Imperial Research Center",
        145 => "Family Base",
        146 => "Family Repair Yard",
        147 => "Pirate Shipyard",
        148 => "Industrical Complex",
        149 => "*Pirate Junkyard Base",
        150 => "Escape Pod 1",
        151 => "Pressure Tank",
        152 => "Container J",
        153 => "Container K",
        154 => "Container L",
        155 => "Container Hangar",
        156 => "Large Gun Emplacement",
        157 => "Large Gun/Warhead Emplacement",
        158 => "Proximity Mine A",
        159 => "Proximity Mine B",
        160 => "*Homing Mine A",
        161 => "Homing Mine B",
        162 => "New Laser Battery",
        163 => "New Ion Battery",
        164 => "Cargo Freighter",
        165 => "*Cargo Freighter 2",
        166 => "*Cargo Freighter 3",
        167 => "*Cargo Freighter 4",
        168 => "*Cargo Freighter 5",
        169 => "Cargo Tanker",
        170 => "*Cargo Tanker 2",
        171 => "*Cargo Tanker 3",
        172 => "*Cargo Tanker 4",
        173 => "*Cargo Tanker 5",
        174 => "Escape Pod 2",
        175 => "*Rebel Pilot",
        176 => "*Imperial Pilot",
        177 => "*Civilian Pilot",
        178 => "Spacetrooper",
        179 => "Zero-G Utility Suit",
        180 => "Emkay",
        181 => "Astromech",
        182 => "Worker droid",
        183 => "Backdrop",
        184 => "*Forest Moon of Endor",
        185 => "*Endor",
        186 => "*Sullust",
        187 => "*Bothuwai",
        188 => "*Kothlis",
        189 => "*Hoth",
        190 => "*DeathStar II backdrop",
        191 => "*Nar Shadda",
        192 => "*Planet",
        197 => "*Planet",
        198 => "*Moon",
        202 => "*Moon",
        203 => "*Sun",
        212 => "*Sun",
        213 => "*Backdrop",
        226 => "*Backdrop",
        227 => "Death Star II",
        228 => "MC80 Liberty-class Cruiser",
        229 => "Victory-class Star Destroyer II",
        230 => "Imperator-class Star Destroyer II",
        231 => "*Planet",
    ];

    public static $CRAFTTYPE_XWING = 1;
    public static $CRAFTTYPE_YWING = 2;
    public static $CRAFTTYPE_AWING = 3;
    public static $CRAFTTYPE_BWING = 4;
    public static $CRAFTTYPE_TIEFIGHTER = 5;
    public static $CRAFTTYPE_TIEINTERCEPTOR = 6;
    public static $CRAFTTYPE_TIEBOMBER = 7;
    public static $CRAFTTYPE_TIEADVANCED = 8;
    public static $CRAFTTYPE_TIEDEFENDER = 9;
    public static $CRAFTTYPE_IRDFIGHTER = 10;
    public static $CRAFTTYPE_TOSCANFIGHTER = 11;
    public static $CRAFTTYPE_MISSILEBOAT = 12;
    public static $CRAFTTYPE_TWING = 13;
    public static $CRAFTTYPE_Z95HEADHUNTER = 14;
    public static $CRAFTTYPE_R41STARCHASER = 15;
    public static $CRAFTTYPE_ASSAULTGUNBOAT = 16;
    public static $CRAFTTYPE_SHUTTLE = 17;
    public static $CRAFTTYPE_ESCORTSHUTTLE = 18;
    public static $CRAFTTYPE_SYSTEMPATROLCRAFT = 19;
    public static $CRAFTTYPE_SCOUTCRAFT = 20;
    public static $CRAFTTYPE_STORMTROOPERTRANSPORT = 21;
    public static $CRAFTTYPE_ASSAULTTRANSPORT = 22;
    public static $CRAFTTYPE_ESCORTTRANSPORT = 23;
    public static $CRAFTTYPE_TUG = 24;
    public static $CRAFTTYPE_COMBATUTILITYVEHICLE = 25;
    public static $CRAFTTYPE_CONTAINERA = 26;
    public static $CRAFTTYPE_CONTAINERB = 27;
    public static $CRAFTTYPE_CONTAINERC = 28;
    public static $CRAFTTYPE_CONTAINERD = 29;
    public static $CRAFTTYPE_HEAVYLIFTER = 30;
    public static $CRAFTTYPE_MOLEMINER = 31;
    public static $CRAFTTYPE_BULKFREIGHTER = 32;
    public static $CRAFTTYPE_CARGOFERRY = 33;
    public static $CRAFTTYPE_MODULARCONVEYOR = 34;
    public static $CRAFTTYPE_CONTAINERTRANSPORT = 35;
    public static $CRAFTTYPE_MEDIUMTRANSPORT = 36;
    public static $CRAFTTYPE_MURRIANTRANSPORT = 37;
    public static $CRAFTTYPE_CORELLIANTRANSPORT = 38;
    public static $CRAFTTYPE_MILLENIUMFALCON = 39;
    public static $CRAFTTYPE_CORELLIANCORVETTE = 40;
    public static $CRAFTTYPE_MODIFIEDCORVETTE = 41;
    public static $CRAFTTYPE_NEBULONBFRIGATE = 42;
    public static $CRAFTTYPE_MODIFIEDFRIGATE = 43;
    public static $CRAFTTYPE_C3PASSENGERLINER = 44;
    public static $CRAFTTYPE_CARRACKCRUISER = 45;
    public static $CRAFTTYPE_STRIKECRUISER = 46;
    public static $CRAFTTYPE_ESCORTCARRIER = 47;
    public static $CRAFTTYPE_DREADNAUGHT = 48;
    public static $CRAFTTYPE_MC80ACRUISER = 49;
    public static $CRAFTTYPE_MC40ALIGHTCRUISER = 50;
    public static $CRAFTTYPE_INTERDICTORCRUISER = 51;
    public static $CRAFTTYPE_VICTORYCLASSSTARDESTROYER = 52;
    public static $CRAFTTYPE_IMPERATORCLASSSTARDESTROYER = 53;
    public static $CRAFTTYPE_EXECUTORCLASSSTARDESTROYER = 54;
    public static $CRAFTTYPE_CONTAINERE = 55;
    public static $CRAFTTYPE_CONTAINERF = 56;
    public static $CRAFTTYPE_CONTAINERG = 57;
    public static $CRAFTTYPE_CONTAINERH = 58;
    public static $CRAFTTYPE_CONTAINERI = 59;
    public static $CRAFTTYPE_PLATFORMA = 60;
    public static $CRAFTTYPE_PLATFORMB = 61;
    public static $CRAFTTYPE_PLATFORMC = 62;
    public static $CRAFTTYPE_PLATFORMD = 63;
    public static $CRAFTTYPE_PLATFORME = 64;
    public static $CRAFTTYPE_PLATFORMF = 65;
    public static $CRAFTTYPE_ASTEROIDRNDSTATION = 66;
    public static $CRAFTTYPE_ASTEROIDLASERBATTERY = 67;
    public static $CRAFTTYPE_ASTEROIDWARHEADBATTERY = 68;
    public static $CRAFTTYPE_X7FACTORY = 69;
    public static $CRAFTTYPE_SATELLITE1 = 70;
    public static $CRAFTTYPE_SATELLITE2 = 71;
    public static $CRAFTTYPE_SATELLITE3 = 72;
    public static $CRAFTTYPE_SATELLITE4 = 73;
    public static $CRAFTTYPE_SATELLITE5 = 74;
    public static $CRAFTTYPE_MINEA = 75;
    public static $CRAFTTYPE_MINEB = 76;
    public static $CRAFTTYPE_MINEC = 77;
    public static $CRAFTTYPE_GUNEMPLACEMENT = 78;
    public static $CRAFTTYPE_MINE5 = 79;
    public static $CRAFTTYPE_PROBEA = 80;
    public static $CRAFTTYPE_PROBEB = 81;
    public static $CRAFTTYPE_PROBE3 = 82;
    public static $CRAFTTYPE_NAVBUOYA = 83;
    public static $CRAFTTYPE_NAVBUOYB = 84;
    public static $CRAFTTYPE_HYPERBUOY = 85;
    public static $CRAFTTYPE_ASTEROIDFIELD = 86;
    public static $CRAFTTYPE_PLANET = 87;
    public static $CRAFTTYPE_RENDEZVOUSBUOY = 88;
    public static $CRAFTTYPE_CARGOCANISTER = 89;
    public static $CRAFTTYPE_SHIPYARD = 90;
    public static $CRAFTTYPE_REPAIRYARD = 91;
    public static $CRAFTTYPE_MODIFIEDSTRIKECRUISER = 92;
    public static $CRAFTTYPE_LANCERFRIGATE = 93;
    public static $CRAFTTYPE_BULKCRUISER = 94;
    public static $CRAFTTYPE_ASSAULTFRIGATE = 95;
    public static $CRAFTTYPE_CORELLIANGUNSHIP = 96;
    public static $CRAFTTYPE_IMPERIALLANDINGCRAFT = 97;
    public static $CRAFTTYPE_ASSAULTSHUTTLE = 98;
    public static $CRAFTTYPE_MARAUDERCORVETTE = 99;
    public static $CRAFTTYPE_STARGALLEON = 100;
    public static $CRAFTTYPE_IMPERIALRESEARCHSHIP = 101;
    public static $CRAFTTYPE_LUXURYYACHT3000 = 102;
    public static $CRAFTTYPE_FERRYBOATLINER = 103;
    public static $CRAFTTYPE_MODIFIEDACTIONTRANSPORT = 104;
    public static $CRAFTTYPE_MOBQUETTRANSPORT = 105;
    public static $CRAFTTYPE_XIYTIARTRANSPORT = 106;
    public static $CRAFTTYPE_FREIGHTTRANSPORTC = 107;
    public static $CRAFTTYPE_FREIGHTTRANSPORTH = 108;
    public static $CRAFTTYPE_FREIGHTTRANSPORTK = 109;
    public static $CRAFTTYPE_YT2000 = 110;
    public static $CRAFTTYPE_YT2400 = 111;
    public static $CRAFTTYPE_SUPROSA = 112;
    public static $CRAFTTYPE_SKIPRAYBLASTBOAT = 113;
    public static $CRAFTTYPE_TEM1 = 114;
    public static $CRAFTTYPE_TEM2 = 115;
    public static $CRAFTTYPE_TEM3 = 116;
    public static $CRAFTTYPE_TEM4 = 117;
    public static $CRAFTTYPE_TEM5 = 118;
    public static $CRAFTTYPE_CLOAKSHAPEFIGHTER = 119;
    public static $CRAFTTYPE_RAZORFIGHTER = 120;
    public static $CRAFTTYPE_PLANETARYFIGHTER = 121;
    public static $CRAFTTYPE_SUPAFIGHTER = 122;
    public static $CRAFTTYPE_PINOOKFIGHTER = 123;
    public static $CRAFTTYPE_BOOSTERPACK = 124;
    public static $CRAFTTYPE_PREYBIRDFIGHTER = 125;
    public static $CRAFTTYPE_STARVIPER = 126;
    public static $CRAFTTYPE_FIRESPRAY = 127;
    public static $CRAFTTYPE_PURSUER = 128;
    public static $CRAFTTYPE_GOLAN1 = 129;
    public static $CRAFTTYPE_GOLAN2 = 130;
    public static $CRAFTTYPE_GOLAN3 = 131;
    public static $CRAFTTYPE_DERILYNPLATFORM = 132;
    public static $CRAFTTYPE_SENSORARRAY = 133;
    public static $CRAFTTYPE_COMMRELAY = 134;
    public static $CRAFTTYPE_SPACECOLONY1 = 135;
    public static $CRAFTTYPE_SPACECOLONY2 = 136;
    public static $CRAFTTYPE_SPACECOLONY3 = 137;
    public static $CRAFTTYPE_CASINO = 138;
    public static $CRAFTTYPE_CARGOFACILITY1 = 139;
    public static $CRAFTTYPE_CARGOFACILITY2 = 140;
    public static $CRAFTTYPE_ASTEROIDMININGPLANT = 141;
    public static $CRAFTTYPE_PROCESSINGPLANT = 142;
    public static $CRAFTTYPE_REBELPLATFORM = 143;
    public static $CRAFTTYPE_IMPERIALRESEARCHCENTER = 144;
    public static $CRAFTTYPE_FAMILYBASE = 145;
    public static $CRAFTTYPE_FAMILYREPAIRYARD = 146;
    public static $CRAFTTYPE_PIRATESHIPYARD = 147;
    public static $CRAFTTYPE_INDUSTRICALCOMPLEX = 148;
    public static $CRAFTTYPE_PIRATEJUNKYARDBASE = 149;
    public static $CRAFTTYPE_ESCAPEPOD1 = 150;
    public static $CRAFTTYPE_PRESSURETANK = 151;
    public static $CRAFTTYPE_CONTAINERJ = 152;
    public static $CRAFTTYPE_CONTAINERK = 153;
    public static $CRAFTTYPE_CONTAINERL = 154;
    public static $CRAFTTYPE_CONTAINERHANGAR = 155;
    public static $CRAFTTYPE_LARGEGUNEMPLACEMENT = 156;
    public static $CRAFTTYPE_LARGEGUNWARHEADEMPLACEMENT = 157;
    public static $CRAFTTYPE_PROXIMITYMINEA = 158;
    public static $CRAFTTYPE_PROXIMITYMINEB = 159;
    public static $CRAFTTYPE_HOMINGMINEA = 160;
    public static $CRAFTTYPE_HOMINGMINEB = 161;
    public static $CRAFTTYPE_NEWLASERBATTERY = 162;
    public static $CRAFTTYPE_NEWIONBATTERY = 163;
    public static $CRAFTTYPE_CARGOFREIGHTER = 164;
    public static $CRAFTTYPE_CARGOFREIGHTER2 = 165;
    public static $CRAFTTYPE_CARGOFREIGHTER3 = 166;
    public static $CRAFTTYPE_CARGOFREIGHTER4 = 167;
    public static $CRAFTTYPE_CARGOFREIGHTER5 = 168;
    public static $CRAFTTYPE_CARGOTANKER = 169;
    public static $CRAFTTYPE_CARGOTANKER2 = 170;
    public static $CRAFTTYPE_CARGOTANKER3 = 171;
    public static $CRAFTTYPE_CARGOTANKER4 = 172;
    public static $CRAFTTYPE_CARGOTANKER5 = 173;
    public static $CRAFTTYPE_ESCAPEPOD2 = 174;
    public static $CRAFTTYPE_REBELPILOT = 175;
    public static $CRAFTTYPE_IMPERIALPILOT = 176;
    public static $CRAFTTYPE_CIVILIANPILOT = 177;
    public static $CRAFTTYPE_SPACETROOPER = 178;
    public static $CRAFTTYPE_ZEROGUTILITYSUIT = 179;
    public static $CRAFTTYPE_EMKAY = 180;
    public static $CRAFTTYPE_ASTROMECH = 181;
    public static $CRAFTTYPE_WORKERDROID = 182;
    public static $CRAFTTYPE_BACKDROP = 183;
    public static $CRAFTTYPE_FORESTMOONOFENDOR = 184;
    public static $CRAFTTYPE_ENDOR = 185;
    public static $CRAFTTYPE_SULLUST = 186;
    public static $CRAFTTYPE_BOTHUWAI = 187;
    public static $CRAFTTYPE_KOTHLIS = 188;
    public static $CRAFTTYPE_HOTH = 189;
    public static $CRAFTTYPE_DEATHSTARIIBACKDROP = 190;
    public static $CRAFTTYPE_NARSHADDA = 191;
    public static $CRAFTTYPE_PLANET2 = 192;
    public static $CRAFTTYPE_PLANET3 = 197;
    public static $CRAFTTYPE_MOON = 198;
    public static $CRAFTTYPE_MOON2 = 202;
    public static $CRAFTTYPE_SUN = 203;
    public static $CRAFTTYPE_SUN2 = 212;
    public static $CRAFTTYPE_BACKDROP2 = 213;
    public static $CRAFTTYPE_BACKDROP3 = 226;
    public static $CRAFTTYPE_DEATHSTARII = 227;
    public static $CRAFTTYPE_MC80LIBERTYCLASSCRUISER = 228;
    public static $CRAFTTYPE_VICTORYCLASSSTARDESTROYERII = 229;
    public static $CRAFTTYPE_IMPERATORCLASSSTARDESTROYERII = 230;
    public static $CRAFTTYPE_PLANET4 = 231;

    public static $CRAFTABBR = [
        1 => "X-W",
        2 => "Y-W",
        3 => "A-W",
        4 => "B-W",
        5 => "T/F",
        6 => "T/I",
        7 => "T/B",
        8 => "T/A",
        9 => "T/D",
        10 => "IRD",
        11 => "TOS",
        12 => "MIS",
        13 => "T-W",
        14 => "Z-95",
        15 => "R-41",
        16 => "GUN",
        17 => "SHU",
        18 => "E/S",
        19 => "SPC",
        20 => "SCT",
        21 => "TRN",
        22 => "ATR",
        23 => "ETR",
        24 => "TUG",
        25 => "CUV",
        26 => "CN/A",
        27 => "CN/B",
        28 => "CN/C",
        29 => "CN/D",
        30 => "HLF",
        31 => "Mole Miner",
        32 => "FRT",
        33 => "CARG",
        34 => "CNVYR",
        35 => "CTRNS",
        36 => "MED",
        37 => "MUR",
        38 => "CORT",
        39 => "FALC",
        40 => "CRV",
        41 => "M/CRV",
        42 => "FRG",
        43 => "M/FRG",
        44 => "LINER",
        45 => "CRCK",
        46 => "STRKC",
        47 => "ESC",
        48 => "DRD",
        49 => "CRS",
        50 => "CRL",
        51 => "INT",
        52 => "VSD",
        53 => "ISD",
        54 => "SSD",
        55 => "CN/E",
        56 => "CN/F",
        57 => "CN/G",
        58 => "CN/H",
        59 => "CN/I",
        60 => "PLT/A",
        61 => "PLT/B",
        62 => "PLT/C",
        63 => "PLT/D",
        64 => "PLT/E",
        65 => "PLT/F",
        66 => "Asteroid R&D Station",
        67 => "Asteroid Laser Battery",
        68 => "Asteroid Warhead Battery",
        69 => "X/7 Factory",
        70 => "Satellite 1",
        71 => "Satellite 2",
        72 => "Satellite 3",
        73 => "*Satellite 4",
        74 => "*Satellite 5",
        75 => "Mine A",
        76 => "Mine B",
        77 => "Mine C",
        78 => "Gun Emplacement",
        79 => "*Mine 5",
        80 => "Probe A",
        81 => "Probe B",
        82 => "*Probe 3",
        83 => "Nav Buoy A",
        84 => "Nav Buoy B",
        85 => "Hyper Buoy",
        86 => "Asteroid Field",
        87 => "Planet",
        88 => "Rendezvous Buoy",
        89 => "Cargo Canister",
        90 => "Shipyard",
        91 => "Repair Yard",
        92 => "*Modified Strike Cruiser",
        93 => "Lancer Frigate",
        94 => "Bulk Cruiser",
        95 => "Assault Frigate",
        96 => "Corellian Gunship",
        97 => "Imperial Landing Craft",
        98 => "Assault Shuttle",
        99 => "Marauder Corvette",
        100 => "Star Galleon",
        101 => "Imperial Research Ship",
        102 => "Luxury Yacht 3000",
        103 => "Ferryboat Liner",
        104 => "Modified Action Transport",
        105 => "Mobquet Transport",
        106 => "Xiytiar Transport",
        107 => "Freight Transport/C",
        108 => "Freight Transport/H",
        109 => "Freight Transport/K",
        110 => "YT-2000",
        111 => "YT-2400",
        112 => "Suprosa",
        113 => "Skipray Blastboat",
        114 => "T/e m1",
        115 => "T/e m2",
        116 => "T/e m3",
        117 => "T/e m4",
        118 => "T/e m5",
        119 => "Cloakshape Fighter",
        120 => "Razor Fighter",
        121 => "Planetary Fighter",
        122 => "Supa Fighter",
        123 => "Pinook Fighter",
        124 => "*Booster Pack",
        125 => "Preybird Fighter",
        126 => "*StarViper",
        127 => "Firespray",
        128 => "Pursuer",
        129 => "Golan 1",
        130 => "Golan 2",
        131 => "Golan 3",
        132 => "Derilyn Platform",
        133 => "Sensor Array",
        134 => "Comm Relay",
        135 => "Space Colony 1",
        136 => "Space Colony 2",
        137 => "Space Colony 3",
        138 => "Casino",
        139 => "Cargo Facility 1",
        140 => "Cargo Facility 2",
        141 => "Asteroid Mining Plant",
        142 => "Processing Plant",
        143 => "Rebel Platform",
        144 => "Imperial Research Center",
        145 => "Family Base",
        146 => "Family Repair Yard",
        147 => "Pirate Shipyard",
        148 => "Industrical Complex",
        149 => "*Pirate Junkyard Base",
        150 => "Escape Pod 1",
        151 => "Pressure Tank",
        152 => "Container J",
        153 => "Container K",
        154 => "Container L",
        155 => "Container Hangar",
        156 => "Large Gun Emplacement",
        157 => "Large Gun/Warhead Emplacement",
        158 => "Proximity Mine A",
        159 => "Proximity Mine B",
        160 => "*Homing Mine A",
        161 => "Homing Mine B",
        162 => "New Laser Battery",
        163 => "New Ion Battery",
        164 => "Cargo Freighter",
        165 => "*Cargo Freighter 2",
        166 => "*Cargo Freighter 3",
        167 => "*Cargo Freighter 4",
        168 => "*Cargo Freighter 5",
        169 => "Cargo Tanker",
        170 => "*Cargo Tanker 2",
        171 => "*Cargo Tanker 3",
        172 => "*Cargo Tanker 4",
        173 => "*Cargo Tanker 5",
        174 => "Escape Pod 2",
        175 => "*Rebel Pilot",
        176 => "*Imperial Pilot",
        177 => "*Civilian Pilot",
        178 => "Spacetrooper",
        179 => "Zero-G Utility Suit",
        180 => "Emkay",
        181 => "Astromech",
        182 => "Worker droid",
        183 => "Backdrop",
        228 => "W/CRS",
        229 => "VSD-II",
        230 => "ISD-II",
    ];

    public static $CRAFTABBR_XW = 1;
    public static $CRAFTABBR_YW = 2;
    public static $CRAFTABBR_AW = 3;
    public static $CRAFTABBR_BW = 4;
    public static $CRAFTABBR_TF = 5;
    public static $CRAFTABBR_TI = 6;
    public static $CRAFTABBR_TB = 7;
    public static $CRAFTABBR_TA = 8;
    public static $CRAFTABBR_TD = 9;
    public static $CRAFTABBR_IRD = 10;
    public static $CRAFTABBR_TOS = 11;
    public static $CRAFTABBR_MIS = 12;
    public static $CRAFTABBR_TW = 13;
    public static $CRAFTABBR_Z95 = 14;
    public static $CRAFTABBR_R41 = 15;
    public static $CRAFTABBR_GUN = 16;
    public static $CRAFTABBR_SHU = 17;
    public static $CRAFTABBR_ES = 18;
    public static $CRAFTABBR_SPC = 19;
    public static $CRAFTABBR_SCT = 20;
    public static $CRAFTABBR_TRN = 21;
    public static $CRAFTABBR_ATR = 22;
    public static $CRAFTABBR_ETR = 23;
    public static $CRAFTABBR_TUG = 24;
    public static $CRAFTABBR_CUV = 25;
    public static $CRAFTABBR_CNA = 26;
    public static $CRAFTABBR_CNB = 27;
    public static $CRAFTABBR_CNC = 28;
    public static $CRAFTABBR_CND = 29;
    public static $CRAFTABBR_HLF = 30;
    public static $CRAFTABBR_MOLEMINER = 31;
    public static $CRAFTABBR_FRT = 32;
    public static $CRAFTABBR_CARG = 33;
    public static $CRAFTABBR_CNVYR = 34;
    public static $CRAFTABBR_CTRNS = 35;
    public static $CRAFTABBR_MED = 36;
    public static $CRAFTABBR_MUR = 37;
    public static $CRAFTABBR_CORT = 38;
    public static $CRAFTABBR_FALC = 39;
    public static $CRAFTABBR_CRV = 40;
    public static $CRAFTABBR_MCRV = 41;
    public static $CRAFTABBR_FRG = 42;
    public static $CRAFTABBR_MFRG = 43;
    public static $CRAFTABBR_LINER = 44;
    public static $CRAFTABBR_CRCK = 45;
    public static $CRAFTABBR_STRKC = 46;
    public static $CRAFTABBR_ESC = 47;
    public static $CRAFTABBR_DRD = 48;
    public static $CRAFTABBR_CRS = 49;
    public static $CRAFTABBR_CRL = 50;
    public static $CRAFTABBR_INT = 51;
    public static $CRAFTABBR_VSD = 52;
    public static $CRAFTABBR_ISD = 53;
    public static $CRAFTABBR_SSD = 54;
    public static $CRAFTABBR_CNE = 55;
    public static $CRAFTABBR_CNF = 56;
    public static $CRAFTABBR_CNG = 57;
    public static $CRAFTABBR_CNH = 58;
    public static $CRAFTABBR_CNI = 59;
    public static $CRAFTABBR_PLTA = 60;
    public static $CRAFTABBR_PLTB = 61;
    public static $CRAFTABBR_PLTC = 62;
    public static $CRAFTABBR_PLTD = 63;
    public static $CRAFTABBR_PLTE = 64;
    public static $CRAFTABBR_PLTF = 65;
    public static $CRAFTABBR_ASTEROIDRNDSTATION = 66;
    public static $CRAFTABBR_ASTEROIDLASERBATTERY = 67;
    public static $CRAFTABBR_ASTEROIDWARHEADBATTERY = 68;
    public static $CRAFTABBR_X7FACTORY = 69;
    public static $CRAFTABBR_SATELLITE1 = 70;
    public static $CRAFTABBR_SATELLITE2 = 71;
    public static $CRAFTABBR_SATELLITE3 = 72;
    public static $CRAFTABBR_SATELLITE4 = 73;
    public static $CRAFTABBR_SATELLITE5 = 74;
    public static $CRAFTABBR_MINEA = 75;
    public static $CRAFTABBR_MINEB = 76;
    public static $CRAFTABBR_MINEC = 77;
    public static $CRAFTABBR_GUNEMPLACEMENT = 78;
    public static $CRAFTABBR_MINE5 = 79;
    public static $CRAFTABBR_PROBEA = 80;
    public static $CRAFTABBR_PROBEB = 81;
    public static $CRAFTABBR_PROBE3 = 82;
    public static $CRAFTABBR_NAVBUOYA = 83;
    public static $CRAFTABBR_NAVBUOYB = 84;
    public static $CRAFTABBR_HYPERBUOY = 85;
    public static $CRAFTABBR_ASTEROIDFIELD = 86;
    public static $CRAFTABBR_PLANET = 87;
    public static $CRAFTABBR_RENDEZVOUSBUOY = 88;
    public static $CRAFTABBR_CARGOCANISTER = 89;
    public static $CRAFTABBR_SHIPYARD = 90;
    public static $CRAFTABBR_REPAIRYARD = 91;
    public static $CRAFTABBR_MODIFIEDSTRIKECRUISER = 92;
    public static $CRAFTABBR_LANCERFRIGATE = 93;
    public static $CRAFTABBR_BULKCRUISER = 94;
    public static $CRAFTABBR_ASSAULTFRIGATE = 95;
    public static $CRAFTABBR_CORELLIANGUNSHIP = 96;
    public static $CRAFTABBR_IMPERIALLANDINGCRAFT = 97;
    public static $CRAFTABBR_ASSAULTSHUTTLE = 98;
    public static $CRAFTABBR_MARAUDERCORVETTE = 99;
    public static $CRAFTABBR_STARGALLEON = 100;
    public static $CRAFTABBR_IMPERIALRESEARCHSHIP = 101;
    public static $CRAFTABBR_LUXURYYACHT3000 = 102;
    public static $CRAFTABBR_FERRYBOATLINER = 103;
    public static $CRAFTABBR_MODIFIEDACTIONTRANSPORT = 104;
    public static $CRAFTABBR_MOBQUETTRANSPORT = 105;
    public static $CRAFTABBR_XIYTIARTRANSPORT = 106;
    public static $CRAFTABBR_FREIGHTTRANSPORTC = 107;
    public static $CRAFTABBR_FREIGHTTRANSPORTH = 108;
    public static $CRAFTABBR_FREIGHTTRANSPORTK = 109;
    public static $CRAFTABBR_YT2000 = 110;
    public static $CRAFTABBR_YT2400 = 111;
    public static $CRAFTABBR_SUPROSA = 112;
    public static $CRAFTABBR_SKIPRAYBLASTBOAT = 113;
    public static $CRAFTABBR_TEM1 = 114;
    public static $CRAFTABBR_TEM2 = 115;
    public static $CRAFTABBR_TEM3 = 116;
    public static $CRAFTABBR_TEM4 = 117;
    public static $CRAFTABBR_TEM5 = 118;
    public static $CRAFTABBR_CLOAKSHAPEFIGHTER = 119;
    public static $CRAFTABBR_RAZORFIGHTER = 120;
    public static $CRAFTABBR_PLANETARYFIGHTER = 121;
    public static $CRAFTABBR_SUPAFIGHTER = 122;
    public static $CRAFTABBR_PINOOKFIGHTER = 123;
    public static $CRAFTABBR_BOOSTERPACK = 124;
    public static $CRAFTABBR_PREYBIRDFIGHTER = 125;
    public static $CRAFTABBR_STARVIPER = 126;
    public static $CRAFTABBR_FIRESPRAY = 127;
    public static $CRAFTABBR_PURSUER = 128;
    public static $CRAFTABBR_GOLAN1 = 129;
    public static $CRAFTABBR_GOLAN2 = 130;
    public static $CRAFTABBR_GOLAN3 = 131;
    public static $CRAFTABBR_DERILYNPLATFORM = 132;
    public static $CRAFTABBR_SENSORARRAY = 133;
    public static $CRAFTABBR_COMMRELAY = 134;
    public static $CRAFTABBR_SPACECOLONY1 = 135;
    public static $CRAFTABBR_SPACECOLONY2 = 136;
    public static $CRAFTABBR_SPACECOLONY3 = 137;
    public static $CRAFTABBR_CASINO = 138;
    public static $CRAFTABBR_CARGOFACILITY1 = 139;
    public static $CRAFTABBR_CARGOFACILITY2 = 140;
    public static $CRAFTABBR_ASTEROIDMININGPLANT = 141;
    public static $CRAFTABBR_PROCESSINGPLANT = 142;
    public static $CRAFTABBR_REBELPLATFORM = 143;
    public static $CRAFTABBR_IMPERIALRESEARCHCENTER = 144;
    public static $CRAFTABBR_FAMILYBASE = 145;
    public static $CRAFTABBR_FAMILYREPAIRYARD = 146;
    public static $CRAFTABBR_PIRATESHIPYARD = 147;
    public static $CRAFTABBR_INDUSTRICALCOMPLEX = 148;
    public static $CRAFTABBR_PIRATEJUNKYARDBASE = 149;
    public static $CRAFTABBR_ESCAPEPOD1 = 150;
    public static $CRAFTABBR_PRESSURETANK = 151;
    public static $CRAFTABBR_CONTAINERJ = 152;
    public static $CRAFTABBR_CONTAINERK = 153;
    public static $CRAFTABBR_CONTAINERL = 154;
    public static $CRAFTABBR_CONTAINERHANGAR = 155;
    public static $CRAFTABBR_LARGEGUNEMPLACEMENT = 156;
    public static $CRAFTABBR_LARGEGUNWARHEADEMPLACEMENT = 157;
    public static $CRAFTABBR_PROXIMITYMINEA = 158;
    public static $CRAFTABBR_PROXIMITYMINEB = 159;
    public static $CRAFTABBR_HOMINGMINEA = 160;
    public static $CRAFTABBR_HOMINGMINEB = 161;
    public static $CRAFTABBR_NEWLASERBATTERY = 162;
    public static $CRAFTABBR_NEWIONBATTERY = 163;
    public static $CRAFTABBR_CARGOFREIGHTER = 164;
    public static $CRAFTABBR_CARGOFREIGHTER2 = 165;
    public static $CRAFTABBR_CARGOFREIGHTER3 = 166;
    public static $CRAFTABBR_CARGOFREIGHTER4 = 167;
    public static $CRAFTABBR_CARGOFREIGHTER5 = 168;
    public static $CRAFTABBR_CARGOTANKER = 169;
    public static $CRAFTABBR_CARGOTANKER2 = 170;
    public static $CRAFTABBR_CARGOTANKER3 = 171;
    public static $CRAFTABBR_CARGOTANKER4 = 172;
    public static $CRAFTABBR_CARGOTANKER5 = 173;
    public static $CRAFTABBR_ESCAPEPOD2 = 174;
    public static $CRAFTABBR_REBELPILOT = 175;
    public static $CRAFTABBR_IMPERIALPILOT = 176;
    public static $CRAFTABBR_CIVILIANPILOT = 177;
    public static $CRAFTABBR_SPACETROOPER = 178;
    public static $CRAFTABBR_ZEROGUTILITYSUIT = 179;
    public static $CRAFTABBR_EMKAY = 180;
    public static $CRAFTABBR_ASTROMECH = 181;
    public static $CRAFTABBR_WORKERDROID = 182;
    public static $CRAFTABBR_BACKDROP = 183;
    public static $CRAFTABBR_WCRS = 228;
    public static $CRAFTABBR_VSDII = 229;
    public static $CRAFTABBR_ISDII = 230;

    public static $HANGAR = [
        0 => "Junkyard",
        1 => "Quick Start 1",
        2 => "Quick Start 2",
        3 => "Quick Start 3",
        4 => "Skirmish",
        5 => "Death Star run",
        6 => "Calamari Cruiser",
        7 => "Family Mission",
    ];

    public static $HANGAR_JUNKYARD = 0;
    public static $HANGAR_QUICKSTART1 = 1;
    public static $HANGAR_QUICKSTART2 = 2;
    public static $HANGAR_QUICKSTART3 = 3;
    public static $HANGAR_SKIRMISH = 4;
    public static $HANGAR_DEATHSTARRUN = 5;
    public static $HANGAR_CALAMARICRUISER = 6;
    public static $HANGAR_FAMILYMISSION = 7;

    public static $BRIEFINGOFFICER = [
        0 => "Devers",
        1 => "Kupalo",
        2 => "Zaletta",
        8 => "Emkay",
    ];

    public static $BRIEFINGOFFICER_DEVERS = 0;
    public static $BRIEFINGOFFICER_KUPALO = 1;
    public static $BRIEFINGOFFICER_ZALETTA = 2;
    public static $BRIEFINGOFFICER_EMKAY = 8;

    public static $BRIEFINGLOGO = [
        4 => "Defiance",
        5 => "Liberty",
        6 => "Independence",
        7 => "Family",
        8 => "Phantom Squadron",
    ];

    public static $BRIEFINGLOGO_DEFIANCE = 4;
    public static $BRIEFINGLOGO_LIBERTY = 5;
    public static $BRIEFINGLOGO_INDEPENDENCE = 6;
    public static $BRIEFINGLOGO_FAMILY = 7;
    public static $BRIEFINGLOGO_PHANTOMSQUADRON = 8;

    public static $DESIGNATION = [
        0 => "Command Ship",
        1 => "Base",
        2 => "Station",
        3 => "Mission Critical Craft",
        4 => "Convoy Craft",
        5 => "Strike Craft",
        6 => "Reload Craft",
        7 => "Primary Target",
        8 => "Secondary Target",
        9 => "Tertiary Target",
        10 => "Resource Center",
        11 => "Facility",
        12 => "HYP from Region 1",
        13 => "HYP from Region 2",
        14 => "HYP from Region 3",
        15 => "HYP from Region 4",
        16 => "HYP to Region 1",
        17 => "HYP to Region 2",
        18 => "HYP to Region 3",
        19 => "HYP to Region 4",
        20 => "Unknown",
        21 => "Unknown",
    ];

    public static $DESIGNATION_COMMANDSHIP = 0;
    public static $DESIGNATION_BASE = 1;
    public static $DESIGNATION_STATION = 2;
    public static $DESIGNATION_MISSIONCRITICALCRAFT = 3;
    public static $DESIGNATION_CONVOYCRAFT = 4;
    public static $DESIGNATION_STRIKECRAFT = 5;
    public static $DESIGNATION_RELOADCRAFT = 6;
    public static $DESIGNATION_PRIMARYTARGET = 7;
    public static $DESIGNATION_SECONDARYTARGET = 8;
    public static $DESIGNATION_TERTIARYTARGET = 9;
    public static $DESIGNATION_RESOURCECENTER = 10;
    public static $DESIGNATION_FACILITY = 11;
    public static $DESIGNATION_HYPFROMREGION1 = 12;
    public static $DESIGNATION_HYPFROMREGION2 = 13;
    public static $DESIGNATION_HYPFROMREGION3 = 14;
    public static $DESIGNATION_HYPFROMREGION4 = 15;
    public static $DESIGNATION_HYPTOREGION1 = 16;
    public static $DESIGNATION_HYPTOREGION2 = 17;
    public static $DESIGNATION_HYPTOREGION3 = 18;
    public static $DESIGNATION_HYPTOREGION4 = 19;
    public static $DESIGNATION_UNKNOWN = 20;
    public static $DESIGNATION_UNKNOWN2 = 21;

    public static $STATUS = [
        0 => "None",
        1 => "2X Warheads",
        2 => "1/2 Warheads",
        3 => "No Shields",
        4 => "1/2 Shields",
        5 => "No Lasers",
        6 => "No Hyperdrive",
        7 => "Shields 0%, charging",
        8 => "Shields added or 200%",
        9 => "Hyperdrive added",
        10 => "2x Countermeasure",
        11 => "1/2 Countermeasures",
        12 => "(200% Shields)",
        13 => "Shields 50%, Charging",
        14 => "(No Lasers)",
        15 => "Engines Damaged",
        16 => "Shields + Hyperdrive added",
        17 => "All Systems Damaged",
        18 => "200% Shields",
        19 => "(50% Shields)",
        20 => "Invincible",
        21 => "Infinite Warheads",
        22 => "No Escape Pods / Ejected Pilot",
        23 => "No Cargo Pods",
        24 => "Not Inspected",
        25 => "Not ID'ed",
        26 => "Inspected",
        27 => "ID'ed",
        28 => "Limited Targetability",
    ];

    public static $STATUS_NONE = 0;
    public static $STATUS_N2XWARHEADS = 1;
    public static $STATUS_N12WARHEADS = 2;
    public static $STATUS_NOSHIELDS = 3;
    public static $STATUS_N12SHIELDS = 4;
    public static $STATUS_NOLASERS = 5;
    public static $STATUS_NOHYPERDRIVE = 6;
    public static $STATUS_SHIELDS0PERCENTCHARGING = 7;
    public static $STATUS_SHIELDSADDEDOR200PERCENT = 8;
    public static $STATUS_HYPERDRIVEADDED = 9;
    public static $STATUS_N2XCOUNTERMEASURE = 10;
    public static $STATUS_N12COUNTERMEASURES = 11;
    public static $STATUS_N200PERCENTSHIELDS = 12;
    public static $STATUS_SHIELDS50PERCENTCHARGING = 13;
    public static $STATUS_NOLASERS2 = 14;
    public static $STATUS_ENGINESDAMAGED = 15;
    public static $STATUS_SHIELDSHYPERDRIVEADDED = 16;
    public static $STATUS_ALLSYSTEMSDAMAGED = 17;
    public static $STATUS_N200PERCENTSHIELDS2 = 18;
    public static $STATUS_N50PERCENTSHIELDS = 19;
    public static $STATUS_INVINCIBLE = 20;
    public static $STATUS_INFINITEWARHEADS = 21;
    public static $STATUS_NOESCAPEPODSEJECTEDPILOT = 22;
    public static $STATUS_NOCARGOPODS = 23;
    public static $STATUS_NOTINSPECTED = 24;
    public static $STATUS_NOTIDED = 25;
    public static $STATUS_INSPECTED = 26;
    public static $STATUS_IDED = 27;
    public static $STATUS_LIMITEDTARGETABILITY = 28;

    public static $WARHEAD = [
        0 => "None",
        1 => "Space Bomb",
        2 => "Heavy Rocket",
        3 => "Concussion Missile",
        4 => "Torpedo",
        5 => "Advanced Concussion Missile",
        6 => "Advanced Torpedo",
        7 => "Mag Pulse Torpedo",
        8 => "Ion Pulse Torpedo",
    ];

    public static $WARHEAD_NONE = 0;
    public static $WARHEAD_SPACEBOMB = 1;
    public static $WARHEAD_HEAVYROCKET = 2;
    public static $WARHEAD_CONCUSSIONMISSILE = 3;
    public static $WARHEAD_TORPEDO = 4;
    public static $WARHEAD_ADVANCEDCONCUSSIONMISSILE = 5;
    public static $WARHEAD_ADVANCEDTORPEDO = 6;
    public static $WARHEAD_MAGPULSETORPEDO = 7;
    public static $WARHEAD_IONPULSETORPEDO = 8;

    public static $BEAM = [
        0 => "None",
        1 => "Tractor Beam",
        2 => "Jamming Beam",
        3 => "Decoy Beam",
    ];

    public static $BEAM_NONE = 0;
    public static $BEAM_TRACTORBEAM = 1;
    public static $BEAM_JAMMINGBEAM = 2;
    public static $BEAM_DECOYBEAM = 3;

    public static $GROUPAI = [
        0 => "Novice (None)",
        1 => "Officer",
        2 => "Veteran",
        3 => "Ace",
        4 => "Top Ace",
        5 => "Super Ace (Invincible)",
    ];

    public static $GROUPAI_NOVICENONE = 0;
    public static $GROUPAI_OFFICER = 1;
    public static $GROUPAI_VETERAN = 2;
    public static $GROUPAI_ACE = 3;
    public static $GROUPAI_TOPACE = 4;
    public static $GROUPAI_SUPERACEINVINCIBLE = 5;

    public static $MARKINGS = [
        0 => "Red (TIE - None)",
        1 => "Gold (TIE - Red)",
        2 => "Blue (TIE - Gold)",
        3 => "Green (TIE - Blue)",
    ];

    public static $MARKINGS_REDTIENONE = 0;
    public static $MARKINGS_GOLDTIERED = 1;
    public static $MARKINGS_BLUETIEGOLD = 2;
    public static $MARKINGS_GREENTIEBLUE = 3;

    public static $RADIO = [
        0 => "None",
        1 => "Team 1",
        2 => "Team 2",
        3 => "Team 3",
        4 => "Team 4",
        5 => "Team 5",
        6 => "Team 6",
        7 => "Team 7",
        8 => "Team 8",
        9 => "Player 1",
        10 => "Player 2",
        11 => "Player 3",
        12 => "Player 4",
        13 => "Player 5",
        14 => "Player 6",
        15 => "Player 7",
        16 => "Player 8",
    ];

    public static $RADIO_NONE = 0;
    public static $RADIO_TEAM1 = 1;
    public static $RADIO_TEAM2 = 2;
    public static $RADIO_TEAM3 = 3;
    public static $RADIO_TEAM4 = 4;
    public static $RADIO_TEAM5 = 5;
    public static $RADIO_TEAM6 = 6;
    public static $RADIO_TEAM7 = 7;
    public static $RADIO_TEAM8 = 8;
    public static $RADIO_PLAYER1 = 9;
    public static $RADIO_PLAYER2 = 10;
    public static $RADIO_PLAYER3 = 11;
    public static $RADIO_PLAYER4 = 12;
    public static $RADIO_PLAYER5 = 13;
    public static $RADIO_PLAYER6 = 14;
    public static $RADIO_PLAYER7 = 15;
    public static $RADIO_PLAYER8 = 16;

    public static $FORMATION = [
        0 => "Vic",
        1 => "Finger Four",
        2 => "Line Astern",
        3 => "Line Abreast",
        4 => "Echelon Right",
        5 => "Echelon Left",
        6 => "Double Astern",
        7 => "Diamond",
        8 => "Stack",
        9 => "High X",
        10 => "Vic Abreast",
        11 => "High Vic",
        12 => "Reverse High Vic",
        13 => "Reverse Line Astern",
        14 => "Stacked Low",
        15 => "Abreast Right",
        16 => "Abreast Left",
        17 => "Wing Forward",
        18 => "Wing Back",
        19 => "Line Astern Up",
        20 => "Line Astern Down",
        21 => "Abreast V",
        22 => "Abreast Inverted V",
        23 => "Double Astern Mirror",
        24 => "Double Stacked Astern",
        25 => "Double Stacked High",
        26 => "Diamond 1",
        27 => "Diamond 2",
        28 => "Flat Pentagon",
        29 => "Side Pentagon",
        30 => "Front Pentagon",
        31 => "Flat Hexagon",
        32 => "Side Hexagon",
        33 => "Front Hexagon",
    ];

    public static $FORMATION_VIC = 0;
    public static $FORMATION_FINGERFOUR = 1;
    public static $FORMATION_LINEASTERN = 2;
    public static $FORMATION_LINEABREAST = 3;
    public static $FORMATION_ECHELONRIGHT = 4;
    public static $FORMATION_ECHELONLEFT = 5;
    public static $FORMATION_DOUBLEASTERN = 6;
    public static $FORMATION_DIAMOND = 7;
    public static $FORMATION_STACK = 8;
    public static $FORMATION_HIGHX = 9;
    public static $FORMATION_VICABREAST = 10;
    public static $FORMATION_HIGHVIC = 11;
    public static $FORMATION_REVERSEHIGHVIC = 12;
    public static $FORMATION_REVERSELINEASTERN = 13;
    public static $FORMATION_STACKEDLOW = 14;
    public static $FORMATION_ABREASTRIGHT = 15;
    public static $FORMATION_ABREASTLEFT = 16;
    public static $FORMATION_WINGFORWARD = 17;
    public static $FORMATION_WINGBACK = 18;
    public static $FORMATION_LINEASTERNUP = 19;
    public static $FORMATION_LINEASTERNDOWN = 20;
    public static $FORMATION_ABREASTV = 21;
    public static $FORMATION_ABREASTINVERTEDV = 22;
    public static $FORMATION_DOUBLEASTERNMIRROR = 23;
    public static $FORMATION_DOUBLESTACKEDASTERN = 24;
    public static $FORMATION_DOUBLESTACKEDHIGH = 25;
    public static $FORMATION_DIAMOND1 = 26;
    public static $FORMATION_DIAMOND2 = 27;
    public static $FORMATION_FLATPENTAGON = 28;
    public static $FORMATION_SIDEPENTAGON = 29;
    public static $FORMATION_FRONTPENTAGON = 30;
    public static $FORMATION_FLATHEXAGON = 31;
    public static $FORMATION_SIDEHEXAGON = 32;
    public static $FORMATION_FRONTHEXAGON = 33;

    public static $ARRIVALDIFFICULTY = [
        0 => "All",
        1 => "Easy",
        2 => "Medium",
        3 => "Hard",
        4 => "Greater than Easy",
        5 => "Less than Hard",
        6 => "Never",
    ];

    public static $ARRIVALDIFFICULTY_ALL = 0;
    public static $ARRIVALDIFFICULTY_EASY = 1;
    public static $ARRIVALDIFFICULTY_MEDIUM = 2;
    public static $ARRIVALDIFFICULTY_HARD = 3;
    public static $ARRIVALDIFFICULTY_GREATERTHANEASY = 4;
    public static $ARRIVALDIFFICULTY_LESSTHANHARD = 5;
    public static $ARRIVALDIFFICULTY_NEVER = 6;

    public static $CONDITION = [
        0 => "Always (true)",
        1 => "Created",
        2 => "Destroyed",
        3 => "Attacked",
        4 => "Captured",
        5 => "Inspected",
        6 => "Boarded",
        7 => "Docked",
        8 => "Disabled",
        9 => "Exist",
        10 => "None (false)",
        11 => "Unknown (---)",
        12 => "Completed mission",
        13 => "Completed Primary Goals",
        14 => "Failed Primary Goals",
        15 => "Completed Secondary Goals",
        16 => "Failed Secondary Goals",
        17 => "Completed Bonus Goals",
        18 => "Failed Bonus Goals",
        19 => "Dropped off",
        20 => "Reinforced",
        21 => "0% Shields",
        22 => "50% Hull",
        23 => "Out of Warheads",
        24 => "Unknown (arrive?)",
        25 => "Be dropped off",
        26 => "Unharmed?",
        27 => "NOT be disabled",
        28 => "NOT be picked up",
        29 => "Destroyed w/o Inspection",
        30 => "Be docked with",
        31 => "NOT be docked with",
        32 => "Begin boarding",
        33 => "NOT begin boarding",
        34 => "50% Shields",
        35 => "25% Shields",
        36 => "75% Hull",
        37 => "25% Hull",
        38 => "Unknown",
        39 => "Unknown",
        40 => "Unknown",
        41 => "Be all Player Craft",
        42 => "Reinforced by AI?",
        43 => "Come and go",
        44 => "Be picked up",
        45 => "Withdraw",
        46 => "Be carried away",
        47 => "Arrived in Region",
        48 => "Departed Region",
        49 => "Be in proximity of",
        50 => "NOT be in proxmity of",
        51 => "Unknown",
        52 => "Defect",
        53 => "Be in convoy",
        54 => "Be delivered?",
        55 => "Unknown",
        56 => "Be shown (message)",
        57 => "Be ID'ed",
        58 => "Unknown",
        59 => "Exist?",
    ];

    public static $CONDITION_ALWAYSTRUE = 0;
    public static $CONDITION_CREATED = 1;
    public static $CONDITION_DESTROYED = 2;
    public static $CONDITION_ATTACKED = 3;
    public static $CONDITION_CAPTURED = 4;
    public static $CONDITION_INSPECTED = 5;
    public static $CONDITION_BOARDED = 6;
    public static $CONDITION_DOCKED = 7;
    public static $CONDITION_DISABLED = 8;
    public static $CONDITION_EXIST = 9;
    public static $CONDITION_NONEFALSE = 10;
    public static $CONDITION_UNKNOWN = 11;
    public static $CONDITION_COMPLETEDMISSION = 12;
    public static $CONDITION_COMPLETEDPRIMARYGOALS = 13;
    public static $CONDITION_FAILEDPRIMARYGOALS = 14;
    public static $CONDITION_COMPLETEDSECONDARYGOALS = 15;
    public static $CONDITION_FAILEDSECONDARYGOALS = 16;
    public static $CONDITION_COMPLETEDBONUSGOALS = 17;
    public static $CONDITION_FAILEDBONUSGOALS = 18;
    public static $CONDITION_DROPPEDOFF = 19;
    public static $CONDITION_REINFORCED = 20;
    public static $CONDITION_N0PERCENTSHIELDS = 21;
    public static $CONDITION_N50PERCENTHULL = 22;
    public static $CONDITION_OUTOFWARHEADS = 23;
    public static $CONDITION_UNKNOWNARRIVE = 24;
    public static $CONDITION_BEDROPPEDOFF = 25;
    public static $CONDITION_UNHARMED = 26;
    public static $CONDITION_NOTBEDISABLED = 27;
    public static $CONDITION_NOTBEPICKEDUP = 28;
    public static $CONDITION_DESTROYEDWOINSPECTION = 29;
    public static $CONDITION_BEDOCKEDWITH = 30;
    public static $CONDITION_NOTBEDOCKEDWITH = 31;
    public static $CONDITION_BEGINBOARDING = 32;
    public static $CONDITION_NOTBEGINBOARDING = 33;
    public static $CONDITION_N50PERCENTSHIELDS = 34;
    public static $CONDITION_N25PERCENTSHIELDS = 35;
    public static $CONDITION_N75PERCENTHULL = 36;
    public static $CONDITION_N25PERCENTHULL = 37;
    public static $CONDITION_UNKNOWN2 = 38;
    public static $CONDITION_UNKNOWN3 = 39;
    public static $CONDITION_UNKNOWN4 = 40;
    public static $CONDITION_BEALLPLAYERCRAFT = 41;
    public static $CONDITION_REINFORCEDBYAI = 42;
    public static $CONDITION_COMEANDGO = 43;
    public static $CONDITION_BEPICKEDUP = 44;
    public static $CONDITION_WITHDRAW = 45;
    public static $CONDITION_BECARRIEDAWAY = 46;
    public static $CONDITION_ARRIVEDINREGION = 47;
    public static $CONDITION_DEPARTEDREGION = 48;
    public static $CONDITION_BEINPROXIMITYOF = 49;
    public static $CONDITION_NOTBEINPROXMITYOF = 50;
    public static $CONDITION_UNKNOWN5 = 51;
    public static $CONDITION_DEFECT = 52;
    public static $CONDITION_BEINCONVOY = 53;
    public static $CONDITION_BEDELIVERED = 54;
    public static $CONDITION_UNKNOWN6 = 55;
    public static $CONDITION_BESHOWNMESSAGE = 56;
    public static $CONDITION_BEIDED = 57;
    public static $CONDITION_UNKNOWN7 = 58;
    public static $CONDITION_EXIST2 = 59;

    public static $VARIABLETYPE = [
        0 => "None",
        1 => "Flight Group",
        2 => "CraftType (enum)",
        3 => "CraftCategory (enum)",
        4 => "ObjectCategory (enum)",
        5 => "IFF",
        6 => "Order (enum)",
        7 => "CraftWhen (enum)",
        8 => "Global Group",
        9 => "Rating",
        10 => "Craft with Status1",
        11 => "All",
        12 => "Team",
        13 => "Player",
        14 => "Delay",
        15 => "All Flight Groups except",
        16 => "All Craft Types except",
        17 => "All Craft Categories except",
        18 => "All Object Categories except",
        19 => "All IFFs except",
        20 => "All Global Groups except",
        21 => "All Teams except",
        22 => "All players except",
        23 => "Global Unit",
        24 => "All Global Units except?",
        25 => "Craft with Global Cargo",
        26 => "Craft without Global Cargo",
        27 => "Message #",
    ];

    public static $VARIABLETYPE_NONE = 0;
    public static $VARIABLETYPE_FLIGHTGROUP = 1;
    public static $VARIABLETYPE_CRAFTTYPEENUM = 2;
    public static $VARIABLETYPE_CRAFTCATEGORYENUM = 3;
    public static $VARIABLETYPE_OBJECTCATEGORYENUM = 4;
    public static $VARIABLETYPE_IFF = 5;
    public static $VARIABLETYPE_ORDERENUM = 6;
    public static $VARIABLETYPE_CRAFTWHENENUM = 7;
    public static $VARIABLETYPE_GLOBALGROUP = 8;
    public static $VARIABLETYPE_RATING = 9;
    public static $VARIABLETYPE_CRAFTWITHSTATUS1 = 10;
    public static $VARIABLETYPE_ALL = 11;
    public static $VARIABLETYPE_TEAM = 12;
    public static $VARIABLETYPE_PLAYER = 13;
    public static $VARIABLETYPE_DELAY = 14;
    public static $VARIABLETYPE_ALLFLIGHTGROUPSEXCEPT = 15;
    public static $VARIABLETYPE_ALLCRAFTTYPESEXCEPT = 16;
    public static $VARIABLETYPE_ALLCRAFTCATEGORIESEXCEPT = 17;
    public static $VARIABLETYPE_ALLOBJECTCATEGORIESEXCEPT = 18;
    public static $VARIABLETYPE_ALLIFFSEXCEPT = 19;
    public static $VARIABLETYPE_ALLGLOBALGROUPSEXCEPT = 20;
    public static $VARIABLETYPE_ALLTEAMSEXCEPT = 21;
    public static $VARIABLETYPE_ALLPLAYERSEXCEPT = 22;
    public static $VARIABLETYPE_GLOBALUNIT = 23;
    public static $VARIABLETYPE_ALLGLOBALUNITSEXCEPT = 24;
    public static $VARIABLETYPE_CRAFTWITHGLOBALCARGO = 25;
    public static $VARIABLETYPE_CRAFTWITHOUTGLOBALCARGO = 26;
    public static $VARIABLETYPE_MESSAGE = 27;

    public static $CRAFTCATEGORY = [
        0 => "Starfighters",
        1 => "Transports",
        2 => "Freighters/Containers",
        3 => "Starships",
        4 => "Utility Craft",
        5 => "Platforms/Facilities",
        6 => "Mines",
    ];

    public static $CRAFTCATEGORY_STARFIGHTERS = 0;
    public static $CRAFTCATEGORY_TRANSPORTS = 1;
    public static $CRAFTCATEGORY_FREIGHTERSCONTAINERS = 2;
    public static $CRAFTCATEGORY_STARSHIPS = 3;
    public static $CRAFTCATEGORY_UTILITYCRAFT = 4;
    public static $CRAFTCATEGORY_PLATFORMSFACILITIES = 5;
    public static $CRAFTCATEGORY_MINES = 6;

    public static $OBJECTCATEGORY = [
        0 => "Craft",
        1 => "Weapons",
        2 => "Space Objects",
    ];

    public static $OBJECTCATEGORY_CRAFT = 0;
    public static $OBJECTCATEGORY_WEAPONS = 1;
    public static $OBJECTCATEGORY_SPACEOBJECTS = 2;

    public static $AMOUNT = [
        0 => "100%",
        1 => "75%",
        2 => "50%",
        3 => "25%",
        4 => "At least one",
        5 => "All but one",
        6 => "Special craft",
        7 => "All non-special craft",
        8 => "All non-player craft",
        9 => "Player's craft",
        10 => "Unknown",
        16 => "66%",
        17 => "33%",
        18 => "Each craft",
        19 => "Each special craft",
    ];

    public static $AMOUNT_N100PERCENT = 0;
    public static $AMOUNT_N75PERCENT = 1;
    public static $AMOUNT_N50PERCENT = 2;
    public static $AMOUNT_N25PERCENT = 3;
    public static $AMOUNT_ATLEASTONE = 4;
    public static $AMOUNT_ALLBUTONE = 5;
    public static $AMOUNT_SPECIALCRAFT = 6;
    public static $AMOUNT_ALLNONSPECIALCRAFT = 7;
    public static $AMOUNT_ALLNONPLAYERCRAFT = 8;
    public static $AMOUNT_PLAYERSCRAFT = 9;
    public static $AMOUNT_UNKNOWN = 10;
    public static $AMOUNT_N66PERCENT = 16;
    public static $AMOUNT_N33PERCENT = 17;
    public static $AMOUNT_EACHCRAFT = 18;
    public static $AMOUNT_EACHSPECIALCRAFT = 19;

    public static $ABORTTRIGGER = [
        0 => "None",
        1 => "0% Shields",
        2 => "Unknown",
        3 => "Out of warheads",
        4 => "50% Hull",
        5 => "Attacked",
        6 => "50% Shields",
        7 => "25% Shields",
        8 => "75% Hull",
        9 => "25% Hull",
    ];

    public static $ABORTTRIGGER_NONE = 0;
    public static $ABORTTRIGGER_N0PERCENTSHIELDS = 1;
    public static $ABORTTRIGGER_UNKNOWN = 2;
    public static $ABORTTRIGGER_OUTOFWARHEADS = 3;
    public static $ABORTTRIGGER_N50PERCENTHULL = 4;
    public static $ABORTTRIGGER_ATTACKED = 5;
    public static $ABORTTRIGGER_N50PERCENTSHIELDS = 6;
    public static $ABORTTRIGGER_N25PERCENTSHIELDS = 7;
    public static $ABORTTRIGGER_N75PERCENTHULL = 8;
    public static $ABORTTRIGGER_N25PERCENTHULL = 9;

    public static $ORDER = [
        0 => "Hold Station",
        1 => "Go Home",
        2 => "Circle",
        3 => "Circle and Evade",
        4 => "Rendezvous",
        5 => "Disabled",
        6 => "Await Boarding",
        7 => "Attack",
        8 => "Attack Escorts",
        9 => "Protect",
        10 => "Escort",
        11 => "Disable",
        12 => "Board and Give Cargo",
        13 => "Board and Take Cargo",
        14 => "Board and Exchange Cargo",
        15 => "Board and Capture Cargo",
        16 => "Board and Destroy Cargo",
        17 => "Pick up",
        18 => "Drop off",
        19 => "Wait",
        20 => "SS Wait",
        21 => "SS Patrol Loop",
        22 => "SS Await Return",
        23 => "SS Launch",
        24 => "SS Protect",
        25 => "SS Wait and Protect",
        26 => "SS Patrol and Attack",
        27 => "SS Patrol and Disable",
        28 => "SS Hold Steady",
        29 => "SS Go Home",
        30 => "SS Wait",
        31 => "SS Board",
        32 => "Board to Repair",
        33 => "Hold Station",
        34 => "Hold Steady",
        35 => "SS Hold Station",
        36 => "Self-destruct",
        37 => "Kamikaze",
        38 => "(Orbit)/Permanently disabled",
        39 => "(Release Carried Cargo)",
        40 => "Deliver/Drop Off",
        41 => "Unknown",
        42 => "(Attack)",
        43 => "Load Objects",
        44 => "Sit and Fire",
        45 => "Repair Self",
        46 => "Defect",
        47 => "Self Capture / Surrender",
        48 => "*Make",
        49 => "Beacon",
        50 => "Hyper to Region",
        51 => "*Relaunch",
        52 => "Transfer Cargo",
        53 => "Inspect Targets",
        54 => "*Await Assembly",
        55 => "*Await Disassembly",
        56 => "*Construct Train",
        57 => "Park at",
        58 => "*Board to Defuse",
        59 => "Start Over",
        60 => "*Take Apart Train",
        61 => "Work on",
        62 => "(Dock to Load)",
        63 => "Follow Targets",
        64 => "Home In",
    ];

    public static $ORDER_HOLDSTATION = 0;
    public static $ORDER_GOHOME = 1;
    public static $ORDER_CIRCLE = 2;
    public static $ORDER_CIRCLEANDEVADE = 3;
    public static $ORDER_RENDEZVOUS = 4;
    public static $ORDER_DISABLED = 5;
    public static $ORDER_AWAITBOARDING = 6;
    public static $ORDER_ATTACK = 7;
    public static $ORDER_ATTACKESCORTS = 8;
    public static $ORDER_PROTECT = 9;
    public static $ORDER_ESCORT = 10;
    public static $ORDER_DISABLE = 11;
    public static $ORDER_BOARDANDGIVECARGO = 12;
    public static $ORDER_BOARDANDTAKECARGO = 13;
    public static $ORDER_BOARDANDEXCHANGECARGO = 14;
    public static $ORDER_BOARDANDCAPTURECARGO = 15;
    public static $ORDER_BOARDANDDESTROYCARGO = 16;
    public static $ORDER_PICKUP = 17;
    public static $ORDER_DROPOFF = 18;
    public static $ORDER_WAIT = 19;
    public static $ORDER_SSWAIT = 20;
    public static $ORDER_SSPATROLLOOP = 21;
    public static $ORDER_SSAWAITRETURN = 22;
    public static $ORDER_SSLAUNCH = 23;
    public static $ORDER_SSPROTECT = 24;
    public static $ORDER_SSWAITANDPROTECT = 25;
    public static $ORDER_SSPATROLANDATTACK = 26;
    public static $ORDER_SSPATROLANDDISABLE = 27;
    public static $ORDER_SSHOLDSTEADY = 28;
    public static $ORDER_SSGOHOME = 29;
    public static $ORDER_SSWAIT2 = 30;
    public static $ORDER_SSBOARD = 31;
    public static $ORDER_BOARDTOREPAIR = 32;
    public static $ORDER_HOLDSTATION2 = 33;
    public static $ORDER_HOLDSTEADY = 34;
    public static $ORDER_SSHOLDSTATION = 35;
    public static $ORDER_SELFDESTRUCT = 36;
    public static $ORDER_KAMIKAZE = 37;
    public static $ORDER_ORBITPERMANENTLYDISABLED = 38;
    public static $ORDER_RELEASECARRIEDCARGO = 39;
    public static $ORDER_DELIVERDROPOFF = 40;
    public static $ORDER_UNKNOWN = 41;
    public static $ORDER_ATTACK2 = 42;
    public static $ORDER_LOADOBJECTS = 43;
    public static $ORDER_SITANDFIRE = 44;
    public static $ORDER_REPAIRSELF = 45;
    public static $ORDER_DEFECT = 46;
    public static $ORDER_SELFCAPTURESURRENDER = 47;
    public static $ORDER_MAKE = 48;
    public static $ORDER_BEACON = 49;
    public static $ORDER_HYPERTOREGION = 50;
    public static $ORDER_RELAUNCH = 51;
    public static $ORDER_TRANSFERCARGO = 52;
    public static $ORDER_INSPECTTARGETS = 53;
    public static $ORDER_AWAITASSEMBLY = 54;
    public static $ORDER_AWAITDISASSEMBLY = 55;
    public static $ORDER_CONSTRUCTTRAIN = 56;
    public static $ORDER_PARKAT = 57;
    public static $ORDER_BOARDTODEFUSE = 58;
    public static $ORDER_STARTOVER = 59;
    public static $ORDER_TAKEAPARTTRAIN = 60;
    public static $ORDER_WORKON = 61;
    public static $ORDER_DOCKTOLOAD = 62;
    public static $ORDER_FOLLOWTARGETS = 63;
    public static $ORDER_HOMEIN = 64;

    public static $CRAFTWHEN = [
        1 => "Inspected",
        2 => "Finished docking?",
        4 => "Disabled",
        5 => "Attacked",
        6 => "Any hull damage",
        7 => "Special craft",
        8 => "Non-special craft",
        9 => "Player's craft",
        10 => "Non-player's craft",
        12 => "not disabled",
    ];

    public static $CRAFTWHEN_INSPECTED = 1;
    public static $CRAFTWHEN_FINISHEDDOCKING = 2;
    public static $CRAFTWHEN_DISABLED = 4;
    public static $CRAFTWHEN_ATTACKED = 5;
    public static $CRAFTWHEN_ANYHULLDAMAGE = 6;
    public static $CRAFTWHEN_SPECIALCRAFT = 7;
    public static $CRAFTWHEN_NONSPECIALCRAFT = 8;
    public static $CRAFTWHEN_PLAYERSCRAFT = 9;
    public static $CRAFTWHEN_NONPLAYERSCRAFT = 10;
    public static $CRAFTWHEN_NOTDISABLED = 12;

    public static $EVENTTYPE = [
        3 => "Page Break",
        4 => "Title Text",
        5 => "Caption Text",
        6 => "Move Map",
        7 => "Zoom Map",
        8 => "Clear FG Tags",
        9 => "FG Tag 1",
        10 => "FG Tag 2",
        11 => "FG Tag 3",
        12 => "FG Tag 4",
        13 => "FG Tag 5",
        14 => "FG Tag 6",
        15 => "FG Tag 7",
        16 => "FG Tag 8",
        17 => "Clear Text Tags",
        18 => "Text Tag 1",
        19 => "Text Tag 2",
        20 => "Text Tag 3",
        21 => "Text Tag 4",
        22 => "Text Tag 5",
        23 => "Text Tag 6",
        24 => "Text Tag 7",
        25 => "Text Tag 8",
        26 => "New Icon",
        27 => "Ship Craft Data",
        28 => "Move Icon",
        29 => "Rotate Icon",
        30 => "Change Region",
        34 => "End Briefing",
    ];

    public static $EVENTTYPE_PAGEBREAK = 3;
    public static $EVENTTYPE_TITLETEXT = 4;
    public static $EVENTTYPE_CAPTIONTEXT = 5;
    public static $EVENTTYPE_MOVEMAP = 6;
    public static $EVENTTYPE_ZOOMMAP = 7;
    public static $EVENTTYPE_CLEARFGTAGS = 8;
    public static $EVENTTYPE_FGTAG1 = 9;
    public static $EVENTTYPE_FGTAG2 = 10;
    public static $EVENTTYPE_FGTAG3 = 11;
    public static $EVENTTYPE_FGTAG4 = 12;
    public static $EVENTTYPE_FGTAG5 = 13;
    public static $EVENTTYPE_FGTAG6 = 14;
    public static $EVENTTYPE_FGTAG7 = 15;
    public static $EVENTTYPE_FGTAG8 = 16;
    public static $EVENTTYPE_CLEARTEXTTAGS = 17;
    public static $EVENTTYPE_TEXTTAG1 = 18;
    public static $EVENTTYPE_TEXTTAG2 = 19;
    public static $EVENTTYPE_TEXTTAG3 = 20;
    public static $EVENTTYPE_TEXTTAG4 = 21;
    public static $EVENTTYPE_TEXTTAG5 = 22;
    public static $EVENTTYPE_TEXTTAG6 = 23;
    public static $EVENTTYPE_TEXTTAG7 = 24;
    public static $EVENTTYPE_TEXTTAG8 = 25;
    public static $EVENTTYPE_NEWICON = 26;
    public static $EVENTTYPE_SHIPCRAFTDATA = 27;
    public static $EVENTTYPE_MOVEICON = 28;
    public static $EVENTTYPE_ROTATEICON = 29;
    public static $EVENTTYPE_CHANGEREGION = 30;
    public static $EVENTTYPE_ENDBRIEFING = 34;

    public static $TFTCCRAFTTYPE = [
        1 => "X-Wing",
        2 => "Y-Wing",
        3 => "A-Wing",
        4 => "B-Wing",
        5 => "TIE Fighter",
        6 => "TIE Interceptor",
        7 => "TIE Bomber",
        8 => "TIE Advanced",
        9 => "TIE Defender",
        10 => "Authority IRD",
        11 => "Toscan Fighter",
        12 => "Missile Boat",
        13 => "T-Wing",
        14 => "Z-95 Headhunter",
        15 => "R-41 Starchaser",
        16 => "Assault Gunboat",
        17 => "Lambda Shuttle",
        18 => "Escort Shuttle",
        19 => "System Patrol Craft",
        20 => "Scout Craft",
        21 => "Stormtrooper Transport",
        22 => "Assault Transport",
        23 => "Escort Transport",
        24 => "Utility Tug",
        25 => "Combat Utility Vehicle",
        26 => "CN/A Brick",
        27 => "CN/B Hexbox",
        28 => "CN/C Tube",
        29 => "CN/D Pronged",
        30 => "Heavy Lifter",
        31 => "Mole Miner",
        32 => "Bulk Freighter",
        33 => "Cargo Ferry",
        34 => "Modular Conveyor",
        35 => "Container Transport",
        36 => "Medium Transport",
        37 => "Muurian Transport",
        38 => "YT-1300 Transport",
        39 => "Millennium Falcon",
        40 => "Corellian Corvette",
        41 => "Modified Corvette",
        42 => "Nebulon-B Frigate",
        43 => "Nebulon-B2 Frigate",
        44 => "C-3 Passenger Liner",
        45 => "Carrack Cruiser",
        46 => "Strike Cruiser",
        47 => "Escort Carrier",
        48 => "Dreadnaught",
        49 => "MC80A Chatnoir Star Cruiser",
        50 => "MC40a Light Cruiser",
        51 => "Interdictor",
        52 => "Victory I Star Destroyer",
        53 => "Imperial I Star Destroyer",
        54 => "Super Star Destroyer",
        55 => "CN/E Hemisphere",
        56 => "CN/F Slotted",
        57 => "CN/G Hourglass",
        58 => "CN/H Gem",
        59 => "CN/I Y shaped",
        60 => "Platform 1",
        61 => "Platform 2",
        62 => "Platform 3",
        63 => "Platform 4",
        64 => "Platform 5",
        65 => "Platform 6",
        66 => "Asteroid Hangar",
        67 => "Ast Laser Battery",
        68 => "Ast Warhd Launcher",
        69 => "Deep Space Facility",
        70 => "Satellite1",
        71 => "Satellite2",
        72 => "Satellite3",
        73 => "Satellite4",
        74 => "Satellite5",
        75 => "Mine1",
        76 => "Mine2",
        77 => "Mine3",
        78 => "GunPlatform",
        79 => "Mine5",
        80 => "Probe1",
        81 => "Probe Capsule",
        82 => "Probe3",
        83 => "Type 1 Navigation Buoy",
        84 => "Type 2 Navigation Buoy",
        85 => "Hyper Buoy",
        86 => "Asteroid",
        87 => "Planet",
        88 => "Rendezvous Buoy",
        89 => "Cargo Canister",
        90 => "Shipyard",
        91 => "Repair Yard",
        92 => "Modified Strike Cruiser",
        93 => "Lancer Frigate",
        94 => "Bulk Cruiser",
        95 => "Assault Frigate",
        96 => "Corellian Gunship",
        97 => "Sentinel Landing Craft",
        98 => "Assault Shuttle",
        99 => "Marauder Corvette",
        100 => "Star Galleon",
        101 => "Imperial Research Ship",
        102 => "Luxury Yacht",
        103 => "Ferryboat Liner",
        104 => "Modified Action Transport",
        105 => "Mobquet Transport",
        106 => "Xiytiar Transport",
        107 => "Freight Transport/C",
        108 => "Freight Transport/H",
        109 => "Freight Transport/K",
        110 => "YT-2000 Transport",
        111 => "YT-2400 Transport",
        112 => "Suprosa Bulk Freighter",
        113 => "Skipray Blastboat",
        114 => "TIE X/1 Bizarro",
        115 => "TIE X/2 BigGun",
        116 => "TIE X/3 Warhead",
        117 => "TIE X/4 Bomb",
        118 => "TIE X/5 Booster",
        119 => "Cloakshape Fighter",
        120 => "Razor Fighter",
        121 => "Planetary Fighter",
        122 => "Supa Fighter",
        123 => "Pinook Fighter",
        124 => "TIE Advanced x1",
        125 => "Preybird Fighter",
        126 => "StarViper",
        127 => "Firespray Attack Ship",
        128 => "Pursuer Enforcement Ship",
        129 => "Golan One",
        130 => "Golan Two",
        131 => "Golan Three",
        132 => "Derilyn Platform",
        133 => "Sensor Array",
        134 => "Comm Relay",
        135 => "Space Colony 1",
        136 => "Space Colony 2",
        137 => "Space Colony 3",
        138 => "Casino",
        139 => "Cargo Facility 1",
        140 => "Cargo Facility 2",
        141 => "Asteroid Mining Unit",
        142 => "Processing Plant",
        143 => "Rebel Alliance Platform",
        144 => "Imperial Research Centre",
        145 => "Azzameen Family Base",
        146 => "Family Repair Yard",
        147 => "Pirate Asteroid Base",
        148 => "Industrial Complex",
        149 => "Pirate Junkyd Base",
        150 => "Escape Pod",
        151 => "Pressure Tank",
        152 => "CN/J Grande",
        153 => "CN/K Box",
        154 => "CN/L Sphere",
        155 => "Container Hangar",
        156 => "Large Gun Emplacement",
        157 => "Large G/W Emplacement",
        158 => "Proximity Mine A",
        159 => "Detonator",
        160 => "Homing Mine A",
        161 => "Homing Mine B",
        162 => "Laser Battery",
        163 => "Ion Battery",
        164 => "Cargo Freighter",
        165 => "Connector Rod",
        166 => "Cargo Freighter Engine",
        167 => "Cargo Freighter 4",
        168 => "Cargo Freighter 5",
        169 => "Cargo Tanker Engine",
        170 => "Cargo Tanker",
        171 => "Cargo Tanker 3",
        172 => "Cargo Tanker 4",
        173 => "Cargo Tanker 5",
        174 => "Escape Pod Deluxe",
        175 => "Rebel Pilot",
        176 => "Imperial Pilot",
        177 => "Civilian Pilot",
        178 => "Zero-G Stormtrooper",
        179 => "Zero-G Utility Worker",
        180 => "MK-09 Droid",
        181 => "Astromech Droid",
        182 => "Worker Droid",
        183 => "BACKDROP",
        184 => "V-Wing",
        185 => "Y-Wing/B",
        186 => "U-Wing",
        187 => "M3-A Scyk",
        188 => "G1-M4-C Dunelizard",
        189 => "M-12 Kimogila",
        190 => "M-22 Krayt Gunship",
        191 => "DontUseMe",
        192 => "DontUseMe",
        193 => "DontUseMe",
        194 => "DontUseMe",
        195 => "VT-49 Decimator",
        196 => "X4 Gunship",
        197 => "YE-4 Gunship",
        198 => "DontUseMe",
        199 => "YKL-37R Nova Courier",
        200 => "DontUseMe",
        201 => "DontUseMe",
        202 => "Naboo Barge",
        203 => "Coruscant Courier",
        204 => "YB-300 Light Transport",
        205 => "DontUseMe",
        206 => "DontUseMe",
        207 => "Arquitens Light Cruiser",
        208 => "Acclamator Cruiser",
        209 => "Gladiator Class Star Destroyer",
        210 => "Venator Star Destroyer",
        211 => "Ecliptic Star Frigate",
        212 => "Commerce Guild Destroyer",
        213 => "MC75 Armored Star Cruiser",
        214 => "Quasar Escort Carrier",
        215 => "Sphyrna Corvette",
        216 => "Gozanti Cruiser",
        217 => "MC80 Reef Home Star Cruiser",
        218 => "MC80 Home One Star Cruiser",
        219 => "Backdrop 7",
        220 => "Raider Class Corvette",
        221 => "Orbital Station",
        222 => "Asteroid Tunnel",
        223 => "Large Asteroid 1",
        224 => "Asteroid Field",
        225 => "DontUseMe",
        226 => "n/a",
        227 => "Death Star II",
        228 => "MC80 Liberty Star Cruiser",
        229 => "Victory II Star Destroyer",
        230 => "Imperial II Star Destroyer",
        231 => "Large Asteroid 2",
    ];

    public static $TFTCCRAFTTYPE_XWING = 1;
    public static $TFTCCRAFTTYPE_YWING = 2;
    public static $TFTCCRAFTTYPE_AWING = 3;
    public static $TFTCCRAFTTYPE_BWING = 4;
    public static $TFTCCRAFTTYPE_TIEFIGHTER = 5;
    public static $TFTCCRAFTTYPE_TIEINTERCEPTOR = 6;
    public static $TFTCCRAFTTYPE_TIEBOMBER = 7;
    public static $TFTCCRAFTTYPE_TIEADVANCED = 8;
    public static $TFTCCRAFTTYPE_TIEDEFENDER = 9;
    public static $TFTCCRAFTTYPE_AUTHORITYIRD = 10;
    public static $TFTCCRAFTTYPE_TOSCANFIGHTER = 11;
    public static $TFTCCRAFTTYPE_MISSILEBOAT = 12;
    public static $TFTCCRAFTTYPE_TWING = 13;
    public static $TFTCCRAFTTYPE_Z95HEADHUNTER = 14;
    public static $TFTCCRAFTTYPE_R41STARCHASER = 15;
    public static $TFTCCRAFTTYPE_ASSAULTGUNBOAT = 16;
    public static $TFTCCRAFTTYPE_LAMBDASHUTTLE = 17;
    public static $TFTCCRAFTTYPE_ESCORTSHUTTLE = 18;
    public static $TFTCCRAFTTYPE_SYSTEMPATROLCRAFT = 19;
    public static $TFTCCRAFTTYPE_SCOUTCRAFT = 20;
    public static $TFTCCRAFTTYPE_STORMTROOPERTRANSPORT = 21;
    public static $TFTCCRAFTTYPE_ASSAULTTRANSPORT = 22;
    public static $TFTCCRAFTTYPE_ESCORTTRANSPORT = 23;
    public static $TFTCCRAFTTYPE_UTILITYTUG = 24;
    public static $TFTCCRAFTTYPE_COMBATUTILITYVEHICLE = 25;
    public static $TFTCCRAFTTYPE_CNABRICK = 26;
    public static $TFTCCRAFTTYPE_CNBHEXBOX = 27;
    public static $TFTCCRAFTTYPE_CNCTUBE = 28;
    public static $TFTCCRAFTTYPE_CNDPRONGED = 29;
    public static $TFTCCRAFTTYPE_HEAVYLIFTER = 30;
    public static $TFTCCRAFTTYPE_MOLEMINER = 31;
    public static $TFTCCRAFTTYPE_BULKFREIGHTER = 32;
    public static $TFTCCRAFTTYPE_CARGOFERRY = 33;
    public static $TFTCCRAFTTYPE_MODULARCONVEYOR = 34;
    public static $TFTCCRAFTTYPE_CONTAINERTRANSPORT = 35;
    public static $TFTCCRAFTTYPE_MEDIUMTRANSPORT = 36;
    public static $TFTCCRAFTTYPE_MUURIANTRANSPORT = 37;
    public static $TFTCCRAFTTYPE_YT1300TRANSPORT = 38;
    public static $TFTCCRAFTTYPE_MILLENNIUMFALCON = 39;
    public static $TFTCCRAFTTYPE_CORELLIANCORVETTE = 40;
    public static $TFTCCRAFTTYPE_MODIFIEDCORVETTE = 41;
    public static $TFTCCRAFTTYPE_NEBULONBFRIGATE = 42;
    public static $TFTCCRAFTTYPE_NEBULONB2FRIGATE = 43;
    public static $TFTCCRAFTTYPE_C3PASSENGERLINER = 44;
    public static $TFTCCRAFTTYPE_CARRACKCRUISER = 45;
    public static $TFTCCRAFTTYPE_STRIKECRUISER = 46;
    public static $TFTCCRAFTTYPE_ESCORTCARRIER = 47;
    public static $TFTCCRAFTTYPE_DREADNAUGHT = 48;
    public static $TFTCCRAFTTYPE_MC80ACHATNOIRSTARCRUISER = 49;
    public static $TFTCCRAFTTYPE_MC40ALIGHTCRUISER = 50;
    public static $TFTCCRAFTTYPE_INTERDICTOR = 51;
    public static $TFTCCRAFTTYPE_VICTORYISTARDESTROYER = 52;
    public static $TFTCCRAFTTYPE_IMPERIALISTARDESTROYER = 53;
    public static $TFTCCRAFTTYPE_SUPERSTARDESTROYER = 54;
    public static $TFTCCRAFTTYPE_CNEHEMISPHERE = 55;
    public static $TFTCCRAFTTYPE_CNFSLOTTED = 56;
    public static $TFTCCRAFTTYPE_CNGHOURGLASS = 57;
    public static $TFTCCRAFTTYPE_CNHGEM = 58;
    public static $TFTCCRAFTTYPE_CNIYSHAPED = 59;
    public static $TFTCCRAFTTYPE_PLATFORM1 = 60;
    public static $TFTCCRAFTTYPE_PLATFORM2 = 61;
    public static $TFTCCRAFTTYPE_PLATFORM3 = 62;
    public static $TFTCCRAFTTYPE_PLATFORM4 = 63;
    public static $TFTCCRAFTTYPE_PLATFORM5 = 64;
    public static $TFTCCRAFTTYPE_PLATFORM6 = 65;
    public static $TFTCCRAFTTYPE_ASTEROIDHANGAR = 66;
    public static $TFTCCRAFTTYPE_ASTLASERBATTERY = 67;
    public static $TFTCCRAFTTYPE_ASTWARHDLAUNCHER = 68;
    public static $TFTCCRAFTTYPE_DEEPSPACEFACILITY = 69;
    public static $TFTCCRAFTTYPE_SATELLITE1 = 70;
    public static $TFTCCRAFTTYPE_SATELLITE2 = 71;
    public static $TFTCCRAFTTYPE_SATELLITE3 = 72;
    public static $TFTCCRAFTTYPE_SATELLITE4 = 73;
    public static $TFTCCRAFTTYPE_SATELLITE5 = 74;
    public static $TFTCCRAFTTYPE_MINE1 = 75;
    public static $TFTCCRAFTTYPE_MINE2 = 76;
    public static $TFTCCRAFTTYPE_MINE3 = 77;
    public static $TFTCCRAFTTYPE_GUNPLATFORM = 78;
    public static $TFTCCRAFTTYPE_MINE5 = 79;
    public static $TFTCCRAFTTYPE_PROBE1 = 80;
    public static $TFTCCRAFTTYPE_PROBECAPSULE = 81;
    public static $TFTCCRAFTTYPE_PROBE3 = 82;
    public static $TFTCCRAFTTYPE_TYPE1NAVIGATIONBUOY = 83;
    public static $TFTCCRAFTTYPE_TYPE2NAVIGATIONBUOY = 84;
    public static $TFTCCRAFTTYPE_HYPERBUOY = 85;
    public static $TFTCCRAFTTYPE_ASTEROID = 86;
    public static $TFTCCRAFTTYPE_PLANET = 87;
    public static $TFTCCRAFTTYPE_RENDEZVOUSBUOY = 88;
    public static $TFTCCRAFTTYPE_CARGOCANISTER = 89;
    public static $TFTCCRAFTTYPE_SHIPYARD = 90;
    public static $TFTCCRAFTTYPE_REPAIRYARD = 91;
    public static $TFTCCRAFTTYPE_MODIFIEDSTRIKECRUISER = 92;
    public static $TFTCCRAFTTYPE_LANCERFRIGATE = 93;
    public static $TFTCCRAFTTYPE_BULKCRUISER = 94;
    public static $TFTCCRAFTTYPE_ASSAULTFRIGATE = 95;
    public static $TFTCCRAFTTYPE_CORELLIANGUNSHIP = 96;
    public static $TFTCCRAFTTYPE_SENTINELLANDINGCRAFT = 97;
    public static $TFTCCRAFTTYPE_ASSAULTSHUTTLE = 98;
    public static $TFTCCRAFTTYPE_MARAUDERCORVETTE = 99;
    public static $TFTCCRAFTTYPE_STARGALLEON = 100;
    public static $TFTCCRAFTTYPE_IMPERIALRESEARCHSHIP = 101;
    public static $TFTCCRAFTTYPE_LUXURYYACHT = 102;
    public static $TFTCCRAFTTYPE_FERRYBOATLINER = 103;
    public static $TFTCCRAFTTYPE_MODIFIEDACTIONTRANSPORT = 104;
    public static $TFTCCRAFTTYPE_MOBQUETTRANSPORT = 105;
    public static $TFTCCRAFTTYPE_XIYTIARTRANSPORT = 106;
    public static $TFTCCRAFTTYPE_FREIGHTTRANSPORTC = 107;
    public static $TFTCCRAFTTYPE_FREIGHTTRANSPORTH = 108;
    public static $TFTCCRAFTTYPE_FREIGHTTRANSPORTK = 109;
    public static $TFTCCRAFTTYPE_YT2000TRANSPORT = 110;
    public static $TFTCCRAFTTYPE_YT2400TRANSPORT = 111;
    public static $TFTCCRAFTTYPE_SUPROSABULKFREIGHTER = 112;
    public static $TFTCCRAFTTYPE_SKIPRAYBLASTBOAT = 113;
    public static $TFTCCRAFTTYPE_TIEX1BIZARRO = 114;
    public static $TFTCCRAFTTYPE_TIEX2BIGGUN = 115;
    public static $TFTCCRAFTTYPE_TIEX3WARHEAD = 116;
    public static $TFTCCRAFTTYPE_TIEX4BOMB = 117;
    public static $TFTCCRAFTTYPE_TIEX5BOOSTER = 118;
    public static $TFTCCRAFTTYPE_CLOAKSHAPEFIGHTER = 119;
    public static $TFTCCRAFTTYPE_RAZORFIGHTER = 120;
    public static $TFTCCRAFTTYPE_PLANETARYFIGHTER = 121;
    public static $TFTCCRAFTTYPE_SUPAFIGHTER = 122;
    public static $TFTCCRAFTTYPE_PINOOKFIGHTER = 123;
    public static $TFTCCRAFTTYPE_TIEADVANCEDX1 = 124;
    public static $TFTCCRAFTTYPE_PREYBIRDFIGHTER = 125;
    public static $TFTCCRAFTTYPE_STARVIPER = 126;
    public static $TFTCCRAFTTYPE_FIRESPRAYATTACKSHIP = 127;
    public static $TFTCCRAFTTYPE_PURSUERENFORCEMENTSHIP = 128;
    public static $TFTCCRAFTTYPE_GOLANONE = 129;
    public static $TFTCCRAFTTYPE_GOLANTWO = 130;
    public static $TFTCCRAFTTYPE_GOLANTHREE = 131;
    public static $TFTCCRAFTTYPE_DERILYNPLATFORM = 132;
    public static $TFTCCRAFTTYPE_SENSORARRAY = 133;
    public static $TFTCCRAFTTYPE_COMMRELAY = 134;
    public static $TFTCCRAFTTYPE_SPACECOLONY1 = 135;
    public static $TFTCCRAFTTYPE_SPACECOLONY2 = 136;
    public static $TFTCCRAFTTYPE_SPACECOLONY3 = 137;
    public static $TFTCCRAFTTYPE_CASINO = 138;
    public static $TFTCCRAFTTYPE_CARGOFACILITY1 = 139;
    public static $TFTCCRAFTTYPE_CARGOFACILITY2 = 140;
    public static $TFTCCRAFTTYPE_ASTEROIDMININGUNIT = 141;
    public static $TFTCCRAFTTYPE_PROCESSINGPLANT = 142;
    public static $TFTCCRAFTTYPE_REBELALLIANCEPLATFORM = 143;
    public static $TFTCCRAFTTYPE_IMPERIALRESEARCHCENTRE = 144;
    public static $TFTCCRAFTTYPE_AZZAMEENFAMILYBASE = 145;
    public static $TFTCCRAFTTYPE_FAMILYREPAIRYARD = 146;
    public static $TFTCCRAFTTYPE_PIRATEASTEROIDBASE = 147;
    public static $TFTCCRAFTTYPE_INDUSTRIALCOMPLEX = 148;
    public static $TFTCCRAFTTYPE_PIRATEJUNKYDBASE = 149;
    public static $TFTCCRAFTTYPE_ESCAPEPOD = 150;
    public static $TFTCCRAFTTYPE_PRESSURETANK = 151;
    public static $TFTCCRAFTTYPE_CNJGRANDE = 152;
    public static $TFTCCRAFTTYPE_CNKBOX = 153;
    public static $TFTCCRAFTTYPE_CNLSPHERE = 154;
    public static $TFTCCRAFTTYPE_CONTAINERHANGAR = 155;
    public static $TFTCCRAFTTYPE_LARGEGUNEMPLACEMENT = 156;
    public static $TFTCCRAFTTYPE_LARGEGWEMPLACEMENT = 157;
    public static $TFTCCRAFTTYPE_PROXIMITYMINEA = 158;
    public static $TFTCCRAFTTYPE_DETONATOR = 159;
    public static $TFTCCRAFTTYPE_HOMINGMINEA = 160;
    public static $TFTCCRAFTTYPE_HOMINGMINEB = 161;
    public static $TFTCCRAFTTYPE_LASERBATTERY = 162;
    public static $TFTCCRAFTTYPE_IONBATTERY = 163;
    public static $TFTCCRAFTTYPE_CARGOFREIGHTER = 164;
    public static $TFTCCRAFTTYPE_CONNECTORROD = 165;
    public static $TFTCCRAFTTYPE_CARGOFREIGHTERENGINE = 166;
    public static $TFTCCRAFTTYPE_CARGOFREIGHTER4 = 167;
    public static $TFTCCRAFTTYPE_CARGOFREIGHTER5 = 168;
    public static $TFTCCRAFTTYPE_CARGOTANKERENGINE = 169;
    public static $TFTCCRAFTTYPE_CARGOTANKER = 170;
    public static $TFTCCRAFTTYPE_CARGOTANKER3 = 171;
    public static $TFTCCRAFTTYPE_CARGOTANKER4 = 172;
    public static $TFTCCRAFTTYPE_CARGOTANKER5 = 173;
    public static $TFTCCRAFTTYPE_ESCAPEPODDELUXE = 174;
    public static $TFTCCRAFTTYPE_REBELPILOT = 175;
    public static $TFTCCRAFTTYPE_IMPERIALPILOT = 176;
    public static $TFTCCRAFTTYPE_CIVILIANPILOT = 177;
    public static $TFTCCRAFTTYPE_ZEROGSTORMTROOPER = 178;
    public static $TFTCCRAFTTYPE_ZEROGUTILITYWORKER = 179;
    public static $TFTCCRAFTTYPE_MK09DROID = 180;
    public static $TFTCCRAFTTYPE_ASTROMECHDROID = 181;
    public static $TFTCCRAFTTYPE_WORKERDROID = 182;
    public static $TFTCCRAFTTYPE_BACKDROP = 183;
    public static $TFTCCRAFTTYPE_VWING = 184;
    public static $TFTCCRAFTTYPE_YWINGB = 185;
    public static $TFTCCRAFTTYPE_UWING = 186;
    public static $TFTCCRAFTTYPE_M3ASCYK = 187;
    public static $TFTCCRAFTTYPE_G1M4CDUNELIZARD = 188;
    public static $TFTCCRAFTTYPE_M12KIMOGILA = 189;
    public static $TFTCCRAFTTYPE_M22KRAYTGUNSHIP = 190;
    public static $TFTCCRAFTTYPE_DONTUSEME = 191;
    public static $TFTCCRAFTTYPE_DONTUSEME2 = 192;
    public static $TFTCCRAFTTYPE_DONTUSEME3 = 193;
    public static $TFTCCRAFTTYPE_DONTUSEME4 = 194;
    public static $TFTCCRAFTTYPE_VT49DECIMATOR = 195;
    public static $TFTCCRAFTTYPE_X4GUNSHIP = 196;
    public static $TFTCCRAFTTYPE_YE4GUNSHIP = 197;
    public static $TFTCCRAFTTYPE_DONTUSEME5 = 198;
    public static $TFTCCRAFTTYPE_YKL37RNOVACOURIER = 199;
    public static $TFTCCRAFTTYPE_DONTUSEME6 = 200;
    public static $TFTCCRAFTTYPE_DONTUSEME7 = 201;
    public static $TFTCCRAFTTYPE_NABOOBARGE = 202;
    public static $TFTCCRAFTTYPE_CORUSCANTCOURIER = 203;
    public static $TFTCCRAFTTYPE_YB300LIGHTTRANSPORT = 204;
    public static $TFTCCRAFTTYPE_DONTUSEME8 = 205;
    public static $TFTCCRAFTTYPE_DONTUSEME9 = 206;
    public static $TFTCCRAFTTYPE_ARQUITENSLIGHTCRUISER = 207;
    public static $TFTCCRAFTTYPE_ACCLAMATORCRUISER = 208;
    public static $TFTCCRAFTTYPE_GLADIATORCLASSSTARDESTROYER = 209;
    public static $TFTCCRAFTTYPE_VENATORSTARDESTROYER = 210;
    public static $TFTCCRAFTTYPE_ECLIPTICSTARFRIGATE = 211;
    public static $TFTCCRAFTTYPE_COMMERCEGUILDDESTROYER = 212;
    public static $TFTCCRAFTTYPE_MC75ARMOREDSTARCRUISER = 213;
    public static $TFTCCRAFTTYPE_QUASARESCORTCARRIER = 214;
    public static $TFTCCRAFTTYPE_SPHYRNACORVETTE = 215;
    public static $TFTCCRAFTTYPE_GOZANTICRUISER = 216;
    public static $TFTCCRAFTTYPE_MC80REEFHOMESTARCRUISER = 217;
    public static $TFTCCRAFTTYPE_MC80HOMEONESTARCRUISER = 218;
    public static $TFTCCRAFTTYPE_BACKDROP7 = 219;
    public static $TFTCCRAFTTYPE_RAIDERCLASSCORVETTE = 220;
    public static $TFTCCRAFTTYPE_ORBITALSTATION = 221;
    public static $TFTCCRAFTTYPE_ASTEROIDTUNNEL = 222;
    public static $TFTCCRAFTTYPE_LARGEASTEROID1 = 223;
    public static $TFTCCRAFTTYPE_ASTEROIDFIELD = 224;
    public static $TFTCCRAFTTYPE_DONTUSEME10 = 225;
    public static $TFTCCRAFTTYPE_NA = 226;
    public static $TFTCCRAFTTYPE_DEATHSTARII = 227;
    public static $TFTCCRAFTTYPE_MC80LIBERTYSTARCRUISER = 228;
    public static $TFTCCRAFTTYPE_VICTORYIISTARDESTROYER = 229;
    public static $TFTCCRAFTTYPE_IMPERIALIISTARDESTROYER = 230;
    public static $TFTCCRAFTTYPE_LARGEASTEROID2 = 231;

}